### ISSUE TITLE
browserslist query can no longer be a string

### ISSUE THREAD

**Issue by jridgewell** [browserslist/browserslist#240]
Per the README:
> Queries can be a string "> 5%, last 1 version" or an array ['> 5%', 'last 1 version'].

But, after https://github.com/browserslist/browserslist/commit/fcf593b777b200dbc57801f015fabee375ef60ca, it [must be an array](https://github.com/browserslist/browserslist/commit/fcf593b777b200dbc57801f015fabee375ef60ca#diff-28a3689be95c88dd5e7a37db516ab084R53). This is [breaking](https://github.com/babel/babel/issues/7624) Babel's test suites.

**Comment by ai** [comment]
I will fix validation after a few hours. Never thought that somebody uses it like this 😅.

**Comment by ai** [comment]
Fixed 816be55e65c0c76efdf056b4d6587196be4d7d63

**Comment by ai** [comment]
Released in 3.2.2
