### ISSUE TITLE
query for browsers that support ESM and are still officially supported

### ISSUE THREAD

**Issue by graingert** [browserslist/browserslist#242]
Currently I compile with babel-preset-env for "not dead" I'm looking to compile two bundles, one for:

"not dead" and one for "not dead with ESM" and load them like:

```jsx
const page = (bundles) => (
   <script src={bundles.esm} type="module"></script>
   <script src={bundles.es5} nomodule="nomodule" defer="defer"></script>
)
```

this way I deliver new-ish JS to new clients.

**Comment by ai** [comment]
What syntax for feature queries do you suggest?

**Comment by graingert** [comment]
Ah there was already a PR for this

**Comment by graingert** [comment]
https://github.com/browserslist/browserslist/pull/40
