### ISSUE TITLE
intersection/logical and

### ISSUE THREAD

**Issue by graingert** [browserslist/browserslist#243]
I'd like to support `(edge >= 16, chrome >= 61, safari >= 11, ios >= 11.2, and_chr >= 64) and not discontinued`

**Comment by graingert** [comment]
eg chrome 61, 63 and 64 would be removed because they have been discontinued.

**Comment by graingert** [comment]
same end goal as https://github.com/browserslist/browserslist/issues/242

**Comment by ai** [comment]
I afraid it will make parser and config too complicated. It will dramatically reduce project maintability.

So I need really good use cases to add it.

**Comment by graingert** [comment]
"supports websockets, and supports local-storage, and > 1%"

Or for me "supports modules and not discontinued"

**Comment by ai** [comment]
Can I Use DB is more complicated than just supported/unsupported. It has prefix and notes. Should we cover them as well?

**Comment by ai** [comment]
Work in the process https://github.com/browserslist/browserslist/pull/286

**Comment by dotnetCarpenter** [comment]
@graingert `edge >= 16, chrome >= 61, safari >= 11, ios >= 11.2, and_chr >= 64 and not dead` is now supported in #286 and currently give this result:

```
and_chr 70
chrome 71
chrome 70
chrome 69
chrome 68
chrome 67
chrome 66
chrome 65
chrome 64
chrome 63
chrome 62
chrome 61
edge 18
edge 17
edge 16
ios_saf 12.0-12.1
ios_saf 11.3-11.4
ios_saf 11.0-11.2
safari 12
safari 11.1
safari 11
```

**Comment by dotnetCarpenter** [comment]
@ai I think you can close this issue now
