### ISSUE TITLE
'cover' query doesn't work

### ISSUE THREAD

**Issue by robbyemmert** [browserslist/browserslist#244]
It doesn't work in your online demo, or from the CLI.

'cover 95%' throws an error

**Comment by ai** [comment]
If you report about error always copy the full error message

**Comment by robbyemmert** [comment]
You can view the error here: http://browserl.ist/?q=cover+95%25

BrowserslistError: Unknown Browser Query `Cover 95%`

**Comment by ai** [comment]
Online demo is not official and could contain old version of Browserslist.

You should create a issue in online demo repo.
