### ISSUE TITLE
support 'next' query or selecting beta/alpha explicitly

### ISSUE THREAD

**Issue by tomkel** [browserslist/browserslist#245]
Say if I want to only select chrome beta, there is no way to currently do that. 

A couple ideas:
```
next 1 chrome versions
```
```
unreleased chrome beta
```

**Comment by ai** [comment]
We already support `unreleased versions` or `unreleased Chrome versions` https://github.com/browserslist/browserslist#queries

We don’t have data from Can I Use to select beta/alpha (and different browsers have a little different policy, so we can ignore it).
