### ISSUE TITLE
Changelog in releases' description

### ISSUE THREAD

**Issue by evgeny-petukhov** [browserslist/browserslist#248]
Please, can you write changelog in releases' descrition. It's very useful.

**Comment by evgeny-petukhov** [comment]
Thanks ;)

**Comment by ai** [comment]
https://github.com/browserslist/browserslist/blob/master/CHANGELOG.md

**Comment by evgeny-petukhov** [comment]
Of course, it's very cool that project has detailed changelog. But when people want to see releases they first go to releases tab on GitHub and see there only tags of releases. And it's also useful sometimes to share link with release to show changes.

**Comment by ai** [comment]
O, you mean GitHub Releases?

I tried it for Autoprefixer and it is a little hard to track both `CHANGELOG.md` and GitHub Releases :(.

**Comment by evgeny-petukhov** [comment]
Also it's very very useful when you subscribe to releases using RSS. For example I do so with browserslist but receive only tags in my feed and need to go to repo and changelog to see changes.

**Comment by evgeny-petukhov** [comment]
Is there no some tool that automatically write changelog after release?

**Comment by ai** [comment]
I don’t know about any. But I will be happy if you found something.

**Comment by evgeny-petukhov** [comment]
I'll to find. Or it's very good idea for new tool.

**Comment by evgeny-petukhov** [comment]
Great thanks for quick replies!
