### ISSUE TITLE
Drop support for "last 2 versions"

### ISSUE THREAD

**Issue by ntwb** [browserslist/browserslist#249]
Ref: https://jamie.build/last-2-versions https://twitter.com/jamiebuilds/status/988559577313492992

I think this raises a good point, I think the docs should be updated to no longer document "last 2 versions" in any codde examples.

The docs reference "last 2 versions" quite a number of times, this could be considered recommended based on the widespread usage examples.

I think the examples should be updated to better reflect practicle use cases.

**Comment by ai** [comment]
Browserslist best practices are not to change browsers.

Browserslist has a very good default. I know only a few businesses which need to change browsers.

But I am open to PR with changing examples.

/cc @jamiebuilds

**Comment by jamiebuilds** [comment]
> Browserslist best practices are not to change browsers.
> 
> Browserslist has a very good default. I know only a few businesses which need to change browsers.

I don't understand

**Comment by ai** [comment]
@jamiebuilds I mean, that most of developers should not change Autoprefixer’s browsers.

Most developers just set very exclusive lost of browsers and cut many popular browsers and versions.

**Comment by jamiebuilds** [comment]
I'll open a PR, but I don't think that's enough. I think it should be completely removed

**Comment by casey6** [comment]
Perhaps the "last X versions" query has been misunderstood by a lot of developers. But it absolutely has a use-case and should not be removed. Every contract I've seen has had terminology like "we will support the latest two versions of browsers". That query helps fulfill very common contractual obligations that developers have.

**Comment by ntwb** [comment]
That terminology:
> _"we will support the latest two versions of browsers"_ 

should probably be updated to something like:
>  _"we will support the latest two versions of browsers with a market share > 1%"_

**Comment by ntwb** [comment]
> Some <1% browsers in global market have >5-10% in local markets.
> 
> Since Western software developers mostly ignore other markets, having this logic will force developers to make websites unaccessible for people from some countries.

+100, I fully and unconditionally support this ♥️ 

But I **do** think that there needs to be a way either by code, or by clear concise documentation warning that if you use `last 2 versions` then would be including support for IE 10, IE Mobile 10, Blackberry 7

**Comment by ai** [comment]
Agree. We must exclude dangerous browsers without security update to make Web secure.

But I think explicit `last 2 versions, not dead` will be better.

We can add Best Practices docs section to force `not dead` and other good things. What do you think? What we should mentioned there?

I already opened issues for this section.

**Comment by ai** [comment]
Anyway, we can’t drop a query in patch/minor release.

I close this issue to move discussion to issue about improving the docs #252
