### ISSUE TITLE
Queries recommendation

### ISSUE THREAD

**Issue by ai** [browserslist/browserslist#252]
Describe why `last 2 versions` or `last 2 Chrome versions, last 2 Firefox versions` are bad.

Promote `>1%`, `>1% in US` or `>1% in my stats` as better replacement.

Promote `not dead`.

**Comment by ai** [comment]
https://github.com/browserslist/browserslist#best-practices

@jamiebuilds @ntwb @casey6 what do you think about these recommendations?

**Comment by jamiebuilds** [comment]
updated it a little bit in #254
