### ISSUE TITLE
Chrome 66

### ISSUE THREAD

**Issue by txwizard** [browserslist/browserslist#255]
Last night, I was working with my Gulp build chain, which relies on the default browserslist, since it has no configuration settings to override it. Everything was working as expected in both Edge and Chrome. Today, I resume, and quickly notice that a page that I am certain rendered correctly last night no longer renders. Eventually, I managed to dump the default browserslist, which is as follows.
```
browserslist QUERIES defaults
and_chr 64
and_ff 57
and_qq 1.2
and_uc 11.8
android 62
android 4.4.3-4.4.4
android 4.4
baidu 7.12
chrome 65
chrome 64
chrome 63
chrome 49
edge 16
edge 15
firefox 59
firefox 58
firefox 52
ie 11
ie_mob 11
ios_saf 11.0-11.2
ios_saf 10.3
op_mini all
op_mob 37
op_mob 12.1
opera 51
opera 50
opera 49
safari 11
safari 10.1
samsung 6.2
samsung 5
samsung 4

```
The newest Chrome version listed is 65. However, a quick check revealed that, as of today, my Chrome installation is of version 66, which isn't listed, and was published yesterday. The announcement is at [https://productforums.google.com/forum/#!topic/chrome/NIlcl7hf6oo](url), and is dated yesterday. I am concerned about how its absence might make tools such as Babel behave, and whether that accounts for the sudden change in behavior. Incidentally, the page behaves correctly today when rendered in Edge. 

I have two active projects, for which NPM gives the following reports.

**Project 1**
```
npm list browserslist
armatus-admin@1.0.0 F:\Praesidium_SVN\ALTPS\admin
+-- babel-preset-env@1.6.1
| `-- browserslist@2.11.3
`-- gulp-autoprefixer@5.0.0
  `-- autoprefixer@8.2.0
    `-- browserslist@3.2.4
```
**Project 2**

```
npm list browserslist
css-constructor@0.0.27 F:\Praesidium\Armatus_Admin_EventRegistration\_Stories\DT_563\withStyles_Issue_20180427\css-constructor
+-- babel-preset-env@1.6.1
| `-- browserslist@2.11.3
+-- gulp-autoprefixer@5.0.0
| `-- autoprefixer@8.3.0
|   `-- browserslist@3.2.6
`-- react-scripts@1.0.0
  +-- autoprefixer@7.1.0
  | `-- browserslist@2.11.3  deduped
  `-- css-loader@0.28.1
    `-- cssnano@3.10.0
      +-- autoprefixer@6.7.7
      | `-- browserslist@1.7.7
      `-- postcss-merge-rules@2.1.2
        +-- browserslist@1.7.7
        `-- caniuse-api@1.6.1
          `-- browserslist@1.7.7
```
The above listings are quite confusing, and they tell me nothing about where the default browsers list originates. Please enlighten me, and the lurkers who are too shy to speak up. Hailing frequencies are open and clear.

**Comment by ai** [comment]
Hi. Sorry, sometimes browsers data can be outdated for few days.

Browserslist doesn't have own data. It uses [Can I Use](https://github.com/Fyrd/caniuse/). Trey tries to update it rapidly but a few hours or days delay can happen. 

So, if it critical to you:

1. Try to update `caniuse-db` npm package every day.
2. Browsers do not remove support. If something work in `n-1` browser versions if will work `n` browser version. If something doesn’t work, it more likely to be a browser issue. Try to investigate it.

**Comment by txwizard** [comment]
Thank you @ai for your prompt, clear, concise, actionable response.

Your response left one thing that seems unclear, because I don't know enough about the internals of such tools as Babel to answer the question for myself. Do I understand correctly that e. g., Babel generates one stream of code that is compatible with all browsers on the list, so that there is little or no need for browser sniffing? If you don't know, that's quite all right; maybe I should ask on the Babel discussion. 

I'll keep an eye out for your reply, but there is no urgency, nor need to re-open this issue.

**Comment by ai** [comment]
Nope. Babel doesn't generate output for everyone.

Let's explain on the example. We have `const [first] = array` input. This JS contains 2 new syntax features: `const` variable and `[first] =` destructor (it means put first array child to this variable).

If you pass `last 2 Chrome versions` to Browserslist, Babel will not change anything in the code, since Chrome support both features.

If you pass `last 2 Edge versions`, Babel replace `[first] = array` to `first = array[0]` because Edge doesn't support destructors.

If you pass `last 2 IE versions` Babel replace both features to old analogies `var first = array[0]`.

So Babel left some features without polyfills depends on browsers list.

But browsers only add new features, they don't remove features to be compatible with old websites (sometimes they remove hacks or unofficial and non-popular features, but we can ignore it). Edge will always understand `array[0]`.
