### ISSUE TITLE
crawler/robot mappings

### ISSUE THREAD

**Issue by lunelson** [browserslist/browserslist#256]
Having recently read that googlebot is based on a specific browser, I wondered if it was possible to gather the mappings of all the crawler bots to know which browsers they equated to (mainly for the purpose of JavaScript compatibility). 

@ai's suggestion was that I create a repo to hold these mappings but I'm afraid I don't know enough about how user-agent strings map to browsers. The following article for example, lists what the user-agent strings are for various bots. Can anyone give any insight on how to process this information further?

https://www.keycdn.com/blog/web-crawlers/

**Comment by ai** [comment]
Hm. Nice idea. It will be useful for Babel to be sure that SPA website will be open in the Google.

I need npm package with a data.

**Comment by ai** [comment]
We don’t need it anymore https://webmasters.googleblog.com/2019/05/the-new-evergreen-googlebot.html
