### ISSUE TITLE
Using "not dead" in package.json does not seem to work

### ISSUE THREAD

**Issue by rowild** [browserslist/browserslist#260]
Probably it is mentioned anywhere - if so, I am sorry, I really must have overread it -, but it seems that using something like
```
"last 4 Chrome versions, not dead"
```
does not seem to work. The npx browserlist command returns:
```
browserslist: Unknown browser query last 3 Chrome versions, not dead
```
If it does, please point me to the docu or please provide an example...
Thanks a lot!!!

**Comment by ai** [comment]
What you mean “doesn't work” (in issue always try to explicit describe what happened)

**Comment by rowild** [comment]
I did.

**Comment by rowild** [comment]
```
{
"browserslist": [
        "> .01%",
        "not dead",
        "last 3 Chrome versions",
        "last 3 Firefox versions",
        "last 3 Safari versions",
        "last 2 Edge versions",
        "last 1 version",
        "Firefox ESR",
        "not ie <= 11"
    ],
}
```

Also, if I use `> 0.1%` and `last 3 Chrome versions`, the result of `npx browserlist` shows Chrome browser versions down to 18 (similiar with Firefox, ios_safari etc.

What takes precedence?

Thank you very much!!

**Comment by ai** [comment]
It is fixed version? Can you show initial? I want to make error message more clean.

**Comment by rowild** [comment]
What is the "fixed version"?
`ncu -a` shows that all dependencies are up-to-date.
The package.json of browserlist in the node-modules folder shows 
```
  "_from": "browserslist@^3.2.6",
  "_id": "browserslist@3.2.7",
    ...
    "version": "3.2.7"
```
Does that help?

**Comment by ai** [comment]
You are still getting this error message?

**Comment by rowild** [comment]
No, the message is indeed gone. Thank you!
But - what about `> 0.01%` and `last 3 Chrome versions`? What is more important?

**Comment by ai** [comment]
Can you does me version of config when you had the error message?

> what about > 0.01% and last 3 Chrome versions? What is more important?

What did you mean by “important”

**Comment by rowild** [comment]
It is the same config as above.
I expect that "npx browserlist" would only show the last 3 versions of Chrome, when I use "last 3 Chrome versions". But as soon as I use "> 0.01%" it shows almost all versions of Chrome that will be supported. It also makes a rule like "not <= ie11" useless, because suddenly the list show IE support down to version 7...
So I assume something "> 0.01%" should not be used together with "last 3 Chrome versions", right?

**Comment by ai** [comment]
Show me a config when you had `browserslist: Unknown browser query last 3 Chrome versions, not dead` error

> So I assume something "> 0.01%" should not be used together with "last 3 Chrome versions", right?

Why not? I used them both. They means “last 3 Chrome versions **OR** any browser versions with at least 0.01% in market share”. But 0.01% if just to low limit. There is no practical reason to support so rare versions.

**Comment by rowild** [comment]
Example:
```
[package.json]
{
  "browserslist": [
     "last 3 Chrome versions",
     "not <= IE11",
     "> 0.01%"
}

[npx browserlist]
and_chr 66
and_ff 60
and_qq 1.2
and_uc 11.8
android 66
android 4.4.3-4.4.4
android 4.4
android 4.2-4.3
android 4.1
baidu 7.12
chrome 67
chrome 66
chrome 65
chrome 64
chrome 63
chrome 62
chrome 61
chrome 60
chrome 59
chrome 58
chrome 57
chrome 56
chrome 55
chrome 54
chrome 53
chrome 52
chrome 51
chrome 50
chrome 49
chrome 48
chrome 47
chrome 46
chrome 45
chrome 44
chrome 43
chrome 42
chrome 41
chrome 40
chrome 39
chrome 38
chrome 35
chrome 34
chrome 33
chrome 32
chrome 31
chrome 29
chrome 22
chrome 18
chrome 11
edge 17
edge 16
edge 15
edge 14
edge 13
edge 12
firefox 60
firefox 59
firefox 58
firefox 57
firefox 56
firefox 55
firefox 54
firefox 53
firefox 52
firefox 51
firefox 50
firefox 49
firefox 48
firefox 47
firefox 45
firefox 43
firefox 41
firefox 40
firefox 38
firefox 31
firefox 6
firefox 4
ie_mob 11
ios_saf 11.3
ios_saf 11.0-11.2
ios_saf 10.3
ios_saf 10.0-10.2
ios_saf 9.3
ios_saf 9.0-9.2
ios_saf 8.1-8.4
ios_saf 8
ios_saf 7.0-7.1
ios_saf 6.0-6.1
ios_saf 5.0-5.1
op_mini all
op_mob 46
opera 53
opera 52
opera 51
opera 36
opera 23
opera 12.1
opera 11
safari 11.1
safari 11
safari 10.1
safari 10
safari 9.1
safari 9
safari 8
safari 6.1
safari 5.1
safari 5
samsung 6.2
samsung 5
samsung 4
```

Which is NOT good, because I only want latest 3 Chrome versions!  
`autoprefixer` will also generate CSS prefixes for IE7 now? 

```
[package.json]
{
  "browserslist": [
     "last 3 Chrome versions",
     "last 1 version",
}

[npx browserlist]
and_chr 66
and_ff 60
and_qq 1.2
and_uc 11.8
android 66
baidu 7.12
chrome 66
chrome 65
chrome 64
edge 17
edge 16
edge 15
firefox 60
firefox 59
firefox 58
firefox 52
ie_mob 11
ios_saf 11.3
op_mini all
op_mob 46
opera 53
safari 11.1
safari 11
safari 10.1
samsung 6.2
```

Which is correct. 
Why does `> 0.01%` override `last 3 Chrome versions`, but `last 1 version` does NOT override `last 3 Chrome versions`?

I would expect this:
* if there is a `last 3 Chrome versions`, then ONLY support those, not matter, if there is any other more global config
* if there is a `> 0.02%` then support all browsers that have a market share of more then 0.02%, UNLESS there is a more specific configuration like `last 3 Chrome versions`, in which case only the last 3 version of Chrome will be supported.

I fear that, when npx browserlist shows me IE 7, then all other plugins like autoprefixer will recognize IE7, too, and act accordingly... which is no desired.

**Comment by ai** [comment]
> Which is NOT good, because I only want latest 3 Chrome versions!

In this case don't use `> 0.01%`

> Why does > 0.01% override last 3 Chrome versions, but last 1 version does NOT override last 3 Chrome versions?

Nobody override each other. They are all combines.

**Comment by rowild** [comment]
Combines!!! Aha! 
Is that mentioned in the docu? Didn't catch my attention...
Thank you!

**Comment by ai** [comment]
Yeap, but maybe not clear. I will try to think how to make it more clear.

Show me a config when you had `browserslist: Unknown browser query last 3 Chrome versions, not dead` error.

**Comment by rowild** [comment]
:-)
As said previously: The config - also the one that caused the error - is the same as the very first one I posted.

Just as an info - maybe that clarifies things: I use Vue/cli webpack, where your browserlist extension is a dependency of some other extension...

Thanks for your help!
