### ISSUE TITLE
Different behavior of "not" operator in package.json and .browserslistrc

### ISSUE THREAD

**Issue by tornography** [browserslist/browserslist#262]
When setting browserslist in `package.json`
```
{
  "browserslist": [
    "last 2 versions",
    "not <1%"
  ]
}
```

I get an error saying

`BrowserslistError: Unknown browser query '<1%'`

while setting these options in `.browserslistrc`
```
last 2 versions
not <1%
```

build works as expected. Just like on http://browserl.ist/?q=last+2+versions%2C+not+%3C1%25

**Comment by ai** [comment]
Seems like you have old Browserslist. Maybe you forget to update it (check `npm outdated`). Or cssnano keep old Browserslist in dependencies (check `npm ls`).

If you have old Browserslist try `not < 1%` (with space). We are trying to solve cssnano problem soon.

**Comment by tornography** [comment]
Browserslist is on 3.2.8, and using `not < 1%` (with space) not working as well.
Still, .browserslistrc and cli (globally, locally) with `"last 2 versions, not <1%"` works.
It just acts differently when set in package.json. Seems like cssnano (?) has a problem with `1%` as it's expecting a browser like `not ie <= 8`.

**Comment by ai** [comment]
@tornography can you check `npm ls` for older Browserslist in some dependency?

`.browserslistrc` works because we added this config only in 3.0.

**Comment by tornography** [comment]
Ok, indeed autoprefixer and caniuse-api have `browserslist@1.7.7` as dependency and is not using the module on root level @3.2.8. So I need to investigate in different direction.

```
├─┬ @vue/cli-plugin-babel@3.0.0-beta.6
│ └─┬ @vue/babel-preset-app@3.0.0-beta.6
│   └─┬ @babel/preset-env@7.0.0-beta.44
│     └── browserslist@3.2.8  deduped
├─┬ @vue/cli-service@3.0.0-beta.6
│ ├─┬ autoprefixer@8.3.0
│ │ └── browserslist@3.2.8  deduped
│ └─┬ css-loader@0.28.11
│   └─┬ cssnano@3.10.0
│     ├─┬ autoprefixer@6.7.7
│     │ └── browserslist@1.7.7
│     └─┬ postcss-merge-rules@2.1.2
│       ├── browserslist@1.7.7
│       └─┬ caniuse-api@1.6.1
│         └── browserslist@1.7.7
└── browserslist@3.2.8
```

Thanks for pointing out. Issue can be closed.
