### ISSUE TITLE
Error in npx browserslist npm ERR! code E404

### ISSUE THREAD

**Issue by jitendravyas** [browserslist/browserslist#269]
```
❯ npx browserlist
npm ERR! code E404
npm ERR! 404 Not Found: browserlist@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jitendravyas/.npm/_logs/2018-06-12T07_18_30_019Z-debug.log
Install for browserlist@latest failed with code 1
```

Browserslist version 2.2.2
I use Yarn as package manager

**Comment by ai** [comment]
browserSlist

**Comment by jitendravyas** [comment]
Sorry, it was my mistake. Now command is running but I get this

```
❯ npx browserslist
browserslist: Define queries or browserslist config path.

Usage:
  browserslist "QUERIES"
  browserslist --coverage "QUERIES"
  browserslist --coverage=US "QUERIES"
  browserslist --config="path/to/browserlist/file"
  browserslist --env="environment name defined in config"
  browserslist --stats="path/to/browserlist/stats/file"
```

I thought only `npx browserslist` will return browserslist from my browserslist file

**Comment by ai** [comment]
Show your config (and config file name)

**Comment by jitendravyas** [comment]
![image](https://user-images.githubusercontent.com/77309/41277295-6f8794c8-6e44-11e8-87f8-95c2d7d6b7e2.png)

file name is just `browserslist` and this is code inside it

```
last 3 Chrome versions
last 3 Firefox versions
last 3 Edge versions
last 3 Opera versions
last 3 ChromeAndroid versions
last 3 Safari versions

```
Browserslist version 2.2.2

I want to upgrade `browserslist` to latest version too but I afraid of breaking changes.

**Comment by ai** [comment]
Update Browserslist to 3.x

**Comment by jitendravyas** [comment]
> Update Browserslist to 3.x. We fix this issue there.

Do I need to update anything in config too? Along with Upgrading Browserslist to the latest version?

```
last 3 Chrome versions
last 3 Firefox versions
last 3 Edge versions
last 3 Opera versions
last 3 ChromeAndroid versions
last 3 Safari versions
```

**Comment by ai** [comment]
Everything will work.

But I recommend to rename config to `.browserslistrc`.

**Comment by jitendravyas** [comment]
> Everything will work.

Hope everything will work as it was working before. Hope breaking changes in CSS prefixes output if the config is same.

> But I recommend renaming config to .browserslistrc.

Can I know the reason for this recommendation? And after renaming this file, do I need to make any changes somewhere else too?

**Comment by ai** [comment]
There was name conflicts in some npm told with old name.

No, you don't need to change anything.

Here is full list of changes:
https://github.com/browserslist/browserslist/blob/master/CHANGELOG.md#30
