### ISSUE TITLE
Query questions and suggestions

### ISSUE THREAD

**Issue by jonathantneal** [browserslist/browserslist#272]
EDIT: I’m a massive fan of this project. I got a little too excited and skipped to my issues. I want to start by saying 1. I understand and often agree with why previous syntax decisions were made, and 2. I’m willing to help contribute to resolve the issues I am raising (if they even are issues).

Why does http://browserl.ist/?q=last+2+chrome+versions (`last 2 chrome versions`) not include Chrome 67 and 68?

Is this because there is some kind of “current version” that is out of date?

Why does http://browserl.ist/?q=chrome+%3E%3D+65 (`chrome >= 65`) not include Chrome 66, 67, and 68?

This shouldn’t be affected by the “current version”, right?

Why does http://browserl.ist/?q=%3C+0.05%25%2C+not+chrome+%3E+0 (`< 0.05%, not chrome > 0`) include Chrome 67 and 68?

This seems like bad “current version” logic.

Why does http://browserl.ist/?q=last+3+versions%2C+not+dead (`last 3 versions, not dead`) include IE9 but not IE10?

Probably because `dead` is defined as:

> browsers from `last 2 version` query, but with less than 0.5% in global usage statistics and without official support or updates for 24 months.

Instead, I would suggest the query be:

> browsers with less than 0.5% in global usage statistics that are either not the last 2 versions, or are the last 2 versions but have been without official support or updates for 2 years.

And how might one write the above query on their own? Is there a way to write ANDs and ORs?

**Comment by ai** [comment]
Can you try this tests on local Browserslist installation with latest Can I Use data. This site is not official and I am not sure that Can I Use data is latest.

**Comment by ai** [comment]
Every your queries has no affect from `dead` policy. You must explicitly set `not dead` query to remove dead browsers.

**Comment by ai** [comment]
@jonathantneal this website contains old Browserslist. I fixed removing IE 9 on `not dead` in a recent release. Can you try latest Browserslist by CLI?
