### ISSUE TITLE
The "-webkit-box-orient" is missing while last 2 versions

### ISSUE THREAD

**Issue by Alsmile** [browserslist/browserslist#274]
last 2 version

[.scss] 
 `    
-webkit-box-orient: vertical;  
text-overflow: ellipsis;  
... 
`  
The  "-webkit-box-orient: vertical;" is missing.

"last 5 version " is work and not missing. Why?

**Comment by ai** [comment]
It happens, because Autoprefixer remove this property. Add `/* autoprefixer: ignore next */` above the rule.
