### ISSUE TITLE
Get current version based on date

### ISSUE THREAD

**Issue by metaa** [browserslist/browserslist#275]
Let's say I want to find out the versions that were considered "current" back in June 2015.
Currently there is no way to do that except using `since` and then cutting off everything but the first version listed in there.

Could we add something like `current <DATE>`?

Looking forward to a discussion.

**Comment by ai** [comment]
Hi. It is cool idea 😄.

Tell me more about your use case. I need it to make API better.

**Comment by metaa** [comment]
I'd use it to do these things:
- find out what versions were current back when some project started
- find out how outdated the version from back then is (if I started a project in December 2017, the most current Edge would be 17 which is still current, whereas we've had 5 versions of Chrome since)
- compare feature support based on date

and probably some more useful stuff 😊

**Comment by ai** [comment]
Maybe it is better to create septated tool. All this use cases are mostly for researching, not for using in `.browserslistrc`.

I can put a link to your tool in Browserslist docs.

Does it look reasonable?
