### ISSUE TITLE
extend rel-path and/or support js/json

### ISSUE THREAD

**Issue by Iyashi** [browserslist/browserslist#277]
Hey \o/

first of all I want to thank you for this great tool. Helped a hell of a lot in web-dev!

But there's still a thing that bothers me:
In combination with some tools used in web-dev (eslint, stylelint, webpack, babel, ..) there's a lot to configure and each tool has its own configuration file which is, in most cases, named by the following pattern: `<>.config.js`. Except for `.browserslistrc` which doesnt even understand js/json syntax (or if it does, please doc it :))
 (some node versions before it was `.<>rc`, same as browserslist now, but any tool is going to `<>.config.js`)

Current directory structure example
```
- eslint.config.js
- stylelint.config.js
- webpack.config.js 
- babel.config.js # default since 7.0.0, else .babelrc;  but configurable since always
- .browserslistrc
- src/
- tests/
```

Both wanted directory structures to be possible:
```
   in /
 - eslint.config.js
 - stylelint.config.js
 - webpack.config.js 
 - babel.config.js
 - browserslist.config.js
 - src/
 - tests/
```
```
   in /config
 - config/eslint.js
 - config/stylelint.js
 - config/webpack.js 
 - config/babel.js
 - config/browserslist.js
 - src/
 - tests/
```

My package.json is clean and in my opinion there's not a single reason why `package.json` should contain configurations for any of the external tools as they belong to their specific config files _only_. What I would accept is a _delegation_ of config **_files_** (**not** new npm packages for just one .browserslist file!) by setting up relative paths like this:
```js
{ // package.json
  "name": 'my-package',
  // ...
  "browserslist": [ "extend ../path/to/.browserslistrc" ]
  // or much better: with js/json support!
  "browserslist": [ "extend ../path/to/browserslist.config.js" ]
}
```

Keep up the great work! :)

Best wishes

**Comment by ai** [comment]
You want some global config directory to keep Browserslist config there instead of project root?

Right now you can:

```
BROWSERSLIST_CONFIG=./config/browserslist gulp css
```

I need some agreement in community about the dir name to support it out of box.

**Comment by Iyashi** [comment]
To generalize

### Configurable config-path / config-dir
I would like to have one (or at best _all_) of these:
- a configurable `config/` directory (auto-search for .browserslistrc, browserslist.config.js, ...)
- a configurable `path/to/config.file` (not dir, but file already. No auto-search needed anymore)

Examples:
1. `browserslist --config ../config` (auto search `.browserslistrc` in given dir)
2. `browserslist --config ../config/.browserslistrc` (use exact given file)
3. `browserslist --config ../config/.browserslist.custom` (use exact given file)
4. `browserslist --config browserslist-config-my-awesome-package` (npm-package, as now)
4. `browserslist --config ./browserslist-config-my-awesome-package`
  (if dir: auto search `.browserslistrc`, if file: use exact given file)

### Extend shareable config with relative path
(instead of only "browserslist-config-*" packages)

Examples:
```
{ // package.json
  name: "my-awesome-package",
  browserslist: [ "extend ../config" ], // auto-search ../config/.browserslistrc
  // .. or
  browserslist: [ "extend ../config/.browserslist.custom" ],
}
```
Now I dont have to configure `.browserslist` anymore for each eslint, stylelint, babel and such as they look for `"browserslist"` in `package.json` themselfs.
And I dont need a `browserslist-config-my-awesome-project` package anymore. I personally dont like to have so many custom npm packages for my own projects (if its just one file with only 3 lines of code, that is))

### Enable js / json support for config-files
First of all, the config-file name could finally get from `.browserslistrc` to `browserslist.config.js`. Following footsteps of the "big players" (missing a word :D) eslint, stylelint, babel, webpack, ...

You would be able to actually construct the browserslist with javascript for your actual environment

Example:
Consider some kind of IoT device with _a browser_ as GUI-"Framework". Whatever browser you use in the end, it will not change until you change the sources. Users cant install new browsers or change versions. In this case I could create a nodejs script that search the installed browser + version" which could improve/minify/polyfill/... my code for that specific browser always and I would never have to reconfigure, even if I change browser
(of course, that example is some-what dreamy, but the case should get clear)

**Comment by ai** [comment]
> browserslist --config ../config/.browserslistrc

Browserslist CLI already has `--config=path/to/config` option.

But Browserslist CLI is rarely used. The most users use Browserslist in Autoprefixer or Babel. So there is a `BROWSERSLIST_CONFIG` env variable.

> browserslist --config ../config/.browserslist.custom

`BROWSERSLIST_CONFIG` and CLI’s `--config` accepts path to custom config.

> browserslist --config browserslist-config-my-awesome-package

`BROWSERSLIST_CONFIG="extends browserslist-config-my-awesome-package" npm build`

> Extend shareable config with relative path

We disabled it because of security issues. There is a website which accepts Browserslist query from users. Load any file can be dangerous.

But you can still use relative path by `dangerousExtend`.

> Enable js / json support for config-files

Browserslist should be used by non-JS environment. For instance, Autoprefixer Rails uses it. This is why we can’t support JS configs.

> Following footsteps of the "big players" (missing a better word :D) eslint, stylelint, babel

They all accept `.NAMErc` configs ;)
