### ISSUE TITLE
NW.js

### ISSUE THREAD

**Issue by TheJaredWilcurt** [browserslist/browserslist#278]
The list of browsers includes Electron (maps to Chrome version), but not NW.js.

A map of NW.js versions to Chromium/Node versions can be found here:

* https://nwjs.io/versions.json

**Comment by ai** [comment]
Hi. I am not sure that adding Electron was a good idea. It increased the project size, but query is not really popular.

Let's wait. If few other developers will need it too, I will add it.

**Comment by ai** [comment]
Also I need npm package with this data, which will be updated by somebody.
