### ISSUE TITLE
Would you please explain why recommending browserslist key in package.json instead of a .browserslistrc file

### ISSUE THREAD

**Issue by yanni4night** [browserslist/browserslist#279]
I think a .browserslistrc file is a more flexible way, so why recommending package.json? `package.json` is for npm not browserslist.

Then close this issue.

**Comment by ai** [comment]
Hi. Good question.

To be honest, we didn't really recommend `package.json`. Both ways are OK.

We mention `package.json` more often just because it is more popular.

**Comment by yanni4night** [comment]
Got it, thanks.
