### ISSUE TITLE
Unable to install browserlist, npmjs returns 404

### ISSUE THREAD

**Issue by CervantesVive** [browserslist/browserslist#280]
Im trying to install browserlist this morning and it is failing

○ → curl -i https://registry.npmjs.org/browserlist
HTTP/1.1 404 Not Found
Date: Thu, 09 Aug 2018 17:09:24 GMT
Content-Type: application/json
Content-Length: 21
Connection: keep-alive
Set-Cookie: __cfduid=d174b70614bd0ecda3c91af2a4d468e361533834564; expires=Fri, 09-Aug-19 17:09:24 GMT; path=/; domain=.registry.npmjs.org; HttpOnly
cache-control: max-age=300
CF-Cache-Status: MISS
CF-RAY: 447bd48cbdcb51ca-SJC
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Vary: accept-encoding, accept
Server: cloudflare

{"error":"Not found"}

**Comment by ai** [comment]
Sorry, this is npm servers issue. I have no power to fix it.

**Comment by CervantesVive** [comment]
Understood @ai . Any suggestions how can I go about installing browserlist while npm fixes their issues?

I am actually trying to run `npx browserlist`

**Comment by ai** [comment]
Done https://github.com/browserslist/typo

I need npm approve to publish npm package with small difference in the names.

**Comment by ai** [comment]
`browserlist` was released and now will show a warning
