### ISSUE TITLE
Should CLI be able to read exported array from JS file?

### ISSUE THREAD

**Issue by joshingmachine** [browserslist/browserslist#282]
Using the `--config` flag on the CLI allows you to specify a path to a Browserslist file.
https://github.com/browserslist/browserslist/blob/d006526fd9300b6301fb5f0748becb3cc1eb033c/cli.js#L12

Usually that file is either `package.json`, `.browserslist`, or `browserslist`. However, I'm creating a [shareable Browserslist config](https://github.com/browserslist/browserslist/tree/d006526fd9300b6301fb5f0748becb3cc1eb033c#shareable-configs). In that shareable config, there is an `index.js` file similar to the one used in the Browserslist README.
```
module.exports = [
  'last 1 version',
  '> 1%',
  'ie 10'
]
```
I think it would be useful to be able to be able to run
```
npx browserslist --config="./index.js"
```
and then have the CLI be able to iterate over the queries in `index.js`'s exported array in order to produce the same output of supported browsers that would be logged if you ran
```
npx browserslist --config="./.browserslistrc"
```
If you think this is okay, I can look into making a PR, but I wanted to check if this behavior would be desired before starting on it, or to see if you had any suggestions.

Thanks :)

**Comment by ai** [comment]
Hm. My main concern is that Browserslist config should be readable by any software, not only JS based.

But it is a good point, that it doesn't work for sharable configs.

Sure me you use case, and if we have no better solution, I will change my mind.

**Comment by joshingmachine** [comment]
My main use case is that with my shareable Browserslist config, I would like to provide users with a single, simple command to view which browsers the config currently targets. Something like:

> To view which browsers this config targets, run
> ```
> npx browserslist --config="./browserslist-config-joshingmachine/index.js"
> ```

It would even be nice to be able to omit `index.js` with
```
npx browserslist --config="./browserslist-config-joshingmachine"
```

My primary goal is to find a simple and shareable way to list the browsers that are targeted by a shareable Browserslist config. And since there is already [special logic to read `package.json`](https://github.com/browserslist/browserslist/blob/9786b239f2072ed272e3c50efa26a5d225ecb69b/node.js#L159-L160) for the presence of the `browserslist` key and parse its queries, I was curious if reading a `.js` file for an exported array containing Browserslist queries would be appropriate.

**Comment by ai** [comment]
There is much faster way.

1. Put `.browserslist` config to npm package of sharable config.
2. Add `extends browserslist-config-joshingmachine` in this config.

What do you think about it? We can create Browserslist config boilerplate to share this best practices.

I am trying to avoid JS based Browserlist to allow the use of Browserslist in Go/Ruby libraries. I use it in Autoprefixer Rails.

**Comment by joshingmachine** [comment]
I'm sorry, I'm not sure if I follow your suggestion. Do you mean
```
browserslist-config-joshingmachine
├── .browserslist
├── index.js
└── package.json
```
?

**Comment by ai** [comment]
@joshingmachine yeap. This `.browserslist` will be used just to load `index.js` in CLI test
