### ISSUE TITLE
Counter intuitive filtering

### ISSUE THREAD

**Issue by dotnetCarpenter** [browserslist/browserslist#283]
`browserslist` uses a logical `OR` when combining queries which I think is very unfortunate and I did not find any discussion about this in the issue list here.

From the [README Notes](https://github.com/browserslist/browserslist#notes):
> Multiple criteria are combined as a boolean `OR`. A browser version must match at least one of the criteria to be selected.

### Problem
When specifying a set of browsers, it's natural to assume that you create selection/filter of all browsers while constructing your query.

Query example: 
+ `last 2 versions` - should give the last 2 versions of all browsers
+ `last 2 version, not IE > 11` - should give the last 2 versions of all browsers, but no IE below 11
+ `last 2 version, not IE > 11, > 1%` - should give the last 2 versions of all browsers, but no IE below 11 and not any browsers with less than 1% global usage.

**These examples requires that queries are combined with a logical `AND` operator.**

Say you want to target the last version of all browsers, but no IE below 11 and not any browsers with less than 1% global usage. With `browserslist` you **can not**. Well, you can with `> 1%, not IE < 11, not Chrome < 67, not iOS < 11.4` but you have to update the query for each new browser release.

I realize that this is a breaking change and requires a major version bump but I think it's an important discussion and I hope I can convince you all of the usefulness of this.

PS. I came to this issue because I wanted to configure babel to not transpile `const` and `let` to `var` , since I only support browsers that also support `const` and `let`. I'm not sure if it's ultimately is a bug in babel but that I can not target the browsers I want with `browserslist` seems to be the first stop-gap.

Ref: https://github.com/jonrohan/browserl.ist/issues/98

**Comment by ai** [comment]
Let's just add `and` operator to config parser. Do you want to send PR?

**Comment by dotnetCarpenter** [comment]
If there is a will to merge it, I will take a look.

Perhaps it is a good idea to get a release candidate with the PR and then I
can take a look at Babel and see if that is enough to configure the
transpiling of js `let`/`const` statements, which is my current use-case?

My point being, that the implementation have to be useful, end-to-end, for
at least one use-case.

On 10 Aug 2018 16:34, "Andrey Sitnik" <notifications@github.com> wrote:

Let's just add and operator to config parser. Do you want to send PR?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/browserslist/browserslist/issues/283#issuecomment-412101093>,
or mute the thread

**Comment by ai** [comment]
Closing this issue as duplicate for #243
