### ISSUE TITLE
Provide mapping to Chromium versions for Chromium-based browsers

### ISSUE THREAD

**Issue by ylemkimon** [browserslist/browserslist#290]
Most tools use only major browsers version to detect features. For instance, Babel (`babel-preset-env`) only uses `Android`, `Chrome`, `Edge`, `Firefox`, `IE`, `iOS`, `Safari`, `Node` versions for detecting which transforms to include. ([`babel/babel`/`packages/babel-preset-env/src/targets-parser.js`#L32-L42](https://github.com/babel/babel/blob/master/packages/babel-preset-env/src/targets-parser.js#L32-L42)).

However, there are local-popular or manufacturer-specific browsers (see #250 for their importance) such as QQ browser, Baidu browser, UC browser, Samsung Internet, which are based on rather old Chromium and rarely update its version:

* QQ: I'm not sure which version `caniuse` refers to, but latest version 8.7 is based on 57
* Baidu: 7.12 based on **48**, but its user-agent string suggests it may be a WebView wrapper
* UC: 11.8 based on 57
* Samsung: 7 based on 59

Fortunately, IE 11, Chrome 49 (usage 0.69%) and Android 4.x (4.4 usage 0.58%, 4.4.4 isn't strictly last 2 versions) acts as a stopgap preventing from excluding transform needed for old browsers. However, if user excludes them, they become `dead`, or their usage drops, they'll recognize as if it targets very modern browsers.

### Proposal

I think Browserslist should:
* maintain a mapping from their versions to Chromium version, like [`electron-to-chromium`](https://github.com/Kilian/electron-to-chromium)
  * Also possibly Opera
* provide a `mapToChromium` options which adds or substitutes with corresponding Chrome versions.

For example, `browserslist('baidu 7.12', {mapToChromium: true})` returns `['baidu 7.12', 'chrome 48']` or `['chrome 48']`.

I'm willing to open a PR.

#### Alternative

I thought about creating another package for version mappings, but as there are only 7 versions of them `caniuse` provides, and as there is no reliable source other than user agent strings collected by analytic companies, it needs community contribution. (Only reliable source I can find is [Samsung Internet release notes](https://developer.samsung.com/internet/android/releases), but even it doesn't have latest versions.)

**Comment by ylemkimon** [comment]
@ai Babel (and possibly eslint-plugin-compat in the future) uses [Kangax compatibility table](http://kangax.github.io/compat-table/es6/), which doesn't provide data for those browsers. (https://github.com/kangax/compat-table/issues/1001, https://github.com/kangax/compat-table/issues/1247) I've opened an issue at https://github.com/babel/babel/issues/8545 to request a feature to warn about them. But for Chromium-based browsers, I think it's better for upstream (Browserslist) to provide a mapping to Chromium versions, as it already has `electron-to-chromium`, it has to stay up-to-date with caniuse data, and other users and tools can use it.

**Comment by ai** [comment]
There is one problem with adding this mapping to Browserslist. In case of Babel QQ works same as Chrome. But in case of other feature (like payment API) it could work in different way.

So with adding it to Browserslist we will make Babel/Kangax life easier, but in other hand we will make life much harder for other Browserslist’s users (like ESLint plugin which will warn you if some of your target browsers don't support JS API).

This is why I think that main problem here is Kangax. I will upvote your issue.

**Comment by ai** [comment]
If we will have this mapping data, patching Kagnax will be very easy. And it will keep Browserslist API free from hacks and avoid other Kangax non-Browserslist users from making the same mistake of ignoring non-white browsers.

Why you think you should use it here, but not in Kagnax?

**Comment by ai** [comment]
I am closing it since nobody decided to create a data
