### ISSUE TITLE
Maybe, support a `react-native` alias.

### ISSUE THREAD

**Issue by mattyclarkson** [browserslist/browserslist#291]
React Native uses JavaScriptCore from WebKit on Android.

This uses the revision from [facebook/android-jsc](https://github.com/facebook/android-jsc/blob/master/fetch_sources.sh), which at the time of writing is [r174650](https://trac.webkit.org/changeset/174650/webkit).  That commit was committed on 13 Oct 2014 at 10:33:28.

So to make **sure** that your published code will work on *all* React Native JavaScript environments you will need `since 2014-10-13`. However, this is technically a moving target. The React Native developers could update that revision at any point. *Why* they haven't in the last 4 years is beyond me.

Feel free to close if you do not think this is a useful alias.

**Comment by ai** [comment]
I think it is useful, but `since 2014-10-13` is not the best value for alias.

It will include Firefox, Opera, UC from 2014. We need more real value for alias. What engine do they use?

**Comment by mattyclarkson** [comment]
They use JavaScriptCore from WebKit. It would be roughly what is in iOS 9 Safari, however, it's not really because they just used a specific revision. I can check if the revision matches up with a particular tag.

**Comment by ai** [comment]
Yeap, let's use closest Safari version to this revision.

But for there future I need some instructions how to update it. Where to look, what to compare.

**Comment by mattyclarkson** [comment]
I can sort out a script to do that tomorrow, hopefully

**Comment by mattyclarkson** [comment]
Hmm, this creates problems as it does loads of translation that isn't needed. React Native automatically does some translation of the `node_modules` for that old JSC. Let me investigate a little more.

**Comment by mattyclarkson** [comment]
https://github.com/facebook/metro/blob/900bcb0bf8a287521428c70675617e08d779e2de/packages/metro-react-native-babel-preset/src/plugins.js#L13-L36

The only one that is missing is `transform-new-target`. Not sure if this is useful to be set as part of `babel-preset-env` or `babel-preset-react-native` 🤔

**Comment by ai** [comment]
Why did you decide to close it?

**Comment by mattyclarkson** [comment]
As the only transformation needed is `transform-new-target` for the Android builds I don't think it's worth the maintenance on this side.

Really the bug is on the React Native `babel-preset-react-native` which should include that transformation for Android.
