### ISSUE TITLE
Targeting Firefox for iOS

### ISSUE THREAD

**Issue by jpirkey** [browserslist/browserslist#295]
I see that there is a `and_ff`, but no `ios_ff` which appears to be using completely different versioning.  Their current version is [13.2](https://itunes.apple.com/us/app/firefox-web-browser/id989804926?mt=8).  Is there a way to target that?  If not, what are your suggestions?

[caniuse](https://caniuse.com/usage-table) doesn't appear to break it out either unless I am missing something.

**User Agent Details**:
```json
{
"family": "Firefox iOS",
"version": "13",
"agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/13.2b11866 Mobile/15G77 Safari/605.1.15"
}
```

**Comment by ai** [comment]
Yeap, but I have no control on it. All browsers names are coming from Can I Use. And I agree that all names do not cover the real market of browsers.

But you need to open issue there 😣

**Comment by jpirkey** [comment]
Sounds good.  Thanks for the quick response.
