### ISSUE TITLE
Not all browser versions counted

### ISSUE THREAD

**Issue by GreLI** [browserslist/browserslist#302]
Query like `> 4% in RU` returns only 4 browsers:
```sh
$ npx browserslist '> 4% in Ru'
and_chr 69
chrome 68
chrome 67
ios_saf 11.3-11.4
```
However, if one run total statistics, we'll see that Firefox of all version has more than 4%:
```sh
$ npx browserslist --coverage=RU 'Firefox >= 53'
These browsers account for 4.01% of all users in the RU
``` 
(actually StatCounter says it has all 8%).
It really prevents Autoprefixer from applying `-moz-` prefix to some rules like `user-select`.

**Comment by ai** [comment]
Yeap, because `> X%` is a filter which applies to every version. It is not a sum, but the criteria for every version.

In other words: “return me please every version, which has more than 4%”.

**Comment by GreLI** [comment]
Well, it's not expected behavior.

**Comment by ai** [comment]
I am open for docs changes :)
