### ISSUE TITLE
> 0.2% resolve browsers which only have < 0.2 coverage

### ISSUE THREAD

**Issue by chentsulin** [browserslist/browserslist#303]
https://browserl.ist/?q=%3E0.2%25

`0.16%`, `0.19%`, `0.09%`, `0.01%`, `0.19%` should not be considered as `> 0.2%`

<img width="1363" alt="2018-10-09 10 01 24" src="https://user-images.githubusercontent.com/3382565/46674650-46d8f700-cc0f-11e8-83be-5c6e6968a864.png">

**Comment by ai** [comment]
`> 0.2%` means **every version**, which has market share more that `0.2 %`.

It **not** make a sum of versions with share `0.2%`, since there is no single way to make this sum.

**Comment by kpman** [comment]
@ai I don't understand why this issue is closed.

The **Chrome 29**'s market share is **0.16%**, which the query is `> 0.2%`.
As far as I know, the browser's single version market share under this value should not be queried. So the **Edge 16** and **Firefox 60** should not be queried neither.

**Comment by ai** [comment]
@kpman good point. I missed the right  sign in origin issue.

**Comment by ai** [comment]
I tested in CLI and got:

```js
var browsers = browserslist('> 2%')
=> [
   'and_chr 69',
  'and_uc 11.8',
  'chrome 68',
  'chrome 67',
  'firefox 61',
  'ie 11',
  'ios_saf 11.3-11.4',
  'op_mini all'
]
browsers.map(browser => browerslist.coverage([browser]))
=> [
  32.6856,
  6.32084,
  18.6191,
  5.93095,
  3.24883,
  2.65721,
  7.93493,
  2.46565
]
```

Everything as expected. Maybe [browserl.ist](https://browserl.ist) uses old Browserslist? It is not the official web interface. (it is always better to use CLI to have the same `caniuse-lite` version)
