### ISSUE TITLE
Unknown browser query `var browserslist = require('./')`

### ISSUE THREAD

**Issue by JMitnik** [browserslist/browserslist#304]
Hi,
I saw a similar issue, but found that none of those solutions could be applied here, so I thought I would try this again. This problem seems to come up in every project, more or less, and in directories without any specific `package.json` either; running `npx browserslist` returns the error of `Unknown browser query var browserslist = require('./')`, and when running Gatsby or some pre-built working configuration of a GraphQL error, I get the following error:

```
Module build failed (from ./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js):
BrowserslistError: [BABEL] /**/pages/index.js: Unknown browser query `var browserslist = require('./')`. Maybe you are using old Browserslist or made typo in query. (While processing: "/**/frontend/node_modules/next/babel.js$0")
    at Array.reduce (<anonymous>)
    at Array.reduce (<anonymous>)
```.

I have not touched nor configured any browserslist variable, nor have any configuration in my root directories. The fact that this same error (shorter version) is returned in any arbitrary directory suggest that somewhere in my npm settings, I might have once saved this, but I doubt that. Any idea what this could be?

**Comment by ai** [comment]
Something bad with config. Somebody put a JS there. Maybe Gatsby uses Browserslist API in the wrong way.

Can you show your `package.json`, `.browserslistrc`, and `browserslist` files?
