### ISSUE TITLE
Support relative month or/and year fraction

### ISSUE THREAD

**Issue by yukulele** [browserslist/browserslist#308]
`"last 2 years"` is supported

month should be supported:
examples:
* `"last 18 months"`
* `"last 1.5 years"`

**Comment by ai** [comment]
@yukulele do you want to send PR with `1.5 years` support? https://github.com/browserslist/browserslist/blob/master/index.js#L436-L441

I am not sure that somebody will use `month` (the query is not really popular). Unnecessary code for `month` will increase client-side bundle. I need use cases for `month`.

**Comment by yukulele** [comment]
https://github.com/browserslist/browserslist/pull/309
