### ISSUE TITLE
last X versions & greater than seem to only favor last X versions

### ISSUE THREAD

**Issue by gauntface** [browserslist/browserslist#315]
I've been trying the query `last 2 versions, > 1%`.

https://browserl.ist/?q=last+2+versions%2C+%3E+1%25

I'm reading it as, pick the last 2 versions that have more than 1% usage, but it seems that's not how it works. Any ideas what I'm doing wrong?

Thanks,
Matt

**Comment by ai** [comment]
Queries combine together with `OR`

**Comment by ai** [comment]
Do you have the idea, how we can improve docs?

**Comment by ai** [comment]
Here is PR with `and` query #286

You can finish it off you want

**Comment by gauntface** [comment]
I know it sounds stupid, but adding some examples to browserl.ist and / or a list of available queries would have been perfect.

**Comment by ai** [comment]
@gauntface sure, but `browserl.ist` is not official, so I can’t do anything. You can open an issue https://github.com/jonrohan/browserl.ist
