### ISSUE TITLE
Query text for supporting MDC Web

### ISSUE THREAD

**Issue by Richienb** [browserslist/browserslist#317]
I'm just wondering what query code should I use to match all versions supported by the Material Design Components for the Web library?

**Comment by ai** [comment]
Sure. What browsers do they super?

**Comment by ai** [comment]
```
last 2 versions
not IE 10
not dead
```

I added `not dead` because I think MDN ignores old browsers without security updates (like Blackberry).

**Comment by Richienb** [comment]
Is it possible to express that in a single line, such that it would be possible to enter it in [browserl.ist](https://browserl.ist/)

**Comment by ai** [comment]
Sure. `last 2 versions, not IE 10, not IE_Mob 10, not dead`

**Comment by Richienb** [comment]
Thanks!
