### ISSUE TITLE
Combining `not` with Language Code leads to Wrong Results

### ISSUE THREAD

**Issue by fabb** [browserslist/browserslist#320]
For example `last 1 baidu version, not <2% in AT` still returns `Baidu Browser 7.12` Even though it has 0% usage in AT. When I leave away the country code, it works as expected.

https://browserl.ist/?q=last+1+baidu+version%2C+not+%3C2%25+in+AT

https://browserl.ist/?q=last+1+baidu+version%2C+not+%3C2%25

**Comment by ai** [comment]
Open issue in `browserl.ist` to update Browserslist (it is not official package). This issue could be already fixed (I fixed similar issue recently).

**Comment by fabb** [comment]
Thanks! I wasn‘t aware that it is a separate project. Filed an issue there: https://github.com/jonrohan/browserl.ist/issues/108

**Comment by fabb** [comment]
Ah ok, then maybe 449bf6?
https://github.com/browserslist/browserslist/commit/449bf6c9d5a08e9a6f9e56ee11582e18b07eb099

**Comment by ai** [comment]
Exactly 😄 you are good in finding commits

**Comment by fabb** [comment]
Nah, you said you fixed it recently, and browserl.ist uses browserslist 4.2.1, and according to the releases of this repo there have only been 4 releases since then, so I looked through the release notes in CHANGELOG.md that you updated in each release tagged commit, and found out that you probably meant release 4.3.1, as the changelog of the other releases looked unrelated. Then I looked at the commit history (since Github didn‘t allow me to compare changes between the tags 4.3.1 and 4.3), and found that only one commit was in the release, so that must be it. Easy thanks to CHANGELOG.md 🙃

**Comment by fabb** [comment]
I tried it with version 4.3.4, the bug is NOT yet fixed.

**Comment by ai** [comment]
OK, I will try to fix it on this week day

**Comment by ai** [comment]
Fixed 0119a36

**Comment by ai** [comment]
Released in 4.3.5.

**Comment by fabb** [comment]
Awesome, thank you 🙏
