### ISSUE TITLE
Unclear sentence in readme

### ISSUE THREAD

**Issue by HerrBertling** [browserslist/browserslist#321]
In the "best practices", the readme says:

> If you want to change the default set of browsers we recommend to combine last 1 version, not dead with > 0.2% (or > 1% in US, > 1% in my stats). last n versions adds too many dead browsers and does not add popular old versions. > 0.2% make popular browsers even more popular, so we will have a monopoly and stagnation, as we had with Internet Explorer 6.

I don't quite get the last sentence. Does it mean "Choosing a percentage above 0,2% could make popular browsers even more popular,…"? It could also mean "Using `0,2%` makes…" which I guess is not the intention here, right?

If that sentence should be a hint to support a more diverse browser landscape, I'd phrase it a bit differently:

> If you want to change the default set of browsers we recommend to combine `last 1 version`, `not dead` with `> 0.2%` (or `> 1% in US`, `> 1% in my stats`). `last n versions` adds too many dead browsers and does not add popular old versions. Choosing a percentage above `0.2%` will in the long run make popular browsers even more popular. We might run into a monopoly and stagnation situation, as we had with Internet Explorer 6. Please use this setting with caution.

Does that make sense? Happy to provide a PR :)

**Comment by ai** [comment]
I like new text. Please send PR to save your name in project history.
