### ISSUE TITLE
BrowserslistError: Unknown browser query `dead`

### ISSUE THREAD

**Issue by cikichen** [browserslist/browserslist#323]
```
/xxx/node_modules/postcss-cssnext/node_modules/browserslist/index.js:164
    throw new BrowserslistError('Unknown browser query `' + selection + '`')
    ^
BrowserslistError: Unknown browser query `dead`
    at /xxx/node_modules/postcss-cssnext/node_modules/browserslist/index.js:164:11
    at Array.reduce (<anonymous>)
    at resolve (/xxx/node_modules/postcss-cssnext/node_modules/browserslist/index.js:132:18)
    at browserslist (/xxx/node_modules/postcss-cssnext/node_modules/browserslist/index.js:224:16)
    at cleanBrowsersList (/xxx/node_modules/postcss-cssnext/node_modules/caniuse-api/dist/utils.js:56:59)
    at setBrowserScope (/xxx/node_modules/postcss-cssnext/node_modules/caniuse-api/dist/index.js:26:43)
    at Object.<anonymous> (/xxx/node_modules/postcss-cssnext/node_modules/caniuse-api/dist/index.js:88:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
```

env

```
    "chalk": "2.4.1",
    "css-loader": "1.0.0",
    "cssnano": "^4.1.7",
    "dotenv": "6.0.0",
    "dotenv-expand": "4.2.0",
"postcss-aspect-ratio-mini": "0.0.2",
    "postcss-cssnext": "^3.1.0",
    "postcss-flexbugs-fixes": "4.1.0",
    "postcss-loader": "3.0.0",
    "postcss-preset-env": "6.0.6",
    "postcss-px-to-viewport": "0.0.3",
    "postcss-safe-parser": "4.0.1",
    "postcss-viewport-units": "^0.1.6",
    "postcss-write-svg": "^3.0.1",

  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
```

**Comment by aurelijusrozenas** [comment]
Not sure this is the place (maybe webpack bug).
I have similar config (with `not dead` option): `npx browserslist` works fine, bet weback throws
> ```
> BrowserslistError: Unknown browser query `dead`
> ```
Config:
```
"browserslist": [
    "defaults",
    "not dead"
]
```
Tried to clear node_modules - did not help.

**Comment by cikichen** [comment]
> Not sure this is the place (maybe webpack bug).
> I have similar config (with `not dead` option): `npx browserslist` works fine, bet weback throws
> 
> > ```
> > BrowserslistError: Unknown browser query `dead`
> > ```
> 
> Config:
> 
> ```
> "browserslist": [
>     "defaults",
>     "not dead"
> ]
> ```
> Tried to clear node_modules - did not help.

'postcss-cssnext' has been deprecated，may be this reason?

**Comment by ai** [comment]
> BrowserslistError: Unknown browser query `dead`

This error happens because of old Browserslist in your build pipeline.

Check `npm ls` for Browserslist < 4 and update dependency which load it.

> 'postcss-cssnext' has been deprecated，may be this reason?

Yeap, it could be a reason

**Comment by rishabhnigamoyo** [comment]
Here I have  a quick fix. 
` "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": []
  }`
Delete items inside the development array inside browser list.

**Comment by DevGemmy** [comment]
@ rishabhnigamoyo please this quick fix you have suggested, in which file should it be, for an angular project.

**Comment by DevGemmy** [comment]
@rishabhnigamoyo please this quick fix you have suggested, in which file should it be, for an angular project.

**Comment by Cyberfolks** [comment]
this one worked for me.
thanks @rishabhnigamoyo 
"browserslist": { "production": [ ">0.2%", "not dead", "not op_mini all" ], "development": [] }
