### ISSUE TITLE
Usage Query in Country Code returns Browsers Below the Threshold 

### ISSUE THREAD

**Issue by fabb** [browserslist/browserslist#324]
Sorry to bother you again, but I‘ve got one more bug with language codes. In a query like `>0.1% in AT` some browsers are returned that are below the threshold:

https://browserl.ist/?q=%3E0.1%25+in+AT

```
Firefox for Android 63 0.09%
Samsung Internet 6.2 0.01%
Samsung Internet 4 0.03%
Chrome 57 0.03%
Edge 15 0.03%
Firefox 61 0.07%
Firefox 60 0.08%
Opera 56 0%
Opera 55 0.06%
```

**Comment by ai** [comment]
I think it is https://browserl.ist issue (sorry, it is non-official project, you should open issue in their repo). It shows global statistics for each browser.

Here are my local results (with latest Can I Use):

```js
browserslist('>0.1% in AT').map(i => [i, browserslist.coverage([i], 'AT')])
[ [ 'and_chr 70', 33.545416 ],
  [ 'and_ff 63', 0.35188 ],
  [ 'android 4.4.3-4.4.4', 0.40662127659574 ],
  [ 'android 4.2-4.3', 0.18162417021277 ],
  [ 'android 4', 0.12017917730496 ],
  [ 'chrome 70', 2.323224 ],
  [ 'chrome 69', 12.7494 ],
  [ 'chrome 68', 0.333688 ],
  [ 'chrome 67', 0.169992 ],
  [ 'chrome 63', 0.113328 ],
  [ 'chrome 57', 0.264432 ],
  [ 'chrome 49', 0.214064 ],
  [ 'edge 17', 2.26656 ],
  [ 'edge 16', 0.232952 ],
  [ 'edge 15', 0.12592 ],
  [ 'firefox 63', 1.171056 ],
  [ 'firefox 62', 5.339008 ],
  [ 'firefox 61', 0.182584 ],
  [ 'firefox 60', 0.554048 ],
  [ 'firefox 52', 0.56664 ],
  [ 'ie 11', 3.8151357710652 ],
  [ 'ios_saf 12', 11.265784391896 ],
  [ 'ios_saf 11.3-11.4', 5.745743499244 ],
  [ 'ios_saf 11.0-11.2', 1.7131902614656 ],
  [ 'ios_saf 10.3', 0.82542667553674 ],
  [ 'ios_saf 10.0-10.2', 0.77168795968148 ],
  [ 'ios_saf 9.3', 0.44710611591573 ],
  [ 'ios_saf 8.1-8.4', 0.13757111258946 ],
  [ 'ios_saf 8', 0.26009538473944 ],
  [ 'op_mini all', 0.1578018556701 ],
  [ 'opera 56', 0.642192 ],
  [ 'opera 55', 0.22036 ],
  [ 'safari 12', 1.725104 ],
  [ 'safari 11.1', 0.736632 ],
  [ 'safari 11', 0.182584 ],
  [ 'safari 10.1', 0.258136 ],
  [ 'safari 9.1', 0.151104 ],
  [ 'samsung 6.2', 0.12654073469388 ],
  [ 'samsung 4', 0.49561787755102 ] ]
```

**Comment by fabb** [comment]
Ah ok, good hint! I thought the individual browser stats were also AT since the website already shows the global stats at AT when the query contains that.
Thanks for clearing that up!

**Comment by ai** [comment]
> Maybe we rather should generate our own browserslist-stats.json.

+1. It is always better. I recommend https://github.com/browserslist/browserslist-ga to do it

**Comment by fabb** [comment]
Yeah I‘ve seen it, but we‘re not using Google Analytics, we use Xiti. But it‘s just data transformation, shouldn‘t be too hard (famous last words).

**Comment by fabb** [comment]
The question is if I want to implement the „log in and fetch data“ part, or if I just manually export csv and only implement the data transpormation 😉
