### ISSUE TITLE
BrowserslistError: Unknown Browser Query `Electron`.

### ISSUE THREAD

**Issue by mutech** [browserslist/browserslist#326]
This is happening via @babel/preset-env, using the command line and also at https://browserl.ist/?q=electron

```
$ npx browserslist "electron"
browserslist: Unknown browser query `electron`. Maybe you are using old Browserslist or made typo in query.
$ npx browserslist "electron 1"
browserslist: Unknown version 1 of electron
$ npx browserslist --version
browserslist 4.3.4
```

Strangely, running npm test in browserslist succeeds.

**Comment by ai** [comment]
Use `last 1 electron version`.

The core idea of Browserslist is to always specify exact target browsers. This is why just `electron` do not work. Browserslist expect exact version.

There was no Electron 1. This is why second query do not work.

**Comment by mutech** [comment]
Well I choose a wrong example, how about these:

```
$ npx browserslist chrome
browserslist: Specify versions in Browserslist query for browser chrome
$ npx browserslist electron
browserslist: Unknown browser query `electron`. Maybe you are using old Browserslist or made typo in query.
```

browserslist recognizes Chrome (and all other browsers I tried), but not electron.

What version of Electron is valid?

```
$ npx browserslist electron 0.1
browserslist: Unknown browser query `0.1`. Maybe you are using old Browserslist or made typo in query.
$ npx browserslist electron 2
browserslist: Unknown browser query `2`. Maybe you are using old Browserslist or made typo in query.
$ npx browserslist electron 3
browserslist: Unknown browser query `3`. Maybe you are using old Browserslist or made typo in query.
$ npx browserslist electron 3.0.9
browserslist: Unknown browser query `3.0.9`. Maybe you are using old Browserslist or made typo in query.
```

**Comment by ai** [comment]
> browserslist recognizes Chrome (and all other browsers I tried), but not electron.

Browserslist recognize it, but just don't have fancy warning. Do you want to send PR with this warning for Electron?

> `npx browserslist electron 3.0.9`

You forgot quotes

**Comment by mutech** [comment]
You have a point, of course, but the problem still remains. No electron versions are found even with the quotes (see the initial example).

Here with quotes:
```
$ npx browserslist "electron 3.0.10"
browserslist: Unknown version 3.0.10 of electron
$ npx browserslist "electron 3.0.9"
browserslist: Unknown version 3.0.9 of electron
$ npx browserslist "electron 2"
browserslist: Unknown version 2 of electron
```

Btw. instead of using electron-to-chrome, electron-releases (see link above) seems to be the better choice as it also provides a mapping for the node dependency and it's maintained by the electron guys.

It would be great if
* `electron x` would resolve to `chrome y, node z`,
* `electron-renderer x` to `chrome y` and
* `electron-main x` to `node z`.

or if that could break existing code to add
* `electron-main x`

If that sounds good, I'd look into it.

**Comment by ai** [comment]
> browserslist: Unknown version 3.0.10 of electron

Strange, we have tests for this query:
https://github.com/browserslist/browserslist/blob/master/test/electron.test.js

Does https://www.npmjs.com/package/electron-to-chromium have this version?

> electron x would resolve to chrome y, node z

Good idea. I forgot about `electron X` queries, when I added `node` support.

Do we have this data in https://www.npmjs.com/package/electron-to-chromium ?

> electron-renderer x to chrome y and electron-main x to node z.

Do you really have use case for this queries (I started to worry about maintability and do not accept theoretical queries anymore).

**Comment by mutech** [comment]
No, node versions are not in electron-to-chromiun, but they are in electron-releases.

Maintainability would benefit from this, since electron-releases is part of the electron project and contains info for all versions (everything they publish to github).

The use case: I use per directory browserslist files to configure platform dependencies for babel and other tools. Code is shared between electron, browser FE, node modules etc. The electron aliases can always be replaced with their chrome/node counterparts, but it's of course more elegant and less error prone to just use the correct electron version instead of looking up the effective chrome version.

Queries like "project electron-main version" would completely remove the need to keep browserslist files up to date with package.json. I would second the proposal I saw in another issue regarding node versions. ;-)

**Comment by ai** [comment]
> electron-releases

Did they contain Chrome and Node.js versions?

Did this project is still maintained? I thought they created new project.

**Comment by ai** [comment]
> The use case: I use per directory browserslist files to configure platform dependencies for babel and other tools.

It is use case for `electron x would resolve to chrome y, node z` case. Why do you need to track  Electron’s Node.js and Chrome versions separately?

**Comment by mutech** [comment]
electron-releases: https://www.npmjs.com/package/electron-releases (laster update a day ago, so yes, it's maintained).

Use case: Assuming this directory structure:

* electron
   * main
   * renderer
   * shared

Code in shared has to run on both node and chrome, code in main and renderer on one of these. Babel and associated tools can optimize for chrome and node in main and renderer folders.

I am short of a concrete example where transpiling code for node and running it in chrome or vice versa would fail in an electron context, but I'm sure there are plenty.

**Comment by ai** [comment]
> electron-releases: https://www.npmjs.com/package/electron-releases (laster update a day ago, so yes, it's maintained).

Great. Please send PR with using it and with using Node and Chrome in Electron query.

> Code in shared has to run on both node and chrome, code in main and renderer on one of these. 

I am not very familiar with Electron. What it has different JS for renderer and main? That is main in this case?

**Comment by mutech** [comment]
> I am not very familiar with Electron. What it has different JS for renderer and main? That is main in this case?

They both run on the same version of V8, so on the language level there should be no differences. AFAIK, the only difference is the availability of API's and probably various defaults. I'm not an expert on this either, that's why I am so happy that browserslist exists ;-)

**Comment by ai** [comment]
I know a way to select only Electron’s Node: `electron 3, not Chrome > 0`

**Comment by mutech** [comment]
That is assuming that this ticket does not exist and "electron 3" would work, right?

*smirk*

**Comment by mutech** [comment]
To summarize, I invaded three topics in this issue:

* "electron 3" not working
   * that's open, could you reproduce this? The test is running for me too, but the query on the command line not (neither from babel).
* replace electron-to-chromium with electron-release
   * benefit: owned by electron, additional info (especially node version), impact on code: dunno
* additional electron queries
   * risk/benefit unclear, I leave that up to you. If you're interested let me know and I'll implement it.
* additional electron query using package.json dependency
   * I would love this. Would need to lookup the dev-dependency in package.json and use it, should be easy. Can do if you like it.

**Comment by ai** [comment]
Also `add node X to Electron query output`

**Comment by ai** [comment]
> that's open, could you reproduce this? The test is running for me too, but the query on the command line not (neither from babel).

I will be able to try to reproduce it only on this weekend

**Comment by mutech** [comment]
Ok, fine. I'll take a look at stuff and we'll have another chat weekends?

**Comment by ai** [comment]
👍

I had convinced for:

1. replace electron-to-chromium with electron-release
2. add node X to Electron query output

I do not know what do you mean for “additional electron query using package.json dependency”?

**Comment by mutech** [comment]
About all electron packages will have a dev dependency to electron in package.json. A query like:

given a package.json containing:
```
"devDependencies": { ...
     "electron": "^3.0.10",
     ...
}
```

a browserslist query like
```
project electron version
```

could resolve to `electron 3.0.10`.

I stumbled over another issue suggesting to determine the node version from the engine declaration with a similar intention. Unlike that, this dependency to electron is pretty much certainly the right version to use.

**Comment by mutech** [comment]
Done

**Comment by mutech** [comment]
Part of the problem I had is that the current implementation of electron queries require exact matches of the version provided by electron-2-chromium, f.e. `electron 3.0` works, `3.0.9` or `3` does not.

The PR I send earlier today also fixes this issue. So if that is ok, this issue can also be closed.
