### ISSUE TITLE
Feature request: Queries referencing project settings (package.json)

### ISSUE THREAD

**Issue by mutech** [browserslist/browserslist#327]
For some platforms, the version can be determined from project settings found in package.json.

If package.json specifies a `node.engines` field or has a dev dependency to electron, specified versions could be referenced by a new query type

```
project node version
```

or 

```
project electron version
```

EDIT: Also, it would be convenient to be able to specifiy

```
project browserslist
```

in a `.browserslistrc` or `browserlist` file to restore the defaults in a directory hierarchy:

```
* package.json[browserslist: "default settings"]
* src/x
   * browserslist: "overwrite settings"
   * subdir
      * browserslist: "project browserslist" <- restoring the defaults from package.json
```

**Comment by mutech** [comment]
See #319

**Comment by mutech** [comment]
See #326

**Comment by ai** [comment]
I am closing since there is no implementation and I will no do it without PR (sorry, just want to keep Browserslist out of rare used queries)
