### ISSUE TITLE
Bug: Custom Usage Data querying is incorrect

### ISSUE THREAD

**Issue by ArgonAlex** [browserslist/browserslist#333]
[This](https://github.com/browserslist/browserslist/blob/master/node.js#L159) normalization is causing [these](https://github.com/browserslist/browserslist/blob/master/index.js#L524) conditions to always be false. Which means any browsers that are "normalized" are always excluded from the results.

Unfortunately the test didn't catch this because it's only checking that and_chr is excluded with `not and_chr > 0`, which it always is regardless of the query.

**Comment by ai** [comment]
Hi. Sorry, I had too many flights recently and now it is hard for me to understand complex issues.

Can you send PR with new test (and maybe a solution)?

**Comment by ai** [comment]
I checked coffee and still do not understand the problem (normalization is too complex).

@ArgonAlex can you show query affected by this issue?

**Comment by ArgonAlex** [comment]
:( I hope you recover soon!

Sorry I haven't had much time to look into a solution. I'm not really sure why the normalization needs to happen. But I just added a test to reproduce the issue, and another issue too.

**Comment by ai** [comment]
Fixed b71984f
