### ISSUE TITLE
Regex to match Browserlist query

### ISSUE THREAD

**Issue by Richienb** [browserslist/browserslist#334]
I'm just wondering if there is a regex I can use to test if a Browserlist query is valid. If not, is there any other way to programmatically check?

**Comment by ai** [comment]
Tell me use case your case. I can add `browserslist.check(query)`.

**Comment by Richienb** [comment]
I'm trying to check this via Javascript.

**Comment by ai** [comment]
> I'm trying to check this via Javascript.

It is not use case. Use case should be end-user centric.

Why do you need to check it? What is your application doing? Why somebody may enter wrong Browserslist query?

**Comment by ai** [comment]
1. What does your system do?
2. Who enter this Browserslist queries?
3. Why this queries could be not valid?
4. What do you do if queries are not valid? Why you can’t just show a standard Browserslist error message?

**Comment by Richienb** [comment]
> What do you do if queries are not valid? Why you can’t just show a standard Browserslist error message?

How do I trigger a Browserlist validation in the way you described?

**Comment by ai** [comment]
You do not need to trigger it. Each time Autoprefixer or Babel runs, it uses Browserslist, Browserslist throw a error on unknown or wrong query.
