### ISSUE TITLE
browserslist does not register and_ff correctly

### ISSUE THREAD

**Issue by isabellachen** [browserslist/browserslist#336]
I am trying to get an array of browsers using browserslist. The conversion for all other browsers seems to be working fine except for "and_ff". Browserslist gives me "and_ff 63" no matter what version of and_ff I give it. "last 2 and_ff versions" gives me "and_ff 63" also. Is there some reason for this?

The results can be seen here in[ this codesandbox](https://codesandbox.io/s/0o85opo1yp).

**Comment by ai** [comment]
@isabellachen unfortunately, this what Can I Use has in their database 😓. They have the only latest version for every mobile browser. https://i.imgur.com/tmRet0u.png

I do not like it too, but I can affect to Can I Use.
