### ISSUE TITLE
Unexpected result for: defaults, not < 1% in DE

### ISSUE THREAD

**Issue by gharlan** [browserslist/browserslist#340]
[`> 1% in DE`](https://browserl.ist/?q=%3E+1%25+in+DE) lists "Safari 12"
[`defaults`](https://browserl.ist/?q=defaults) also lists "Safari 12"
So why is Safari 12 missing with [`defaults, not < 1% in DE`](https://browserl.ist/?q=defaults%2C+not+%3C+1%25+in+DE)?

Shouldn't be `not < 1% in DE` the same as `> 1% in DE`?

**Comment by ai** [comment]
Hi. Sorry, I will discover it after New Year (it is a very important holiday in Russia).

Right now you can:

1. Check that you use the latest version of Browserslist. https://browserl.ist/ is not official and not latest.
2. Debug [this block](https://github.com/browserslist/browserslist/blob/master/index.js#L135-L189). Don’t worry. Browserslist is 2 files libraries with simple pure JS code.

**Comment by ai** [comment]
Fixed 21c25e2c0751107d45f4dc768fecad6d870f4913

**Comment by gharlan** [comment]
Thanks for the very fast fix! 👏
