### ISSUE TITLE
Support for Edge mobile?

### ISSUE THREAD

**Issue by saschanaz** [browserslist/browserslist#341]
Currently there is Edge and IE Mobile but no Edge mobile (for Windows 10 Mobile). It's dead in feature-wise and also dying in security-wise, but should exist so that tools including `@babel/preset-env` can still support it.

**Comment by ai** [comment]
We just use Can I Use database. Ask them to add Edge Mobile and it will be in Browserslist. https://github.com/Fyrd/caniuse

**Comment by saschanaz** [comment]
Related issue: https://github.com/Fyrd/caniuse/issues/2119
