### ISSUE TITLE
Query ">1%" shows Chrome 69 with 0.38%

### ISSUE THREAD

**Issue by KevinBrogan** [browserslist/browserslist#344]
https://browserl.ist/?q=%3E1%25

**Comment by ai** [comment]
browserl.ist is unofficial and often has outdated data.

Use `npx browserslist "> 1%"` instead (and be sure that you have latest `browserslist` and `caniuse-lite` npm package versions (you can check them in `npm ls`).

Also, note that we use Can I Use data and we take their data from npm. Something it takes few days for update.
