### ISSUE TITLE
[Question] Does specifying browsers mean whitelisting?

### ISSUE THREAD

**Issue by comatory** [browserslist/browserslist#348]
If I specify for example `Chrome >= 69, Firefox >= 60` does this mean other browsers get ignored?

**Comment by ai** [comment]
Yes. It will ignore all other browsers (and this is why it is not recommend for standard use cases).

**Comment by comatory** [comment]
Thank you, maybe this behaviour could be implied in the README.

**Comment by ai** [comment]
Sure

**Comment by comatory** [comment]
Opened PR here https://github.com/browserslist/browserslist/pull/349
