### ISSUE TITLE
`node, last 2 years` does not resolve

### ISSUE THREAD

**Issue by tyteen4a03** [browserslist/browserslist#350]
This query fails: `node, last 2 years`

**Comment by ai** [comment]
There is no `node` query. Here is available queries: https://github.com/browserslist/browserslist#full-list

Maybe you need to replace `node` to `maintained node versions` or `current node`

**Comment by tyteen4a03** [comment]
That's rather limiting. Are there plans to make these queries work on node?

**Comment by ai** [comment]
What is your use case? Do you create a library (and want to compile it for your clients?) or do you create an application (and need only one Node.js version)>

What Node.js version do you want to select?

**Comment by tyteen4a03** [comment]
I don't have a strong need for this - just a nice to have. It struck me as odd how node query behaviour is different from regular browsers.

**Comment by ai** [comment]
I think `nvm` queries is not very good since it is not very clear. This is why we used more explicit queries.

What query do you want? Latest version of Node? For what use case?

**Comment by tyteen4a03** [comment]
For me latest LTS version would be good.

**Comment by ai** [comment]
For this case `last 1 node lts` could be better.

I can add it.

What is use case?
