### ISSUE TITLE
When I build react project, the problem hanppened. Module build failed: BrowserslistError: Unknown browser query `dead`     at Array.forEach (<anonymous>)

### ISSUE THREAD

**Issue by shenhui815** [browserslist/browserslist#353]
Creating an optimized production build...
Failed to compile.

./src/styles/main.less
Module build failed: BrowserslistError: Unknown browser query `dead`
    at Array.forEach (<anonymous>)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! KnowledgeBase@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the KnowledgeBase@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     AppData\Roaming\npm-cache\_logs\2019-03-05T04_09_17_341Z-debug.log

**Comment by ai** [comment]
You have some dependency which uses very old Browserslist.

1. try to call `npm update` to update dependencies.
2. Call `npm ls`, find who use Browserslist < 3.0. Update it or open issue there.

**Comment by Soumava-221B** [comment]
Creating an optimized production build...
Failed to compile.

./src/App.css
Module build failed: BrowserslistError: Unknown browser query `dead`
    at Array.forEach (<anonymous>)

I tried the above method but it didn't work
