### ISSUE TITLE
False-positives

### ISSUE THREAD

**Issue by EvgenyOrekhov** [browserslist/browserslist#355]
I believe these are false-positives:

> document.getElementsByTagName() is not supported in Safari 11.1, Opera 57, Edge 17
> document.documentElement() is not supported in Safari 11.1, Opera 57, Edge 17
> window.history() is not supported in Safari 11.1, Opera 57, Edge 17

browserslist version: 4.4.2

Moved here from https://github.com/amilajack/eslint-plugin-compat/issues/186.

**Comment by ai** [comment]
> The versions are generated by browsers list but the compat records are from ast-metadata-inferer and mdn-browser-compat-data. This is an issue with this project.
