### ISSUE TITLE
Idea: "<browser> >= last supported on <platform>

### ISSUE THREAD

**Issue by jrencz** [browserslist/browserslist#359]
It's now super-manual to express a policy related to last supported versions on platforms. One has to know what were those versions if they want to have them covered. E.g.: support at least the last version of evergreen browsers available on Windows XP. 

This means:
- Chrome >= 49 (last for windows XP, Vista, Max OS 10.6-10.8)
- Opera >= 36 (it uses Chromium 49 so same reason)
- Firefox >= 52 (last for Windows XP, Vista and all 32-bit Mac OS)

But I have to have this written down explicitly and well commented because otherwise it's like "WTF, why '36'?" - especially for someone not "into it" for whom those numbers doesn't mean much.

I think it would be better to have it written down like:

- _chrome_ >= **last supported on** _windows_xp_
- _opera_ >= **last supported on** _windows_xp_
- _firefox_ >= **last supported on** _windows_xp_

I suggest there should be syntax for that. Not necessarily the one I suggested above
This also means there should be a list of last versions by platform maintained (I didn't yet try to find such list already there, maybe there's one)

**Comment by ai** [comment]
Do you know any good resource with this data?

**Comment by ai** [comment]
I think, the sharable config will be the best thing for this case

https://github.com/browserslist/browserslist#shareable-configs

```
extends browserslist-config-winxp/chrome
```

**Comment by jrencz** [comment]
> Do you know any good resource with this data?

I searched release logs and it's often written in there. Valuable but not possible to automate

> I think, the sharable config will be the best thing for this case
>
> https://github.com/browserslist/browserslist#shareable-configs
>
> ```
> extends browserslist-config-winxp/chrome
> ```

I'm worried about discoverability of this - it will have to be well listed right in the core project documentation to make it usable for the end user.
And the number of combinations: one will want to support xp, one will want to support vista, other will focus on mac OS.

**Comment by ai** [comment]
> Valuable but not possible to automate

This is why I am afraid to add it to the core.

> And the number of combinations: one will want to support xp, one will want to support vista, other will focus on mac OS.

```
extends browserslist-config-os/xp/chrome
```

You can use a script to generates there sharable config by one JSON data.

**Comment by ai** [comment]
I am closing this issue, since at least right now I do not want to add it to the core.
