### ISSUE TITLE
Parsing bug if newer minor version appears before major version

### ISSUE THREAD

**Issue by spiltcoffee** [browserslist/browserslist#360]
**What happened?**
- I tried passing a query through browserlist where a newer minor version appeared before the same browser's major version (i.e. `safari 12.2` appeared before `safari 12`).

**What did I expect?**
- Everything to work fine

**What actually happened?**
- It seems like the major version gets removed twice during parsing the query string, so you end up with the minor version attaching to the next part of the string.
- As a result, I got an error that didn't make sense: `unknown version 11.2 of ie` (_but I never asked for... okay what?_)
- I think this line in particular is the culprit: https://github.com/browserslist/browserslist/blob/442e51f911f2f98ffe0926bd2e349a860d5fdcee/index.js#L389

**Reproduction:**
- https://browsersl.ist/?q=chrome+70%2C+ie+11%2C+safari+12.2%2C+safari+12

**Comment by ai** [comment]
Fixed b1de7aa

Thanks for issue with all details

**Comment by ai** [comment]
Released in 4.5.3
