### ISSUE TITLE
Specify default

### ISSUE THREAD

**Issue by ThomasdenH** [browserslist/browserslist#366]
Reading through the history of the Readme, it seems it is recommended to use the browserlist default when creating a general usage website. However, it is also recommended to specify a config in `package.json` instead of relying on the fallback. Is there a default config to extend here?

**Comment by ai** [comment]
> Is there a default config to extend here?

```js
"browserslist": [
  "defaults"
]
```

**Comment by ai** [comment]
Should we clarify it in docs? Do you want to send PR?
