### ISSUE TITLE
Node must be lower case despite docs

### ISSUE THREAD

**Issue by brettz9** [browserslist/browserslist#369]
Per https://www.npmjs.com/package/browserslist, "Names are case insensitive" and "`Node` for Node.js.", but using `4.5.5`, "Node" does not work with comparators (#293) unless made all lower-case (and it doesn't work at all, including lower case, if there is no version, but I suppose that is expected).

**Comment by ai** [comment]
Do you want to send PR to save your name in history? Just add `i` regexp modifier and tests.

**Comment by ai** [comment]
Fixed 9f1752e

**Comment by ai** [comment]
Released in 4.5.6.

**Comment by brettz9** [comment]
Thanks much！
