### ISSUE TITLE
Error build

### ISSUE THREAD

**Issue by artel1992** [browserslist/browserslist#370]
after I added the scripts in the package.json ... I started to get the error "This is probably additional logging output above." during assembly...
    "build:css": "postcss src/app.css -o build/app.css",
    "build:js": "babel src/app.js -o dist/app.js",
    "build": "npm run build:css && npm run build:js"
What have I done wrong? Can you help me with this?

**Comment by ai** [comment]
@artel1992 show me full output

**Comment by artel1992** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--scripts-prepend-node-path=auto' ]
2 info using npm@6.8.0
3 info using node@v10.15.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle scores-vue@1.0.0~prebuild: scores-vue@1.0.0
6 info lifecycle scores-vue@1.0.0~build: scores-vue@1.0.0
7 verbose lifecycle scores-vue@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle scores-vue@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\test_projects\mrs25\scores-vue\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files (x86)\Brackets\command;C:\Program Files\Git\cmd;C:\Program Files (x86)\PuTTY\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\Users\Art\AppData\Local\Programs\Python\Python35\Scripts\;C:\Users\Art\AppData\Local\Programs\Python\Python35\;C:\Program Files\JetBrains\PyCharm 2018.3.2\bin;C:\Users\Art\AppData\Roaming\npm;C:\Program Files\PostgreSQL\9.6\bin
9 verbose lifecycle scores-vue@1.0.0~build: CWD: D:\test_projects\mrs25\scores-vue
10 silly lifecycle scores-vue@1.0.0~build: Args: [ '/d /s /c', 'npm run build:css && npm run build:js' ]
11 silly lifecycle scores-vue@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle scores-vue@1.0.0~build: Failed to exec build script
13 verbose stack Error: scores-vue@1.0.0 build: `npm run build:css && npm run build:js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid scores-vue@1.0.0
15 verbose cwd D:\test_projects\mrs25\scores-vue
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build" "--scripts-prepend-node-path=auto"
18 verbose node v10.15.2
19 verbose npm  v6.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error scores-vue@1.0.0 build: `npm run build:css && npm run build:js`
22 error Exit status 1
23 error Failed at the scores-vue@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
I think I did not correctly pointed the path

**Comment by artel1992** [comment]
in the script you need to specify the path to the js file right?and how to be with vue components? I have a project and I am trying to build it with support for multiple browsers.

**Comment by artel1992** [comment]
> @artel1992 show me full output

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli 'run',
1 verbose cli 'build',
1 verbose cli '--scripts-prepend-node-path=auto' ]
2 info using npm@6.8.0
3 info using node@v10.15.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle scores-vue@1.0.0prebuild: scores-vue@1.0.0
6 info lifecycle scores-vue@1.0.0build: scores-vue@1.0.0
7 verbose lifecycle scores-vue@1.0.0build: unsafe-perm in lifecycle true
8 verbose lifecycle scores-vue@1.0.0build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\test_projects\mrs25\scores-vue\node_modules.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files (x86)\Brackets\command;C:\Program Files\Git\cmd;C:\Program Files (x86)\PuTTY;C:\Program Files\dotnet;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\nodejs;C:\Users\Art\AppData\Local\Programs\Python\Python35\Scripts;C:\Users\Art\AppData\Local\Programs\Python\Python35;C:\Program Files\JetBrains\PyCharm 2018.3.2\bin;C:\Users\Art\AppData\Roaming\npm;C:\Program Files\PostgreSQL\9.6\bin
9 verbose lifecycle scores-vue@1.0.0build: CWD: D:\test_projects\mrs25\scores-vue
10 silly lifecycle scores-vue@1.0.0build: Args: [ '/d /s /c', 'npm run build:css && npm run build:js' ]
11 silly lifecycle scores-vue@1.0.0build: Returned: code: 1 signal: null
12 info lifecycle scores-vue@1.0.0build: Failed to exec build script
13 verbose stack Error: scores-vue@1.0.0 build: npm run build:css && npm run build:js
13 verbose stack Exit status 1
13 verbose stack at EventEmitter. (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack at EventEmitter.emit (events.js:189:13)
13 verbose stack at ChildProcess. (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack at ChildProcess.emit (events.js:189:13)
13 verbose stack at maybeClose (internal/child_process.js:970:16)
13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid scores-vue@1.0.0
15 verbose cwd D:\test_projects\mrs25\scores-vue
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "build" "--scripts-prepend-node-path=auto"
18 verbose node v10.15.2
19 verbose npm v6.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error scores-vue@1.0.0 build: npm run build:css && npm run build:js
22 error Exit status 1
23 error Failed at the scores-vue@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
I think I did not correctly pointed the path..and how to be with vue components? I have a Vue project, and I am trying to build it with support for multiple browsers.

**Comment by ai** [comment]
Sorry, I can’t help you with Vue (I have no real experience with it). StackOverflow will be a better choice.

I am closing this issue because if it not related to Browserslist code or docs.

**Comment by artel1992** [comment]
I understood you. Thank you for responding so quickly. Total you best
