### ISSUE TITLE
Depending on caniuse-lite v1.0.30000967

### ISSUE THREAD

**Issue by fALKENdk** [browserslist/browserslist#372]
The latest release is depending on caniuse-lite v1.0.30000967 but the latest release is v1.0.30000966

**Comment by ai** [comment]
Are you sure that 966 is latest? https://www.npmjs.com/package/caniuse-lite show 967.

Maybe you have some npm HTTP error? (They often have them (

**Comment by fALKENdk** [comment]
Your right sorry, just tried to install caniuse-lite in another project and I get 967 aswell.
Just got this error message:
Borwserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browerslist`
and after a look on https://github.com/ben-eb/caniuse-lite/releases it looked like 966 was the latest release.
