### ISSUE TITLE
"last 2 versions" once edge goes chromium

### ISSUE THREAD

**Issue by jonathantneal** [browserslist/browserslist#373]
In the near future, would a query like `last 2 edge versions` translate to `edge 18, edge 74`?

The way it will work in browserslist would likely have a huge impact on the transition period between **EdgeHTML Edge** (18-) and **Chromium Edge** (74+).

_Note: It will be much more common for this query to come down in the form of `last 2 versions`. The specific example of `last 2 edge versions` was only used to focus the question._

**Comment by ai** [comment]
What is Microsoft policy about the transition period between EdgeHTML and Chromium Edge? Will they keep supporting both branches for a while?

**Comment by mgol** [comment]
@ai have you gotten a response about that from MS? I know @TheLarkInn reached out to you on that topic some time ago.

**Comment by ai** [comment]
No response yet

**Comment by molant** [comment]
Hello all,

EdgeHTML will receive security updates but no features will be added to it so there won't be a major release of it.

One thing to take into account is that once Chromium Edge has a stable channel, it will be updated every 6 weeks. While `last 2 edge versions` might return something similar to what @jonathantneal says in the description, it won't be for long.
That said, users might want to support the latest(s) versions of EdgeHTML as well (especially for enterprise scenarios where they move a bit slower). Maybe EdgeHTML should be considered something like Firefox ESR?

If you have any particular question let me know and I'll find the right people if I can't answer it.

**Comment by jonathantneal** [comment]
Thanks for the update, @molant! Would you mind confirming the last version of EdgeHTML Edge? I believe it is `18`, but [whatismybrowser.com stats](https://developers.whatismybrowser.com/useragents/explore/software_name/edge/?order_by=-software_version) suggests `19`.

_Aside: Ah, I’m so excited to ship support for Chromium Edge to normalize.css and sanitize.css, which is then used by PostCSS Normalize, which is then used by Create React App!_

PR at https://github.com/csstools/normalize.css/pull/9 😄

**Comment by molant** [comment]
The version I have in my laptop is 18.18362 and it has the latest Windows 10 release from this week.
I'm going to double check internally to make sure we are not bumping the version in the next Windows 10 release just to make sure.

**Comment by ai** [comment]
Let’s wait for some final release and how Can I Use will count Edge versions.

How I see Edge policy for now:

1. If Can I Use will have only the latest Edge version (`17, 18, 80`) we will use `android` behavior https://github.com/browserslist/browserslist/issues/374. `last 2 versions` will return only `edge 80`
2. If EdgeHTML will be popular (>0.1%) I will keep `edge 18` in `defaults`. If somebody will give me a really important use case, I can keep EdgeHTML in `defaults` even with fewer statistics.

**Comment by ai** [comment]
We used new evergreen policy for `android` https://github.com/browserslist/browserslist/issues/374

So we will use it for Edge if Can I Use data will be inconsistent.

**Comment by jonathantneal** [comment]
> As of today, we are now referring to the old version of Microsoft Edge as "Microsoft Edge Legacy.”
>
> The Chromium-based version is simply called "Microsoft Edge.”
> — William Devereux, Senior PM, MicrosoftEdge (https://twitter.com/MasterDevwi/status/1191464457697783808)

If it proves necessary, we can add an `edge-legacy` browser so that people can write things like `last 2 edge-legacy`.

**Comment by ai** [comment]
Browserslist uses browser names from Can I Use, we can’t rename it here. We can add only legacy version alias like `edge legacy` = `edge 18`.

**Comment by ai** [comment]
But I think `edge 18` is shorter. We do not need lias for things that do not get new versions.

**Comment by molant** [comment]
A few questions/comments I have now that this is finally public to see what you think:

* I see `edge 18` similar to `firefox esr`, a version that is going to get security updates for a while. Maybe it should be included as part of `defaults` once the new edge ships? We want the new edge to replace the legacy one as fast as possible but it depends in many different factors (enterprise being one that doesn't usually move fast)
* What happens with queries like `last 2` once the new edge ships. Let's imagine the first stable version is 80. Would that return `edge 79` which doesn't exist, and `edge 80`, or would that return `edge 18` and `edge 80`?
   With updates every 6 weeks I'm not super worried about this, but I wanted to see if someone had thought about this or not

**Comment by ai** [comment]
> I see edge 18 similar to firefox esr, a version that is going to get security updates for a while. Maybe it should be included as part of defaults once the new edge ships?

Good idea. I will add it after the first Chromium Edge release (can you ping me if I will miss the release?).

> What happens with queries like last 2 once the new edge ships

I depends on Can I Use. I think they will track only the latest Edge version, so in the future, they will have `edge 81, edge 18` (even if `edge 80` exists). In this case:

Current behavior:

```
last 2 edge versions => edge 80, edge 18
```

After the first Chromium Edge release I will fix it to (we use the same behavior, that we already use for Chrome for Android):

```
last 2 edge versions => edge 80
last 62 edge version => edge 80, edge 18
```

Is it OK?

**Comment by ai** [comment]
> With updates every 6 weeks I'm not super worried about this, but I wanted to see if someone had thought about this or not

Don’t worry, we will be in touch during the release :hugs:. I can make hotfix during the day.

**Comment by mgol** [comment]
> last 2 edge versions => edge 80
> last 62 edge version => edge 80, edge 18

Wouldn't it be better to slightly tweak that logic & assume that Edge 18 comes directly before the first stable Chromium-based release? In pseudo-code the logic would be as follows (let's assume that Edge 82 is the latest version as we execute it):

```
Input:
last n Edge versions

Data:
const LAST_LEGACY_EDGE = 18;
const FIRST_STABLE_CHROMIUM_EDGE = 79;
const LAST_STABLE_EDGE = 82;

Algorithm:
if (n > LAST_STABLE_EDGE - FIRST_STABLE_CHROMIUM_EDGE + 1) {
   n += FIRST_STABLE_CHROMIUM_EDGE - LAST_LEGACY_EDGE - 1;
}

return getAllVersionsLargerOrEqualTo(LAST_STABLE_EDGE - n + 1);
```

That would mean, if Can I Use only shares 82, 18, 17, 16 etc.:
```
last 4 Edge versions -> Edge >=79 -> Edge 82
last 5 Edge versions -> Edge >=18 -> Edge 82, Edge 18
last 6 Edge versions -> Edge >=17 -> Edge 82, Edge 18, Edge 17
...
```

**Comment by ai** [comment]
Yeap, @mgol suggestion is much better. Let’s count Edge versions like: `last 1 versions` → `edge 82`, `last 2 versions`: `edge 82` (because Can I Use will not have Edge 81), `last 5 versions`: `edge 82, edge 18, edge 17`.

**Comment by molant** [comment]
Pinging this thread now that the Edge stable is published and with version 79 😊

**Comment by ai** [comment]
Seems like Microsoft is planning to support old Edge for a while. I think the current `last 2 versions` → `edge 79, edge 18` is what people expect (since people need time to update browsers).

Feel free to ping me again a few months later. We will know how Can I Use will deal with Edge versions.

**Comment by Dangoo** [comment]
Hi, maybe slightly of topic, but wanted to ask before opening an issue:
I'm getting `edge 76` for query `last 1 Edge versions` with `browserslist@4.8.4`, can that be right?

**Comment by ai** [comment]
@Dangoo it is fixed

**Comment by axeen** [comment]
Hello! I'm testing queries on https://browsersl.ist/, and I'm getting `Edge 18` on `last 1 Edge versions`, can't seem to find any version of Edge higher than that. Did you guys decide to use Chrome as the Edge versions above 18?

**Comment by ai** [comment]
@axeen it can be a problem with website updates.

Try CLI `npx browserslist "last 1 version"`
