### ISSUE TITLE
"last 2 versions" (and "defaults") should not include "android 4.4.3-4.4.4"

### ISSUE THREAD

**Issue by antross** [browserslist/browserslist#374]
This technically falls out from how `caniuse` is representing versions for Android, but I think is worth discussing here since it impacts the `defaults` query. 

Relevant data from `caniuse`:
```json
"android": {
    "browser": "Android Browser",
    "abbr": "And.",
    "prefix": "webkit",
    "type": "mobile",
    "usage_global": {
        "2.1": 0.00480563,
        "2.2": 0.00823823,
        "2.3": 0.00480563,
        "3": 0.000686519,
        "4": 0.0988588,
        "4.1": 0.0494294,
        "4.2-4.3": 0.214194,
        "4.4": 0,
        "4.4.3-4.4.4": 0.300009,
        "67": 0
    }
```

The `caniuse` data is only providing one version covering the time since the [Android webview went evergreen in Android 5](https://developer.chrome.com/multidevice/webview/overview), even though there have been multiple versions in between, just like Chrome.

This causes `browserslist` to include `4.4.3-4.4.4` in the `last 2 versions` (and by association `defaults`) query even though it doesn't truly meet the criteria - it just appears to due to how the data is represented.

**Comment by ai** [comment]
Hi. Yeap, it is a good idea to strip `android 4.4.3-4.4.4` from `last X version`.

Can you send PR with code like:

```js
if (latestAndroid - 4 < howMuchVersion) {
  result = result.filter(i => i !== 'android 4.4.3-4.4.4')
}
```

`last 2 version` should no contain `4.4.3-4.4.4`, but `last 100 version` should.

**Comment by antross** [comment]
Thanks @ai!

I ended up opening a PR with a different approach in an attempt at a more complete fix, but if that proves to not be in alignment with your principles for the project I'm happy to adjust it to something more scoped.

**Comment by ai** [comment]
@antross oops, I merge PR but then found a big problem.

Browserslist must to return only browsers from Can I Use. We can’t return `android 67, android 66`.

For instance, Autoprefixer will use these browsers to get prefixes data from Can I Use. If we will artificially create `android 66`, Autoprefixer will not find a browser data and it could cause an error.

Can I ask you to do PR in a different way? In `last \d+ versions` query we need add a filter to remove `android 4.4.3-4.4.4` if `\d+` less than `latest - firstEvergreenVersion`.

**Comment by antross** [comment]
@ai Bummer, but I understand. I'll open a new PR with your proposed approach. 

Should I include the filter on the `last \d+ major versions`, `last \d+ \w+ versions` and `last \d+ \w+ major versions` queries in addition to `last \d+ versions`?

Also any thoughts on when `browserslist` might be ready for another major update so we can fix this more completely? And when that time comes, what do you think about sourcing missing versions from [`browsers` in `mdn/browsers-compat-data`](https://github.com/mdn/browser-compat-data/tree/master/browsers) since they seem to have a fairly comprehensive list?

**Comment by ai** [comment]
> Should I include the filter on the last \d+ major versions, last \d+ \w+ versions and last \d+ \w+ major versions queries in addition to last \d+ versions?

Yeap

> Also any thoughts on when browserslist might be ready for another major update so we can fix this more completely?

Browserslist 4 release was so painful 😣.

CRA and many other popular tools used old Browserslist and users was not able to add new queries to Browserslist config.

**Comment by ai** [comment]
I decided to ignore major versions (anyway it is a very rare query) and fixed the issue in e061cf7

**Comment by ai** [comment]
I backported changes to queries with “major” keyword 18f08a2

**Comment by antross** [comment]
Thanks for fixing this @ai!

Sorry I didn’t get to it sooner as I’ve been traveling lately. Coincidentally I was working on a fix on my flight home today, but I’m glad to see it done regardless. I’ll try to get to things a bit more quickly next time I offer to do a PR.

**Comment by ai** [comment]
Don't worry, you already did a big PR
