### ISSUE TITLE
Drop `browsers` option

### ISSUE THREAD

**Issue by nikolay-govorov** [browserslist/browserslist#376]
The other day I encountered an error - at the root of the project lay browserslist with properly configured browsers, but in autoprefix browsers were transferred separately and did not meet the requirements. Because of this prod did not get prefixes for CSS Grids in IE, and the prod fell.

It would be cool if the settings can be passed ONLY in the browserslist config.

**Comment by ai** [comment]
> It would be cool if the settings can be passed ONLY in the browserslist config.

It is not possible. But we definitely should make it harder.

**Comment by ai** [comment]
I update docs c07d0f2

Also, I will change the default option in the next major release of Autoprefixer https://github.com/postcss/autoprefixer/issues/1216
