### ISSUE TITLE
Update docs browserslist README file

### ISSUE THREAD

**Issue by RinatValiullov** [browserslist/browserslist#377]
I update docs c07d0f2

Also, I will change the default option in the next major release of Autoprefixer https://github.com/postcss/autoprefixer/issues/1216

_Originally posted by @ai in https://github.com/browserslist/browserslist/issues/376#issuecomment-494784458_

---

_My suggestion_

**Is it worth it to add some warnings(notes) because of not recommended option `browsers` in autoprefixer like here [Options, item `browsers`](https://github.com/postcss/autoprefixer/blob/master/README.md#options) in [Queries, item 2](https://github.com/browserslist/browserslist/blob/master/README.md#queries)**?

**Comment by ai** [comment]
Yeap, I will update docs, when I will add warning in Autoprefixer.

**Comment by ai** [comment]
Done https://github.com/browserslist/browserslist/commit/1de61ff3b11116f42529861cd2814f7d0d6a5159
