### ISSUE TITLE
[Feature Request:] add support for config file name => browserslist.config.js

### ISSUE THREAD

**Issue by jimblue** [browserslist/browserslist#380]
Hi,

Configuration name **`*.config.js`** seems to be the most default/common value for most of majors libraries:

- **webpack.config.js**
- **babel.config.js**
- **stylelint.config.js**
- **postcss.config.js**
- **prettier.config.js**
- **vue.config.js**
- **nuxt.config.js**
- **tailwind.config.js**
- **jest.config.js**

I see only too libraries that doesn't support this format:
- **Browserlist**
- **Eslint** ([Eslint issues 11844](https://github.com/eslint/eslint/issues/11844))

It could be nice for **Browserlist** to offer this option.

Following this convention will definitively help users.
Having a consistent way to configure libraries would be easier and cleaner.

Just my two cents to make our life a little easier 😄 !

Cheers!

**Comment by jimblue** [comment]
Seems that **Eslint** already have a PR on the go to fix this!
So we are only one library from getting a new standard... Could be worst! 😅

**Comment by ai** [comment]
Browserslist has different reason. Because of the performance Browserslist config should be static. If your want some dynamic, you can use environments.

Is it a good answer for you?

**Comment by jimblue** [comment]
I'm not talking about dynamic configuration here. Just config file naming standard.
Plus how accepting `browserlist.config.js` would decrease performance?

**Comment by jimblue** [comment]
Browserlist works with nodejs, so using a `browserlist.config.js` would actually be better for performance.

You wouldn't have to read the `.browserlistrc` file then export it as a module anymore like here:

https://github.com/browserslist/browserslist/blob/0ae7155a6c7d8f58eaeb3ea450c21bec76de2763/node.js#L274

**Comment by ai** [comment]
> I'm not talking about dynamic configuration here. Just config file naming standard.

`.config.js` will make config dynamic since it become written in JS.

> Browserlist works with nodejs

Not only. For instance, Autoprefixer Rails reads the same config by Ruby code.

> how accepting browserlist.config.js would decrease performance?

Dynamic config doesn't support caching since develop can write something like:

```js
module.exports = db.read('settings.browsers')
```

It will force Browserslist to read it again and again.

**Comment by jimblue** [comment]
> > I'm not talking about dynamic configuration here. Just config file naming standard.
> 
> `.config.js` will make config dynamic since it become written in JS.

Let's just imagine you have a `browserlist.config.js`:

```js
module.exports = [
  'last 2 versions'
  '> 0.5%'
]
```
You can import the above array and save it in a `const`. Where is the dynamic part then?

> 
> > Browserlist works with nodejs
> 
> Not only. For instance, Autoprefixer Rails reads the same config by Ruby code.
> 

Of course... I've never talk about breaking anything here!
This feature request is for **adding** a new way to configure Browserlist.

> > how accepting browserlist.config.js would decrease performance?
> 
> Dynamic config doesn't support caching since develop can write something like:
> 
> ```js
> module.exports = db.read('settings.browsers')
> ```
> 
> It will force Browserslist to read it again and again.

Again, if you save the config a `const`. Where is the dynamic part that would break the support for caching?

**Comment by ai** [comment]
> You can import the above array and save it in a const. Where is the dynamic part then?

But how we can be sure that developers use simple array in their JS code?\

> Where is the dynamic part that would break the support for caching?

We can enable cache if we will be 100% sure about non-dynamic nature of every config. A lot of developers will not predict it. They will add some dynamic code and then open issues about why Browserslist miss this dynamic behavior.

> This feature request is for adding a new way to configure Browserlist.

And how we can parse JS file in Ruby code of Autoprefixer Rails?

**Comment by jimblue** [comment]
> > You can import the above array and save it in a const. Where is the dynamic part then?
> 
> But how we can be sure that developers use simple array in their JS code?\
> 
Simply by checking if the config is an array. (https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/isArray)

> > Where is the dynamic part that would break the support for caching?
> 
> We can enable cache if we will be 100% sure about non-dynamic nature of every config. A lot of developers will not predict it. They will add some dynamic code and then open issues about why Browserslist miss this dynamic behavior.
> 
If your check if the config is a simple array as said above, this will not happen.

> > This feature request is for adding a new way to configure Browserlist.
> 
> And how we can parse JS file in Ruby code of Autoprefixer Rails?

As I said in my previous answer: **I've never talk about breaking anything here!
This feature request is for **ADDING** a new way to configure Browserlist, not delete the actual **.browserlistrc**

**Comment by ai** [comment]
> Simply by checking if the config is an array. 

This config is 100% non-dynamically:

```js
module.exports = Math.random() > 0.5 ? ['last 2 version'] : ['ie 11']
```

But it anyway returns an `Array`:

```js
const config = require('./browserslist.config.js')
Array.isArray(config) //=> true
```

The only way to guarantee that JS files export the same result is a very complex source code analyzing. I am not sure that somebody did it before for JS.

> This feature request is for ADDING a new way to configure Browserlist, not delete the actual .browserlistrc

Of course. I understood you.

If we will add one more config to Browserslist `browserslist.config.js` how we will write code in Autoprefixer Rails, which will get config value from JS file? Ruby can’t execute JS files.

**Comment by jimblue** [comment]
> This config is 100% non-dynamically:
> 
> ```js
> module.exports = Math.random() > 0.5 ? ['last 2 version'] : ['ie 11']
> ```
> 
> But it anyway returns an `Array`:
> 
> ```js
> const config = require('./browserslist.config.js')
> Array.isArray(config) //=> true
> ```
> 
> The only way to guarantee that JS files export the same result is a very complex source code analyzing. I am not sure that somebody did it before for JS.

So at this point, the array check is working.
The only remaining problem is the possibility that this array change dynamically right?
But is it really a problem as it will only executed at runtime? Postcss allow that and it seems to work well. https://github.com/postcss/postcss-loader#context-ctx

> > This feature request is for ADDING a new way to configure Browserlist, not delete the actual .browserlistrc
> 
> Of course. I understood you.
> 
> If we will add one more config to Browserslist `browserslist.config.js` how we will write code in Autoprefixer Rails, which will get config value from JS file? Ruby can’t execute JS files.

Autoprefixer Rails and Ruby can always stick to `.browserlistrc`

**Comment by jimblue** [comment]
Anyway @ai, if it doesn't make sens for Browserlist team we can just close this.
I don't want to argue for ages, but thanks for this good talk!

**Comment by amilajack** [comment]
A really good case for having a dynamic config is being able to target electron based on the dependency version. Here's how we could do this with babel:

```js
presets: [
  [
    require('@babel/preset-env'),
    {
       targets: { electron: require('electron/package.json').version }
    }
  ]
],
```

Because browerslist doesn't support .js config files we have to [hardcode the browerslist version](https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/master/package.json#L289), which makes means we have to bump the browserslist config every time we update our electron version.

**Comment by ai** [comment]
@amilajack you can try to use [sharable configs](https://github.com/browserslist/browserslist#shareable-configs) to have dynamic JS code

**Comment by rdsedmundo** [comment]
I'm also interested on this, would like to make my browserslist configuration dynamic because I have packages in the monorepo that use Node.js and others that are web applications. I even have a backend project that uses Storybook to render some HTML, so in the same project I want to change it dynamically—having to set an environment variable for every npm script is cumbersome.

This would be fairly trivial to implement using: https://www.npmjs.com/package/cosmiconfig.

**Comment by ai** [comment]
@rdsedmundo don’t use `cosmiconfig`. In PostCSS ecosystem, we migrated to smaller & faster analogs.

**Comment by rdsedmundo** [comment]
@ai I ended up using sharable configs based on your suggestion, it works. Thanks.
