### ISSUE TITLE
Unknown browser query `android all`

### ISSUE THREAD

**Issue by lemondreamtobe** [browserslist/browserslist#383]

**Comment by ai** [comment]
There is no `all` query in Browserslist. We have a reason for it. In most of the cases “all” is a mistake. Anyway you do not really support browser of Android 1.

Use `android > 0` if you really know what you do. But better use a real version.

**Comment by Slapbox** [comment]
@ai could you touch on why Android doesn't reflect versions like `56` and `67` which I've seen mentioned in the README and in other issues? I'd think that those versions should still be reflected.

**Comment by ai** [comment]
@Slapbox this issue is old. Can you create a new issue with fl details (input, expected output, real output)?
