### ISSUE TITLE
Feature request: emit js to tell if the running browser isn't supported

### ISSUE THREAD

**Issue by xenogenesi** [browserslist/browserslist#385]
I think it would be interesting if the tool could generate code to test if the browser used is not part of the supported by the query, would it be possible?

    if (<generated code>) alert('unsupported');

**Comment by ai** [comment]
We already have few solutions for it

https://github.com/browserslist/browserslist/blob/master/README.md#tools

The best way is to do it on server side, Browserslist data is too big to send it to client side.
