### ISSUE TITLE
How to use browserlist with gulp and autoprefixer

### ISSUE THREAD

**Issue by webmasterpf** [browserslist/browserslist#386]
Hi,

After updating my gulp system, I get this message when I run it:

```
Replace Autoprefixer browsers option to Browserslist config.
  Use browserslist key in package.json or .browserslistrc file.
```
But I don't find example to convert my actual code to work with these new practices. Here is my starting actual code in gulp.js file:

```
// Autoprefixer : Navigateurs à cibler pour le préfixage CSS
var AUTOPREFIXER = [

'> 1%',
'ie >= 8',
'edge >= 15',
'ie_mob >= 10',
'ff >= 45',
'chrome >= 45',
'safari >= 7',
'opera >= 23',
'ios >= 7',
'android >= 4',
'bb >= 10'
];

//Tableau pour utiliser les plugins de PostCSS
//https://webdesign.tutsplus.com/tutorials/postcss-quickstart-guide-gulp-setup--cms-24543
var processors = [
  autoprefixer(  {
                                browsers: AUTOPREFIXER,
                                cascade: false,
                                //activation du prefixage pour grid
                                grid: true
                            })
];
```
What do I need to change to get this work with browserlist now ?

Thanks

**Comment by ai** [comment]
Open `package.json` and add:

```js
  "browserslist": [
    "> 1%",
    "ie >= 8",
    "edge >= 15",
    "ie_mob >= 10",
    "ff >= 45",
    "chrome >= 45",
    "safari >= 7",
    "opera >= 23",
    "ios >= 7",
    "android >= 4",
    "bb >= 10"
  ]
```

Remove `browsers: AUTOPREFIXER` option and `AUTOPREFIXER` variable.

**Comment by webmasterpf** [comment]
Thanks, no way to modify another file than package.json ? because this file is created on the server and I need to edit it after initializing with npm and gulp. What about the browserlist file option into my project ?

**Comment by ai** [comment]
You can create `.browserslistrc` instead of editing `package.json`:

```
> 1%
ie >= 8
edge >= 15
ie_mob >= 10
ff >= 45
chrome >= 45
safari >= 7
opera >= 23
ios >= 7
android >= 4
bb >= 10
```

**Comment by webmasterpf** [comment]
Great. It's better way for me.

**Comment by alexlopez-natgeo** [comment]
is there a way to inherit from other repo?
 e.g.
for prettier, there's a repo `github/companyX/prettier-config`
later we use it on multiple package.json (distributed as npm package)
```json
"prettier": "@companyX/prettier-config"
```

**Comment by ai** [comment]
@alexlopez-natgeo yeap https://github.com/browserslist/browserslist#shareable-configs

**Comment by devkyo** [comment]
Because after declaring the browsers they support in browserlistrc still showing the alert in terminal?

**Comment by yu-coder** [comment]
I'm having same issue.

**package.json**

```
"gulp-autoprefixer": "^6.0.0",
"browserlist": "^1.0.1",
```

**Comment by ai** [comment]
@yu-coder replace `gulp-autoprefixer` into `gulp-postcss` and `autoprefixer`

**Comment by yu-coder** [comment]
Yes, just replaced.

new **package.json**
```
"autoprefixer": "^9.7.3",
"gulp-postcss": "^8.0.0",
```

But in **gulp**, I have this issue.
`$.autoprefixer is not a function`

**Comment by ai** [comment]
@yu-coder add `var autoprefixer = require('autoprefixer')` and replace `$.autoprerfixer` to `$.postcss(autoprefixer)`

**Comment by yu-coder** [comment]
Sorry, getting this issue again.

`$.postcss(...) is not a function`

**Comment by ai** [comment]
I am not sure how this `$.` magic work. Let’s try simple require there as well `var postcss = require('gulp-postcss')` and `postcss([autoprefixer])`

**Comment by ai** [comment]
Show you `Gulpfile` and `npm ls | grep autoprefixer`

**Comment by yu-coder** [comment]
**gulp/tasks/styles.js**

```
const gulp = require('gulp')
const config = require('../gulp.config')
const when = require('gulp-if')
const $ = require('gulp-load-plugins')()
const production = config.production
const moduleImporter = require('sass-module-importer')
const destination = config.theme + '/assets'
const autoprefixer = require('autoprefixer')
const postcss = require('gulp-postcss');

gulp.task('style:styles', function () {
  return gulp.src(config.src.styles + '/style.scss')
    .pipe(when(!production, $.sourcemaps.init()))
    .pipe($.sass({importer: moduleImporter()}))
    .on('error', $.sass.logError)
    .pipe(postcss([autoprefixer({browsers: ['last 2 versions', 'iOS 8']})]))
    .pipe(when(production, $.groupCssMediaQueries()))
    .pipe(when(production, $.csscomb()))
    .pipe(when(!production, $.sourcemaps.write()))
    .pipe(when(production, $.cssnano()))
    .pipe(gulp.dest(destination))
})

gulp.task('styles', gulp.series('style:styles'))
```

**npm ls | grep autoprefixer**

```
│ │ ├─┬ autoprefixer@7.2.6
├─┬ autoprefixer@9.7.3
│ │ ├─┬ autoprefixer@6.7.7
```

**Comment by ai** [comment]
Replace 

```js
    .pipe(postcss([autoprefixer({browsers: ['last 2 versions', 'iOS 8']})]))
```

to:

```
    .pipe(postcss([autoprefixer()]))
```

Add to `.browserslistrc`:

```
last 2 versions
not dead
iOS 8
```

I added `not dead` since it will dramatically reduce vendor prefixes by removing rare browser versions without security support

**Comment by NineAllexis** [comment]
@ai & @yu-coder Just wanna say thanks! I encounter exact same issue and got to this page and @ai 's solution works great! I'm just a beginner in this and you saved me lots of hours of depression trying to figure it all out. -Cheers-

**Comment by ai** [comment]
We have Open Collective if you want to speak to your amanger about open source donations
https://opencollective.com/browserslist

**Comment by ibra188** [comment]
> Open `package.json` and add:
> 
> ```js
>   "browserslist": [
>     "> 1%",
>     "ie >= 8",
>     "edge >= 15",
>     "ie_mob >= 10",
>     "ff >= 45",
>     "chrome >= 45",
>     "safari >= 7",
>     "opera >= 23",
>     "ios >= 7",
>     "android >= 4",
>     "bb >= 10"
>   ]
> ```
> 
> Remove `browsers: AUTOPREFIXER` option and `AUTOPREFIXER` variable.

were can i remove this AUTOPREFIXER option and AUTOPREFIXER variable..
and also if i add the script to the package.json it sows and errows....plz help...?

**Comment by skyshab** [comment]
@ibra188 
> > Remove `browsers: AUTOPREFIXER` option and `AUTOPREFIXER` variable.
> 
> were can i remove this AUTOPREFIXER option and AUTOPREFIXER variable..
> and also if i add the script to the package.json it sows and errows....plz help...?

Check your gulpfile to see if you are using the "browsers" key in your config.

**Comment by SamuelMiller** [comment]
> .browserslistrc
Besides putting the .browserslistrc in the same root directory as package.json. Is there anything else I need to do?

Here is the function in my gulpfile.js:
```
function compileStyles() {
    return src(paths.maincss.bootstrap)
        .pipe(purgecss({ content: ['./src/*.html', './src/assets/js/*.js'] }))
        .pipe(src(paths.maincss.theme))
        .pipe(concat('bootstrap.css'))
        .pipe(postcss([autoprefixer(), cssnano()]))
        .pipe(dest(paths.css.dest))
}
```

**Comment by rijoshdeveloper** [comment]
> Thank you! It works. 🎉 I much appreciated your help. 👍

How you have solved this issue. Can you please explain.
I'm facing the same Issue. Yarn
