### ISSUE TITLE
Browserlist is not consisting

### ISSUE THREAD

**Issue by jimblue** [browserslist/browserslist#387]
Hi,

I've always use the following config:

```json
"browserslist": [
    "last 2 versions",
    "> 0.5%",
    "not ie 11",
    "not ie_mob 11",
    "not op_mini all",
    "not dead"
  ]
```

Since today it returns me a strange result:

![Screenshot 2019-06-20 at 23 01 40](https://user-images.githubusercontent.com/10623367/59881258-6552dd00-93af-11e9-8da5-b46a2d4af533.png)

As you can see it returns **safari 5.1** whereas it shouldn't.

The same config on `browserl.ist` doesn't return **safari 5.1** as you can see.

![Screenshot 2019-06-20 at 22 57 06](https://user-images.githubusercontent.com/10623367/59881592-3f7a0800-93b0-11e9-9dd9-960b1f77d4b4.png)

I'm surprise because I haven't change my browserlist config for while...

Thanks for your help!

Cheers

**Comment by ai** [comment]
@jimblue can you try

```
npx --coverage "safari 5.1"
```

I think it has more than `0.5%`.

> I'm surprise because I haven't change my browserlist config for while...

There are two reasons to change browsers list:
1. Changing the config
2. Fresh Can I Use data in `caniuse-lite` npm package update

**Comment by jimblue** [comment]
Ya **safari 5.1** have **0.95%** of coverage.
But my config is a combination of rules... it's not only about 0.5%.

**Comment by ai** [comment]
This is `OR` combination.

We are writing it here https://github.com/browserslist/browserslist#query-composition

But you are not the first and seems like people misses it (so it is docs problem). How we can improve docs?

**Comment by jimblue** [comment]
Indeed, I didn't read that part thank you.
But how do you explain, I never had this problem before with Safari 5.1 whereas I never change my browserlist config.
Also why the results return by [https://browserl.ist](https://browserl.ist) aren't the same and don't give Safari 5.1?

**Comment by ai** [comment]
> Also why the results return by https://browserl.ist aren't the same and don't give Safari 5.1?

https://browserl.ist is not official. Maybe they forget to update Can I Use data.

**Comment by jimblue** [comment]
Ok so something have probably change on the `caniuse-lite` package as you suggest.
Also probably related to the `android all` bug 😄 !

**Comment by jimblue** [comment]
About the documentation and query composition, what's not really clear is how should we use the combinator in the json format?

like this ?
```json
"browserslist": [
    "last 2 versions",
    "and > 0.5%",
    "not ie 11",
    "not ie_mob 11",
    "not op_mini all",
    "not dead"
  ]
```

**Comment by ai** [comment]
```
"browserslist": [
    "last 2 versions and > 0.5%",
    "not ie 11",
    "not ie_mob 11",
    "not op_mini all",
    "not dead"
  ]
```

**Comment by jonathantneal** [comment]
Thank you for posting this issue, @jimblue. I was very confused.

Here are the browsers currently returning by `default`:

```js
[
  "and_chr 75",
  "and_ff 67",
  "and_qq 1.2",
  "and_uc 11.8",
  "android 67",
  "baidu 7.12",
  "chrome 72",
  "chrome 73",
  "chrome 74",
  "chrome 75",
  "edge 17",
  "edge 18",
  "firefox 60",
  "firefox 66",
  "firefox 67",
  "ie 11",
  "ie_mob 11",
  "ios_saf 11.3-11.4",
  "ios_saf 12.0-12.1",
  "ios_saf 12.2",
  "kaios 2.5",
  "op_mini all",
  "op_mob 46",
  "opera 57",
  "opera 58",
  "safari 12",
  "safari 12.1",
  "safari 5.1",
  "samsung 4",
  "samsung 8.2",
  "samsung 9.2"
]
```

I tried a similar query, `> 0.5% and not dead`, and these were the results:

```js
[
  "and_chr 75",
  "and_uc 11.8",
  "chrome 72",
  "chrome 73",
  "chrome 74",
  "edge 17",
  "edge 18",
  "firefox 66",
  "ie 11",
  "ios_saf 11.3-11.4",
  "ios_saf 12.0-12.1",
  "ios_saf 12.2",
  "op_mini all",
  "opera 58",
  "safari 12",
  "safari 12.1",
  "safari 5.1",
  "samsung 4",
  "samsung 9.2"
]
```

I think the surprising thing in both results is that `not dead` is not removing `samsung 4` or `safari 5.1`. I thought both of these browsers would fall under “_without official support or updates for 24 months_”.

**Comment by ai** [comment]
Hm. I will investigate the update status for these browsers few day later.

**Comment by ai** [comment]
https://twitter.com/Browserslist/status/1146955994901176320

**Comment by 719media** [comment]
Is there any update to this thread? I see the twitter link got some replies about samsung 4 still being used, but safari 5.1? I imagine the reason it shows anything above 0% use is it's the last version released for windows OS.

I would advocate for at least moving safari 5.1 to dead.

**Comment by ai** [comment]
@719media I found that we need to use only browsers from `last 2 version` in `dead`

**Comment by 719media** [comment]
But then safari 5.1 shows up in the "defaults" query, which I think is undesirable.
https://browserl.ist/

Are you saying this is a desirable default? Support for Safari 5.1?

**Comment by ai** [comment]
@719media `defaults` is `> 0.5%, last 2 versions, Firefox ESR, not dead`. Safari 5.1 was added because it is used by > 0.5% of users:

```sh
npx browserslist "safari 5.1" --coverage
These browsers account for 0.81% of all users globally
```

Sorry, without excplicit agreement from Safari team, I can’t remove it.
