### ISSUE TITLE
Browserslist in package.json does not adhere to JSON Schema

### ISSUE THREAD

**Issue by andrastothtw** [browserslist/browserslist#388]
I have found about this through IntelliJ warning me:
![image](https://user-images.githubusercontent.com/29704619/59915672-7afeeb80-941d-11e9-9654-9d828e37f8dc.png)

In fact it says according the JSON Schema `browserslist` would require an `array` and not an `object`:
https://flaviocopes.com/package-json/#browserslist

```json
{
  "name": "a-project",
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
```

So, is this `browserslist` issue or a `react-scripts` issue which uses `browserslist` wrong?

**Comment by ai** [comment]
You should open a issue in JetBrains repo. They have s wrong schema and I do not control it.

**Comment by andrastothtw** [comment]
Thanks for the quick answer! Created a bug report.
You can track advancement of ticket here: https://youtrack.jetbrains.com/issue/IDEA-216742
