### ISSUE TITLE
Different configs using .browserslistrc 

### ISSUE THREAD

**Issue by isabellachen** [browserslist/browserslist#391]
When I use create-react-app, it generates a package.json for me with the following browserslist config
```
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

If I want to move this to the .browserlistrc file, how can I specify two different arrays? Its not shown in the documentation, which says this:
```
# Browsers that we support

last 1 version
> 1%
maintained node versions
not dead
```

**Comment by ai** [comment]
```
[production]
> 1%
ie 10

[modern]
last 1 chrome version
last 1 firefox version
```

https://github.com/browserslist/browserslist/blob/master/README.md#environments

How we can improve docs to make it more discoverable?

**Comment by isabellachen** [comment]
Ah thanks. I probably should have ctrl+f for "environments". Maybe above the martians logo there could be a link to the section - to format these files for different environments, see [...], but maybe that will clutter up the start of the readme :/

**Comment by ai** [comment]
Table of contents is a good idea. I will open an issue until I will add TOC.

Do you want to send PR to save your name in project’s history?

**Comment by isabellachen** [comment]
Sure! It's getting late here so I'll do it tomorrow. I'll put the TOC below the Martian logo :)

**Comment by isabellachen** [comment]
Here you go :)
PR 392: https://github.com/browserslist/browserslist/pull/392
