### ISSUE TITLE
New query: Unsupported

### ISSUE THREAD

**Issue by Nettsentrisk** [browserslist/browserslist#395]
The dead query is defined as:
> dead: browsers from last 2 version query, but with less than 0.5% in global usage statistics and without official support or updates for 24 months. Right now it is IE 10, IE_Mob 10, BlackBerry 10, BlackBerry 7, and OperaMobile 12.1.

There should be a query that is defined as: 
> without official support or updates for 24 months

Or even: 
>  without official support

For example, I want to cover X % of users in country Y, but do not wish to cover browsers that are no longer officially supported by their vendors.

**Comment by ai** [comment]
Yeap. We are already changing the definition

https://twitter.com/Browserslist/status/1146955994901176320
