### ISSUE TITLE
We can’t connect to the server at browserl.ist.

### ISSUE THREAD

**Issue by lol768** [browserslist/browserslist#397]

**Comment by ai** [comment]
Create an issue here https://github.com/jonrohan/browserl.ist

It is no official project. I can’t help here.

**Comment by lol768** [comment]
I'll raise an issue.

It may be worth removing the link from the README if this is extended downtime, perhaps?

**Comment by ai** [comment]
Yeap. Good idea of removing the link. Can you send PR to save your name in history?

**Comment by ai** [comment]
I removed the link f4654af

**Comment by ThiefMaster** [comment]
Is the code behind that site open source? Could it be re-hosted as an official project (even though the current domain for it was pretty awesome)?

**Comment by ai** [comment]
Use `npx browserslist "last 2 version"`. It will give the more correct result, because of `caniuse-lite` in your `node_modules`.

I have plans to create my own Browserslist website. But I need to rewrite the code according to my standards.

**Comment by ThiefMaster** [comment]
I can't link nicely to that in [my README](https://github.com/indico/indico/#browser-support) like I did with `browsersl.ist` ;)

**Comment by ai** [comment]
> I can't link nicely to that in my README like I did with browsersl.ist ;)

Good use case. I will think about the website on this week.
