### ISSUE TITLE
new feature request: BROWSERSLIST array

### ISSUE THREAD

**Issue by weilinzung** [browserslist/browserslist#400]
Hi,

Could we have multiple values supported in `BROWSERSLIST`environment variable?
In windows with `CROSS-ENV` that if the browser name contains space would give errors.

This way only works for MAC.

command:
`../node_modules/.bin/cross-env BROWSERSLIST='last 5 versions,Safari 7,ie 10'`

```
'5' is not recognized as an internal or external command,
operable program or batch file.
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: spawn 5 ENOENT
```

Looking for is each broswer name contain quotes in brackets:

`BROWSERSLIST=['last 5 versions','Safari 7','ie 10']`

```
BrowserslistError: Unknown browser query `[last 5 versions`. Maybe you are using old Browserslist or made typo in query.
    at Array.reduce (<anonymous>)
    at new Promise (<anonymous>)
```

**Comment by ai** [comment]
You didn't see the array. Environment variables is just a string.

```
BROWSERSLIST=['last 5 versions','Safari 7','ie 10']
```

Is equal to:

```
BROWSERSLIST="['last 5 versions','Safari 7','ie 10']"
```

Adobe environment variables do not support array in Node.js (they are always just a strings) we can't support it.
