### ISSUE TITLE
Minor version numbers aren't respected in ranges

### ISSUE THREAD

**Issue by pastelsky** [browserslist/browserslist#402]
### Use case
When querying with a minor version number –

```js
var browserslist = require("browserslist")
browserslist('ios_saf >= 9.2')
```

### Expected output

```js
[
 "ios_saf 12.2-12.3",
 "ios_saf 12.0-12.1",
 "ios_saf 11.3-11.4",
 "ios_saf 11.0-11.2",
 "ios_saf 10.3",
 "ios_saf 10.0-10.2",
 "ios_saf 9.3",
 "ios_saf 9.2",
]
```

### Actual output

```js
[
 "ios_saf 12.2-12.3",
 "ios_saf 12.0-12.1",
 "ios_saf 11.3-11.4",
 "ios_saf 11.0-11.2",
 "ios_saf 10.3",
 "ios_saf 10.0-10.2",
 "ios_saf 9.3",
 "ios_saf 9.0-9.2",  // <----- This is incorrect
]
```

**Comment by ai** [comment]
Sorry, we are stuck to Can I Use versions and they track Safari in this strange version range.

Adding `9.0-9.2` is less dangerous than avoiding it.

Maybe we should try to convince Can I Use to split version ranges?

**Comment by pastelsky** [comment]
@ai Makes sense, opened an issue here –
https://github.com/Fyrd/caniuse/issues/5051
