### ISSUE TITLE
getting only latest version for android browsers

### ISSUE THREAD

**Issue by kermorgant** [browserslist/browserslist#403]
Hi,

I've maybe missed something but can't find out how to get more than one version of android browsers. 

For example, here's my test config 

```json
  "browserslist": [
      "last 10 and_chr versions",
	  "last 10 and_ff versions",
	  "last 10 and_uc versions",
	  "last 10 ios_saf versions"

  ]
```

and the output is 
![image](https://user-images.githubusercontent.com/10561580/62212080-ad025680-b3a8-11e9-9084-ef61735be029.png)

I've tested with version 4.6.6 and older up to 4.4.0, getting same result.

any idea of what's going on ?

**Comment by ai** [comment]
“It is a feature, not a bug” 😆

There are more than 10 versions between Android 75 and Android 4.4.4. https://github.com/browserslist/browserslist/blob/master/index.js#L210-L220

If you want to test Android 4.4.4, it is better to explicitly add it to the queries.
