### ISSUE TITLE
2 browsers with 0% in defaults

### ISSUE THREAD

**Issue by dmartinjs** [browserslist/browserslist#405]
Why there is 2 browsers (Android Browser67, Baidu Browser7.12) with 0% usage into defaults query ?

<img width="1666" alt="default-query" src="https://user-images.githubusercontent.com/53537199/62489853-209ccd00-b7c8-11e9-95f6-b0ebbe774a6b.png">

**Comment by ai** [comment]
Seems like it is browsersl.ist statistics rounding problem. They have less than 0.1 % and website shows it wrong. 

Please, create issue https://github.com/jonrohan/browserl.ist

**Comment by galvarez421** [comment]
If the `defaults` query was `> 0.5%, last 2 versions, Firefox ESR, not dead` at the time of the original post (https://github.com/browserslist/browserslist/tree/4.6.6#full-list shows that it was for the latest version at the time), then couldn't this also be explained by the `last 2 versions` query, which includes browsers regardless of usage?
