### ISSUE TITLE
Feature-based query

### ISSUE THREAD

**Issue by alaricd** [browserslist/browserslist#407]
While this may not be an issue, I can't find a mailing list, or any example.

I want to limit the browsers I support to those that support tls12, caniuse has the info, but I can't find any way to query for that.

If it is a supported query, can we add documentation for that?

**Comment by ai** [comment]
Nope, docs will be too big.

**Comment by piranna** [comment]
For a browser library it would make sense, but for a development tool, how much does it matter if it gets increased? I don't think it would make the package so much bigger, and would allow to do more fine-grained optimization with tools like Babel or webpack that would have a real impact in the browser deployed code.

**Comment by ai** [comment]
There are few use cases when development tool is using in the browser.

However, I have an another idea: you can create a build script, which will make sharable config for each Can I Use feature and publish these configs on npm. It will also be more flexible for tricky cases of partial feature support.

Creating these sharable configs is one of the goals on [our OpenCollective funding page](opencollective.com/browserslist).

**Comment by alaricd** [comment]
Hi, 

I have created a tool using 

https://www.npmjs.com/package/browserslist 

and caniuse-api (https://github.com/Nyalab/caniuse-api) 

to create a tool that would quiery what I need. If I had more idea of how to bundle it, pass parameters etc, it could be used for any feature. Obviously my TLS query makes the most sense, but I made it to be able query anything i the caniuse database. I might have lost the exact code but I can always recreate it. 


Alaric

**Comment by piranna** [comment]
@alaricd, have you published your code somewhere? Maybe I can do the final fixes.
@ai, would you accept a pull-request if it show to be not such a huge change?

**Comment by alaricd** [comment]
No I haven't, i lost my hard drive after getting it working. I will take some time and get it recovered and working again and let you know. 

Sent from MailDroid

-----Original Message-----

**Comment by piranna** [comment]
> No I haven't, i lost my hard drive after getting it working. I will take some time and get it recovered and working again and let you know.

Ok, don't worry, take your time :-)

**Comment by ai** [comment]
Fixed by @piranna in https://github.com/browserslist/browserslist/pull/501 and released in 4.13
