### ISSUE TITLE
bug or expected: `last 1 Node version` throws `browserslist: Unknown browser Node`

### ISSUE THREAD

**Issue by JounQin** [browserslist/browserslist#410]
As title, I think it should make sense like `last 1 Chrome version`.

**Comment by ai** [comment]
What is your use case for this query?

BTW, what version to you expect to have for `last 2 Node versions`?

**Comment by JounQin** [comment]
I'm writing a shareable config, which targets latest modern browsers and node.

https://github.com/1stG/configs/blob/master/packages/browserslist-config/latest.js

All available node versions are listed at https://nodejs.org/dist/index.json .

**Comment by ai** [comment]
Yeap, this behavior looks good. Do you want to send PR?

**Comment by JounQin** [comment]
OK, I'll do in few days.

**Comment by cowwoc** [comment]
Dead issue?

**Comment by ai** [comment]
It is not an issue, but a feature idea
