### ISSUE TITLE
Query combiners select incomplete browsers list

### ISSUE THREAD

**Issue by fichorka** [browserslist/browserslist#415]
I'm not sure if I'm mistaken, but browser selection by queries seem wrong when using combiners. I'll show a couple of examples I tried and please tell me if this makes sense to You. Thanks.

`last 2 Chrome versions` - `chrome 77 chrome 76`
`last 2 Chrome versions and not dead` - `chrome 77 chrome 76`
`last 2 Chrome versions or not dead` - `chrome 77 chrome 76`
`last 2 Chrome versions, not dead` - `chrome 77 chrome 76`

How come all of the queries select the same browsers? Shouldn't the query with `or`, or `,` combiner in this case select all the browsers considered **not dead** apart from last 2 chrome versions?

_Queries were specified in package.json file and browseres were listed with `npx browserslist`_

**Comment by ai** [comment]
It is how `not X` works. It removed `X` from previous queries.

We can’t change it, because it will be breaking changes (and because it fits all real use cases, that I know).

Can we improve this doc to make this behavior more clear? https://github.com/browserslist/browserslist#query-composition

**Comment by fichorka** [comment]
> We can’t change it, because it will be breaking changes (and because it fits all real use cases, that I know).
> 
> Can we improve this doc to make this behavior more clear? https://github.com/browserslist/browserslist#query-composition

Oh ok, thanks. I just don't understand how these queries work exactly, though it's a good thing they can be easily tested with npm commands. However, isn't it wrong to use Venn's diagram in query composition docs for some of these combiners, specifically `or`?

**Comment by ai** [comment]
> However, isn't it wrong to use Venn's diagram in query composition docs for some of these combiners, specifically or?

Why?

**Comment by fichorka** [comment]
Because it obviously doesn't include result(set) from each query in query composition.
As far as I understand (which is probably wrong) it behaves like `and` combiner/operator.

**Comment by ai** [comment]
At least I saw the same circles for `or` and `not` in my university book. Maybe they are not Venn’s diagram.

If it is not familiar to others, we can replace illustration. Do you have an idea of how to replace it?

**Comment by fichorka** [comment]
I don't.  I' don't understand these query combinations myself. Anyway, thanks for info :)
