### ISSUE TITLE
Getting unexpected results

### ISSUE THREAD

**Issue by danofpaco** [browserslist/browserslist#417]
I'm getting unexpected (outdated?) results when using Browserslist.

In my `package.json`:

```
"browserslist": [
    "last 2 Chrome versions"
],
```

(among others)

As of this writing, current Chrome is 77. Running `npx browserslist` gives me versions 74 and 75 of Chrome. Am I correct in expecting my query to be returning 77 and 76 instead?

**Comment by ai** [comment]
Check the version of `caniuse-lite` and update it

**Comment by danofpaco** [comment]
Thank you for the reply, I will check into this.
