### ISSUE TITLE
'> 10%' not working correctly?

### ISSUE THREAD

**Issue by burtek** [browserslist/browserslist#420]
Why is '> 10%' not showing Chrome 77, which has over 22% of share, but instead showing Chrome 76 with 1% of share?

Also, why is iOS Safari (with less than 5% share) included in '> 5%' ?

![image](https://user-images.githubusercontent.com/2940958/68685476-7e307a80-056a-11ea-82c5-01b205b4736a.png)

![image](https://user-images.githubusercontent.com/2940958/68685309-3c9fcf80-056a-11ea-9faf-a85d104e7530.png)

**Comment by ai** [comment]
`browserl.ist` is not official and can have different statistics.

Show me the result of:

```sh
npx browserslist "chrome 77" --coverage
```

**Comment by burtek** [comment]
Nevermind :) Didn't know about that, thanks for clarification.

![image](https://user-images.githubusercontent.com/2940958/68687813-0ebc8a00-056e-11ea-9776-f8bd3832032c.png)

**Comment by burtek** [comment]
On the other hand it's strange that the difference is so big

**Comment by ai** [comment]
Agree. Maybe we can report issue https://github.com/jonrohan/browserl.ist

**Comment by burtek** [comment]
@ai did that in https://github.com/jonrohan/browserl.ist/issues/115
