### ISSUE TITLE
`caniuse-lite` acknowledgement notice while running `npx tldrlegal`

### ISSUE THREAD

**Issue by ankurkaushal360** [browserslist/browserslist#423]
~Since my company has to comply with SOC [compliance](https://www.imperva.com/learn/data-security/soc-2-compliance/)~ 

Since my company wants to protect itself from any legal troubles in future, we ran `npx tldrlegal` on our project & it brought this to our attention:

![Screen Shot 2019-11-26 at 11 11 22 AM](https://user-images.githubusercontent.com/31927177/69651339-eccb0900-103d-11ea-8e2e-0ebf6668581a.png)

We don't use `caniuse-lite` directly but `babel` & other packages in our project does:

![image](https://user-images.githubusercontent.com/31927177/69651399-066c5080-103e-11ea-9563-9279af6c7443.png)

I would love to discuss how I help in fixing this & is it something that maintainers / contributors can fix themselves?

**Comment by ai** [comment]
Are you asking about different versions of `caniuse-lite` (it can be fixed by `npm update`) or acknowledgment notice?

**Comment by ankurkaushal360** [comment]
@ai The acknowledgement notice specifically.

**Comment by ai** [comment]
Sorry, I am not familiar with SOC 2 Compliance. Can you tell me more about the problem and how I can fix it?

**Comment by ankurkaushal360** [comment]
@ai Upon further discussion with one of my managers & seeing their update, it isn't SOC compliance thing, it's more of a legal base for our company & protect us from any legal troubles in future. Apologies for confusion. 

But coming back to the notice, is it possible that `Browserslist` & `Autoprefixer` give some credits in `README` or somewhere else? Or one option is `caniuse-lite` changes its license, I am not aware of who maintains it but it's an option nonetheless.

**Comment by ai** [comment]
CC-BY force any users to explicit tell that it is using this lib. Didn’t know about it. We can add a link to `README.md`. Do we have any rules about this mention (just a link will be enough)?

**Comment by ankurkaushal360** [comment]
@ai I am not sure but we can definitely adding a link & then run `npx tldrlegal` to confirm if the notice pops up again? Let me know if you want me to put up a PR :)

**Comment by ai** [comment]
Will `npx tldrlegal` stop to show warning if I add a mention to Autoprefixer’s docs? Seems like according to the license, every user in the chain must mentioned `caniuse-lite` somewhere.

**Comment by ankurkaushal360** [comment]
@ai I am assuming it should. One option like I mentioned before is to change the license type altogether, not sure if that's a viable option? I noticed you're one of the contributors too, is there a reason why that particular license type was chosen? :)

**Comment by ai** [comment]
> One option like I mentioned before is to change the license type altogether

We can’t do it since `caniuse-lite` is just a repack if CC-BY’s `caniuse-db`

**Comment by ai** [comment]
I added `caniuse-lite` mention to Browserslist docs e0dcbfa (but still have warning from `npx tldrlegal`)
