### ISSUE TITLE
IE_Mob 11 qualifies as dead

### ISSUE THREAD

**Issue by KevinCathcart** [browserslist/browserslist#436]
IE Mobile 11 should technically qualify as dead for almost 6 months now. It was supported as part of Windows Phone 8.x, and that went out of support on July 11, 2017.

The next version of Windows Phone (WP10) used Edge Mobile instead of IE Mobile.

**Comment by ai** [comment]
Good idea. Can you send PR? (sorry, I am bachelor's party in Mexico)

**Comment by ai** [comment]
You just need to change [this block](https://github.com/browserslist/browserslist/blob/master/index.js#L1020-L1031) and maybe check tests.

Just want to keep your name in the project history.

**Comment by ai** [comment]
Fixed 61e7c94

**Comment by ai** [comment]
Released at 4.8.4

**Comment by ai** [comment]
https://twitter.com/Browserslist/status/1219405429454909440
