### ISSUE TITLE
`last 2 chrome versions` returns [ 'chrome 78', 'chrome 77' ] - latest version is 79

### ISSUE THREAD

**Issue by uditalias** [browserslist/browserslist#437]
browserslist v4.8.3

`browserslist("last 2 chrome versions")` outputs `[ 'chrome 78', 'chrome 77' ]`

Expected output:
`[ 'chrome 79', 'chrome 78' ]`

Am I missing something? the latest stable Chrome version is 79

**Comment by ai** [comment]
You need to update `caniuse-lite` in your `node_modules` to see the latest data (also Can I Use can have a few days lag)

**Comment by uditalias** [comment]
Thanks! I'll check it out.

**Comment by uditalias** [comment]
Thanks @ai, I'll give it a try.

**Comment by uditalias** [comment]
@ai I just updated to the latest `caniuse-lite@1.0.30001021` (released 5 days ago).
`browserslist("last 2 chrome versions")` still outputs `[ 'chrome 78', 'chrome 77' ]`
Chrome 79 released on Dec 10, 2019 (40 days ago).

`browserslist("last 2 firefox versions")` outputs `[ 'firefox 71', 'firefox 70' ]` althoug 72 is the latest firefox version.

Should I open this issue in `caniuse-lite`s repo?

**Comment by ai** [comment]
`caniuse-lite` is just a repack of `caniuse-db`.

Wait a second, I will invastigate the problem.

**Comment by ai** [comment]
Seems like `caniuse-db` again changed the format 1e61852

Thanks for the notice.

**Comment by ai** [comment]
Released at 4.8.4

**Comment by ai** [comment]
Release notes: https://twitter.com/Browserslist/status/1219405429454909440

**Comment by eligao** [comment]
`caniuse-db` updated their data to rev `1.0.30001022` ( https://github.com/Fyrd/caniuse/commit/a133838cd287d3e807151a4c39ebead7bb3b18b6 )right after your commit https://github.com/browserslist/browserslist/commit/1e61852c55a31c83520392a61e3d2ad7d6cd0e8c , and the results are wrong instead.
I've created a PR to revert it: https://github.com/browserslist/browserslist/pull/438

**Comment by uditalias** [comment]
@eligao @ai I just updated `caniuse-lite` to 1.0.30001022 and it works with `browserslist@4.8.3`

Thanks

**Comment by ai** [comment]
Fixed at 4.8.5
