### ISSUE TITLE
"last N major versions" ignoring breaks in non-sequential version numbers

### ISSUE THREAD

**Issue by vetruvet** [browserslist/browserslist#447]
Right now something like "last 4 edge major versions" only reports 79 and 80, ignores 17 and 18. "last 4 edge versions" reports all four correctly.

**Using version**: 4.8.6

**Steps to reproduce**:
```
const browsers = require('browserslist');
browsers('last 4 edge major versions'); // [ 'edge 80', 'edge 79' ]
browsers('last 4 edge versions'); // [ 'edge 80', 'edge 79', 'edge 18', 'edge 17' ]
browsers('last 64 edge major versions'); // [ 'edge 80', 'edge 79', 'edge 18', 'edge 17' ]
```

**Expected behavior**: report 17, 18, 79, and 80 as last 4 major versions of edge.
**Actual behavior**: only 79 and 80 are reported

**Comment by ai** [comment]
Good point. Please send PR. I will release it.
