### ISSUE TITLE
`node 8-12` throws `browserslist: Unknown browser node`

### ISSUE THREAD

**Issue by zypA13510** [browserslist/browserslist#452]
Not sure if related to #410. When querying `node 8-12` (or anything in a similar fashion, e.g. `node 10-13`), it says `browserslist: Unknown browser node`.

### Expected behavior
I would say `node 8-12` should return all minor versions from 8.0.0 to the latest version in major version 12 (currently 12.16.0).

However, it conflicts with the existing behavior of `node 8` selecting only the latest minor version (8.17.0 but not 8.0.0), which may cause confusion.

### Workaround
In the first case (`node 8-12` returns all versions starting 8.0.0), you can use `node >=8 and node < 13` instead.

**Comment by ai** [comment]
Yeap, there is no `node X-Y` query support right now.

Send a pull request. I will release it.

**Comment by zypA13510** [comment]
Which behavior would be expected?
1. `8.0.0`, `8.1.0`, ... `8.17.0`; `9.0.0`, `9.1.0` ... `9.11.0`; `10.0.0` ... `10.19.0`; `11.0.0` ... `11.15.0`; `12.0.0` ... `12.16.0`
2. `8.17.0`, `9.11.0`, `10.19.0`, `11.15.0`, `12.16.0`

**Comment by ai** [comment]
The first one
