### ISSUE TITLE
Missing and_chr versions

### ISSUE THREAD

**Issue by pheinicke** [browserslist/browserslist#453]
Hi,

I'm trying to select Android Chrome Versions 78 and higher. I'm using the following query:
`"browserslist": [
        "and_chr >= 78"
]`

`npx browserslist` returns the following output:
`and_chr 79`

I was expecting
```
and_chr 78
and_chr 79
and_chr 80
```

I guess with and_chr 80 being released only two weeks ago there might be a delay, but at least I was expecting to see and_chr 78 in that list.

I'm using browserslist 4.8.7.

**Comment by ai** [comment]
Can I Use tracks only the lastest release for mobile browsers

**Comment by ai** [comment]
You can use `mobileToDesktop` to use desktop Chrome history for Android Chrome
