### ISSUE TITLE
`Android` query not working as expected

### ISSUE THREAD

**Issue by LyteFM** [browserslist/browserslist#457]
Hi,

I'm trying to use `Android` in order to target a specific version of Android WebView (Version 33, which is installed on devices running Android 4.4.3 [according to this](https://developer.chrome.com/multidevice/webview/overview).
But when I just pass a version like `Android 33`, it's reported as an unknown version. Using `Android >= 33` will just default to android 80 (i.e. the current version of Android WebView).

Looking at [this](https://github.com/browserslist/browserslist/issues/39) issue, I think I got the correct result by selecting `Android >= 4.4.3`. I'd suggest to either adjust the readme or to map the WebView-Versions to the corresponding OS versions.

**Comment by ai** [comment]
Android WebView was a fork from Chrome and was not compatible with Chrome. `Android 4.4.4 != Chrome 33` (but they are close to each other). This is why Can I Use and we use other versions.

I like the idea to improve docs. For instance, we can add note at `Android` browser at Browsers section. Feel free to send PR.
