### ISSUE TITLE
Sign in with Google temporarily disabled for this app  This app has not been verified yet by Google in order to use Google Sign In.

### ISSUE THREAD

**Issue by max-mykhailenko** [browserslist/browserslist#461]
Got this error when trying to update my stats with `npx browserslist-ga`

**Comment by ai** [comment]
You need to open this issue in `browserslist-ga` repo. I do not know how Google integration work and can't be helpful here.

**Comment by max-mykhailenko** [comment]
Sorry, already find https://github.com/browserslist/browserslist-ga/issues/26
