### ISSUE TITLE
pnpm tests failing

### ISSUE THREAD

**Issue by mrseanbaines** [browserslist/browserslist#463]
After cloning the repo, installing packages with `yarn` and running tests with `yarn test`, 2 tests are failing for me:

<img width="1440" alt="Screenshot 2020-03-29 at 14 31 46" src="https://user-images.githubusercontent.com/24367010/77850433-6fb9c700-71ca-11ea-9b01-66d3e15fa9eb.png">

**Comment by ai** [comment]
@mrseanbaines you need to install pnpm to test `npx browserslist --update-db` for pnpm.

Or just ignore this error.

**Comment by ai** [comment]
Fixed 50aafcd

**Comment by mrseanbaines** [comment]
Nice! 🎉
