### ISSUE TITLE
Shareable configuration on monorepo fails due to incompatible lockfiles

### ISSUE THREAD

**Issue by mitermayer** [browserslist/browserslist#464]
Hi there, 

Considering this directory structure:

```
ParentProject
   package.json
   .browserlistrc
   ...
   src
        packages
            foo
                package.json
                ...
```

How can have the project `foo` have access to the `.browserlistrc` resolved config from ParentProject? 

*** 
EDIT:
After further investigation, we realized the root cause of this issue is that `foo` project had an outdated lock file that was causing `browserslist` to resolve to a different query instead of using the same dependencies that are defined in the package which contains `.browserlistrc`

**Comment by ai** [comment]
`foo` should use `.browserlistrc` from the parent directory.

What is the current and expected behavior?

**Comment by mitermayer** [comment]
The current behaviour is:

output from running on `ParentProject` command `npx browserslist`:

```
and_chr 79
chrome 79
edge 18
firefox 72
ie 11
ios_saf 13.2
safari 13
```
output from running on `foo` command `npx browserslist`:

```
and_chr 75
chrome 75
edge 18
firefox 67
ie 11
ios_saf 12.2-12.3
safari 12.1
```

**Comment by mitermayer** [comment]
@ai Thanks for the quick response!

**Comment by ai** [comment]
`foo` output does not look like `defaults`.

What do you have in `foo/package.json`?

**Comment by mitermayer** [comment]
`foo/package.json` has a lot of installed `deps` combination of external and private packages but no reference to any `browserlist` configuration. What are the things I should be looking at ?

**Comment by mitermayer** [comment]
Maybe I should rename/rephrase this issue, I am looking for a way to share the resolved browsers version from a parent project to ensure that we are targeting same browsers.

**Comment by ai** [comment]
Browserslist looks up to the parent folders until it will find the first browserslist config:

```
A/
  .browserslistrc
  B/
    .browserslistrc <= this config will be used
    C/
      D/ <= current working dir
```

Is it expected behavior (and we are talking about the bug) or do you want to merge some specific changes with the parent config?

**Comment by ai** [comment]
If it is a bug, can you provide extra information to reproduce the problem? Maybe create a simple example?

I am going to sleep right now and will answer you tomorrow.

**Comment by mitermayer** [comment]
What I want is being able to from `foo` get the same result as from `ParentProject`:

```and_chr 79
chrome 79
edge 18
firefox 72
ie 11
ios_saf 13.2
safari 13
```

**Comment by mitermayer** [comment]
I created a repository with a minimal example and step by step on how to repro the above in:

https://github.com/mitermayer/browserslist-issue-464

**Comment by mitermayer** [comment]
Maybe I should rename this issue to "Shareable resolved browsers list"

**Comment by ai** [comment]
Thanks for the repo. I will look into it a few hours later.

We can keep the issue name until we will find out what is a reason of the problem.

**Comment by ai** [comment]
@mitermayer here is my output:

```sh
browserslist-issue-464 on master
➜ npx browserslist
npx: installed 11 in 2.267s
and_chr 80
chrome 80
edge 80
firefox 74
ie 11
ios_saf 13.3
safari 13

browserslist-issue-464 on master
➜ cd ./src/foo 

browserslist-issue-464/src/foo on master
➜ npx browserslist
npx: installed 11 in 1.765s
and_chr 80
chrome 80
edge 80
firefox 74
ie 11
ios_saf 13.3
safari 13
```

Browserslist in `src/foo` uses config from the root as expected.

Here are possible problems, which you can check in your project:
1. Maybe you have `.env` or another way to set environment variables? Something can use env variable to change Browserslist config in `src/foo`.
2. Double-check the Browserslist version in the system by `npm ls`. Maybe there is a very old version of the Browserslist.
3. Go into `node_modules`, find Browserslist and debug its code by `console.log` or debugger. You need to check [`loadConfig()`](https://github.com/browserslist/browserslist/blob/master/node.js#L201-L216).

**Comment by ai** [comment]
I know what is the problem (and why I can’t reproduce it in your example)!

You have different `caniuse-lite` versions in root and `src/foo`. Both dirs uses the same config, but because of the different Can I Use DB, `last 1 chrome version` returns different version.

Here is how you can fix it:
1. Check that you do not have `yarn.lock` in `src/foo`.
2. Run `npx browserslist@latest --update-db`. It will update `caniuse-lite` in you lock file.
3. If you still have different versions, you can compare `yarn list` in project’s root and `src/foo`. Look for Browserslist and `caniuse-lite` versions.

**Comment by mitermayer** [comment]
Hi @ai 

Thank you for explaining the above. I am aware that we could force sync the repos by updating `browserslist` on the lockfile in `foo` but that on the long run could provide a challenge on its own to ensure they are on sync.

I think what I really wished was the ability to share the resolved browsers instead of the configuration to run the query.

**Comment by ai** [comment]
> I think what I really wished was the ability to share the resolved browsers instead of the configuration to run the query.

If you have an idea of how we can change Browserslist to do it, let’s discuss it in separated issue. This one will b about different results because of different versions in lock files.

If your use Browserslist in Atlassian, it will be nice if you will talk with a manager about supporting Browserslist. We are collecting funds for security refactoring, which will prevent publishing malware like [that ESLint incident](https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes). The company will win from this refactoring.
https://opencollective.com/browserslist

**Comment by mitermayer** [comment]
> If you have an idea of how we can change Browserslist to do it, let’s discuss it in separated issue. This one will b about different results because of different versions in lock files.

I will create a separate issue for us to further elaborate on it

> If your use Browserslist in Atlassian, it will be nice if you will talk with a manager about supporting Browserslist. We are collecting funds for security refactoring, which will prevent publishing malware like that ESLint incident. The company will win from this refactoring.
https://opencollective.com/browserslist

Will forward this internally
