### ISSUE TITLE
multi-lines in .browserslistrc: AND versus OR

### ISSUE THREAD

**Issue by dilyanpalauzov** [browserslist/browserslist#466]
The documentation is not clear what happens if the queries are in .browserlistrc or package.json.browserlis: are the queries combined with AND or wtih OR?

.browserlistrc
```
> 1%
last 2 versions

```
Is this `> 1% or last 2 versions` or `>1% and last 2 versions`?

**Comment by ai** [comment]
`,` == `or` https://github.com/browserslist/browserslist#query-composition
