### ISSUE TITLE
Why Does This Use Node-Releases Data?

### ISSUE THREAD

**Issue by mudgen** [browserslist/browserslist#471]
Why does this project use data from the nodes-release project?
The data is bing used here: https://github.com/browserslist/browserslist/blob/master/index.js

This project is about web browsers.  So why is information about nodejs being used?   Just want to understand.

**Comment by ai** [comment]
> This project is about web browsers.

Nope. This project is also have many queries to select Node.js versions https://github.com/browserslist/browserslist#full-list
* `maintained node versions`
* `node 10`
* `current node`

We have this queries because Browserslits is used to select targets for Babel

**Comment by mudgen** [comment]
Gotcha,  thank you.
