### ISSUE TITLE
Wrong browser list in some cases

### ISSUE THREAD

**Issue by fdubost** [browserslist/browserslist#480]
Hi!

This command have the expected behavior:
```
> browserslist "Safari > 8 and Safari < 12, ie <= 11"
ie 11
ie 10
ie 9
ie 8
ie 7
ie 6
ie 5.5
safari 11.1
safari 11
safari 10.1
safari 10
safari 9.1
safari 9
```

But with this one, IE is removed:
```
> browserslist "ie <= 11, Safari > 8 and Safari < 11"
safari 10.1
safari 10
safari 9.1
safari 9
```

**Comment by ai** [comment]
Browserslist does not plan to have strong logical parameters. It will require a lot of work, but the community didn’t give us a money even for [security refactoring](https://opencollective.com/browserslist).

Use: `ie <= 11, Safari > 8, not Safari > 12`

Send PR if you want to improve `or`/`and` resolving algorithm. I will help you there.

**Comment by fdubost** [comment]
Ok, thank you for the tip 👍
