### ISSUE TITLE
Add support for extending a relative browserslist config in a repository using Lerna

### ISSUE THREAD

**Issue by StephenEsser** [browserslist/browserslist#484]
Add support for extending a local browserslist configuration in a repository setup using Lerna.

Repositories setup using lerna have a difficult time sharing an extendable configuration within the same project. 

Example structure:
```
.
└── terra-toolkit
    └── packages
        ├── browserslist-config-terra
        ├── eslint-config-terra
        └── terra-functional-testing
```

Example of how we attempted to extend. We also tried a local browserslist.config.js that imported/exported the browserlist-config-terra setup.
```
  "browserslist": [
    "extends ./packages/browserslist-config-terra/browserslist.config.js"
  ],
```

The root of the project defines the babel.config.js and package.json. Within the root package.json we want to extend the browserslist-config-terra configuration so it is available to babel for compiling packages independently. The package.json browserslist key does not accept a file path or read from a browserslist.config.js file in the same directory. 
 
Here is the repository for reference: https://github.com/cerner/terra-toolkit. We're looking for the ability to extend the relative package/browserslist-config-terra: https://github.com/cerner/terra-toolkit/blob/master/package.json#L25-L27

**Comment by ai** [comment]
1. What is inside your shared config?
2. Will `BROWSERSLIST_DANGEROUS_EXTEND` environment variable will help? It will allow you to use non-secure paths in `extends X` query.

**Comment by StephenEsser** [comment]
Thanks for the quick response.

1. The shared config can be viewed here: https://github.com/cerner/terra-toolkit/blob/master/packages/browserslist-config-terra/browserslist.config.js
2. I think the environment variable might help, but it will result in defining it in dozens of places. Once in every place that babel is used. As this project grows, so will the number of times the path variable is defined. I'll give it a try and see how far I can get.

**Comment by ai** [comment]
1. You have a very exclusive config, to be honest. As a creator of Autoprefixer, I created Browserslist syntax in a way to avoid this bad practice, where Western developers uses only browsers popular in their country. But it is up to you.
2. What other solution do you suggest? (do not forget to keep in mind that there are websites which use Browserslist with queries from the users, so we should care about security here).

**Comment by StephenEsser** [comment]
1. Our browserslist configuration is directly tied to browsers our internal solutions support. Our client base and solution support has a defined list of browsers/regions/technologies. Do you have suggestions for alterations?
2. Do you have examples of websites that query users? Our browserslist configurations are used during webpack, a pre-step to releasing/publishing code. My suggestions would be to allow browserslist to extend from a file path or JavaScript file (browserslist.config.js). What are the security vulnerability concerns with this approach?

**Comment by ai** [comment]
> Do you have suggestions for alterations?

Do not have allow-list and support browsers according to some policy. For instance, `last 2 versions, firefox esr, not dead`.

I understand that these changes will require a lot of internal changes in the team and is not part of this issue. I just want to clarify the philosophy behind Browserslist.

> Do you have examples of websites that query users?

https://browserl.ist/
https://codepen.io/ (they have Autoprefixer and allow to specify browsers)

**Comment by ai** [comment]
> My suggestions would be to allow browserslist to extend from a file path or JavaScript file

I like the idea to allow a non-secure path for queries from the file.

But note, that Browserslist does not support JS files for config because they are bad for caching and can’t be supported by some non-JS front-end tools (like Ruby-based Compass in the past).

**Comment by StephenEsser** [comment]
> But note, that Browserslist does not support JS files for config because they are bad for caching

How is browserslist handling JS based configurations that are extended today? Previously, before moving projects into a Lerna monorepo, our browserslist configuration was defined here using a JS file:

https://github.com/cerner/browserslist-config-terra/blob/master/browserslist.config.js

We'd then extend this in the package.json of a project that installed the extendable configuration

```json
{
  "name": "terra-example-project",
  "browserslist": [
    "extends browserslist-config-terra"
  ],
  "devDependencies": {
    "browserslist-config-terra": "^1.0.0",
  }
}
```

Example: https://github.com/cerner/terra-core/

What is the difference internally for browserslist between extending a released JS configuration vs a file path to a non-release JS configuration?

**Comment by ai** [comment]
> How is browserslist handling JS based configurations that are extended today?

You can use `browserslist-config-example/index.js` file in the sharable config. But not in the project’s config (`mywebsite/.browserslistrc`).

Sharable config often taken from npm and will not be updated during the development process.

**Comment by ai** [comment]
> I like the idea to allow a non-secure path for queries from the file.

I will not have time to change secure check in the Browserslist for the next few weeks. Possible options:

1. You can send PR with tests and docs.
2. Donate to [our OpenCollective](https://opencollective.com/browserslist) to a goal with the support option so I will be able to use working hours.

**Comment by timomayer** [comment]
The environment variable is now available: https://github.com/browserslist/browserslist/issues/516
