### ISSUE TITLE
How to use browserlist with gulp and autoprefixer

### ISSUE THREAD

**Issue by phoshenwen** [browserslist/browserslist#485]
This is in light of [this thread](https://github.com/browserslist/browserslist/issues/386), which unfortunately doesn't help my situation. My setup is pretty much as the same:

npm: 6.14.4
node: v12.13.1

package.json:
```
"autoprefixer": "^9.7.6",
"gulp": "^4.0.2",
"gulp-postcss": "^8.0.0",
"@wordpress/browserslist-config": "^2.6.0"
```

gulpfile:
```
var autoprefixer = require('autoprefixer');
var postcss = require('gulp-postcss');

gulp.task('scss', function () {
	var stream = gulp
		.src([`${paths.scss}/theme.scss`])
		.pipe(plumber())
		.pipe(newer('./src/scss/*'))
		.pipe(sourcemaps.init({ loadMaps: true }))
		.pipe(sass({ outputStyle: 'expanded' }).on('error', sass.logError))
		.pipe(postcss([autoprefixer()]))
		.pipe(sourcemaps.write(undefined, { sourceRoot: null }))
		.pipe(gulp.dest(paths.css));
	return stream;
});
```

.browserslistrc:
`extends @wordpress/browserslist-config`

No matter if I extend the wordpress config, or paste the values in manually, there are no prefixes showing up.

Per the [online autoprefixer](https://autoprefixer.github.io/) the resulting CSS should include prefixes for -ms- (the dreadful reason I am creating this post in the first place), but it doesn't.

**Comment by ai** [comment]
> No matter if I extend the wordpress config, or paste the values in manually, there are no prefixes showing up.

How do you test Autoprefixer? What is input CSS?

**Comment by phoshenwen** [comment]
Tested with the css file/chrome dev console output. Expected grid properties to be prefixed in accordance with [autoprefixer's](https://autoprefixer.github.io/) output. Instead, I am receiving no prefixed output, and just the standard css is taken over from the scss files.

At a minimum, the tested css was along the lines of:

```
.example {
    display: grid;
    grid-template-columns: 400px 500px;
    grid-template-rows: auto auto;
}
```

**Comment by ai** [comment]
@phoshenwen you need to set `grid` option:

```
.pipe(postcss([autoprefixer({ grid: 'autoplace' })]))
```

---

If you use Autoprefixer for work, tell your manager to support that the company can [support Autoprefixer](https://opencollective.com/postcss/)/[Browserslist](https://opencollective.com/browserslist] team.
