### ISSUE TITLE
Upgrade electron-to-chromium to 1.3.448 because the current used version does not contain Electron 8.3.0

### ISSUE THREAD

**Issue by kotapeter** [browserslist/browserslist#486]
If I use browserlist in Electron 8.3.0, I get the following error:

```
BrowserslistError: Unknown version 8.3.0 of electron
```

Solution:
Upgrade `electron-to-chromium` package to 1.3.448. It contains this electron version.

https://github.com/Kilian/electron-to-chromium/blob/v1.3.448/full-versions.js

Thank you!

**Comment by ai** [comment]
Do you want send a PR and update error message to suggest using dependencies?

**Comment by kotapeter** [comment]
@ai yes, It would be great:) Do I need any permission to create a pr?

**Comment by kotapeter** [comment]
@ai sure, I've opened a pr:)
