### ISSUE TITLE
Search by features

### ISSUE THREAD

**Issue by piranna** [browserslist/browserslist#491]
Since we are already using [caniuse-lite](https://github.com/ben-eb/caniuse-lite) package that allow to search [by feature](https://github.com/ben-eb/caniuse-lite#litefeaturejs), add the option to do, similar to the recomendation of testing for features in browser instead of checking compatibility using the UserAgent string.

**Comment by ai** [comment]
Dublicate https://github.com/browserslist/browserslist/issues/407

**Comment by ai** [comment]
Fixed by @piranna in https://github.com/browserslist/browserslist/pull/501 and released in 4.13
