### ISSUE TITLE
Should we run npx browserslist@latest --update-db regularly?

### ISSUE THREAD

**Issue by rj-david** [browserslist/browserslist#492]
We are using browserslist to display to our users if their browsers are out-of-date (we also use it on a number of things during development like eslint-plugin-compat). Thanks for this wonderful work, by the way.

Recently, we had issues that new Edge browsers (desktop and android) are being tagged as out of date. We saw an issue a few days ago and the solution was to run 

```
npx browserslist@latest --update-db
```

So, our question is if we need to run it regularly? During our CI/CD, we run this to update our regex patterns for useragents

```
browserslist-useragent-regexp --allowHigherVersions
```

Thinking to add the update before this if it will make sense.

**Comment by ai** [comment]
> So, our question is if we need to run it regularly?

Yeap. Run it every few months.

It updates the `caniuse-lite` database with browsers. With all data `last 2 versions` or `>1%` will return old browsers and Autoprefixer/Babel will insert polyfills for browsers, which nobody really uses nowadays.

Another option will be to run `npm update`, but it will update all your dependencies, which will force you to run the full QA process.

---

Help us maintain this project and finish security refactoring by [domantion at out Open Collective](https://opencollective.com/browserslist). Supporting tools, which creates a basement for your business is very important for sustainable development.

**Comment by nksfrank** [comment]
Is there any documentation on this function in the repo?

**Comment by ai** [comment]
@nksfrank nope, we just show it in the new warning text.

Do you want to send a PR to the docs?

**Comment by talha786-wahid** [comment]
Where I can run this command? VS-Code or cmd?
Because I am getting an error after running this command in VS-code.
Anyone, please help.

**Comment by ai** [comment]
@talha786-wahid `cmd` inside project or `VS Code`.

Show error text.

**Comment by talha786-wahid** [comment]
Error: EPERM: operation not permitted, mkdir 'C:\Users\user'
command not found: browserslist

**Comment by ai** [comment]
@talha786-wahid have no idea, sorry. Never saw it. Could be npm bug with Windows.

**Comment by Codeweb04** [comment]
> Error: EPERM: operation not permitted, mkdir 'C:\Users\user'
> command not found: browserslist

use cmd vscode integrated terminal doesn't have certain permissions. You should check to see if your vscode terminal is a powershell. I think you can change it to cmd from the dropdown at the top-right. If that doesn't work you can always use the usual command prompt. Hope this helps.

**Comment by jertje260** [comment]
> Error: EPERM: operation not permitted, mkdir 'C:\Users\user' command not found: browserslist

I have this same error on windows, I think it is related to a space in the username

**Comment by frankwo1** [comment]
Getting a weird error after running "npx browserslist@latest --update-db"
Breaks my app -
Error: Broken symbolic link encountered at /Users/WW-V2/node_modules/create-hash/node_modules/.bin/sha.js
    at isWithinProdPackage (/tools/isobuild/bundler.js:497:19)
    at /tools/isobuild/builder.js:724:15
    at Array.forEach (<anonymous>)
    at walk (/tools/isobuild/builder.js:656:34)
    at /tools/isobuild/builder.js:734:11
    at Array.forEach (<anonymous>)
    at walk (/tools/isobuild/builder.js:656:34)
    at /tools/isobuild/builder.js:734:11
    at Array.forEach (<anonymous>)
    at walk (/tools/isobuild/builder.js:656:34)
    at /tools/isobuild/builder.js:734:11
    at Array.forEach (<anonymous>)
    at walk (/tools/isobuild/builder.js:656:34)
    at Builder._copyDirectory (/tools/isobuild/builder.js:788:5)
    at Builder.copyNodeModulesDirectory (/tools/isobuild/builder.js:550:17)
    at /tools/isobuild/bundler.js:2522:17
    at Function._.each._.forEach (/Users/.meteor/packages/meteor-tool/.2.2.4.1sakonz.h63w++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:191:9)
    at JsImage.write (/tools/isobuild/bundler.js:2479:7)
    at ServerTarget.write (/tools/isobuild/bundler.js:2734:13)
    at /tools/isobuild/bundler.js:2901:30
    at /tools/isobuild/bundler.js:3040:11
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3035:26
    at /tools/isobuild/bundler.js:3401:22
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3214:31)
    at /tools/isobuild/bundler.js:3157:32
    at Slot.withValue (/Users/.meteor/packages/meteor-tool/.2.2.4.1sakonz.h63w++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/@wry/context/lib/context.js:73:29)
    at Object.withCache (/Users/.meteor/packages/meteor-tool/.2.2.4.1sakonz.h63w++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/fs/tools/fs/files.ts:1663:39)
    at Object.bundle (/tools/isobuild/bundler.js:3157:16)
    at /tools/runners/run-app.js:581:24
    at Function.run (/Users/.meteor/packages/meteor-tool/.2.2.4.1sakonz.h63w++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/tools/tool-env/tools/tool-env/profile.ts:289:14)
    at bundleApp (/tools/runners/run-app.js:580:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:627:35)
    at AppRunner._fiber (/tools/runners/run-app.js:948:28)
    at /tools/runners/run-app.js:410:12
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Anuj0124Kumar** [comment]
Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
ℹ ｢wdm｣: Hash: b57ed13ba3cc62bbdb71
Version: webpack 4.44.2
Time: 2121ms
Built at: 01/10/2023 2:26:35 PM
          Asset       Size  Chunks             Chunk Names
     index.html  305 bytes          [emitted]  
index_bundle.js   1.35 MiB    main  [emitted]  main
Entrypoint main = index_bundle.js
[0] multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/index.js 52 bytes {main} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {main} [built]
[./node_modules/react/index.js] 190 bytes {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {main} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {main} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {main} [built]
[./src/index.js] 192 bytes {main} [built]
    + 37 hidden modules
Child HtmlWebpackCompiler:
     1 asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 588 bytes {HtmlWebpackPlugin_0} [built]
ℹ ｢wdm｣: Compiled successfully.

**Comment by rakvium** [comment]
UPD: `npx browserlist@latest --update-db` is deprecated, the new command is:
```sh
npx update-browserslist-db@latest
```

(Got this info from the npx output):

```
$ npx browserslist@latest --update-db
Need to install the following packages:
browserslist@4.24.4
Ok to proceed? (y) y

The --update-db command is deprecated.
Please use npx update-browserslist-db@latest instead.
Browserslist DB update will still be made.
Latest version:     1.0.30001692
Installed version:  1.0.30001692
caniuse-lite is up to date
caniuse-lite has been successfully updated

No target browser changes

$ npx update-browserslist-db@latest
Need to install the following packages:
update-browserslist-db@1.1.2
Ok to proceed? (y) y

Latest version:     1.0.30001692
Installed version:  1.0.30001692
caniuse-lite is up to date
caniuse-lite has been successfully updated

No target browser changes

```
