### ISSUE TITLE
Microsoft Edge latest version in Android

### ISSUE THREAD

**Issue by rj-david** [browserslist/browserslist#493]
The latest version of Edge in Windows is 83

Edge in Android is 45. This is causing our system to tag Edge in Android as outdated.

Any suggestions for the rule to use in this case?

**Comment by ai** [comment]
I think the best place to open an issue is a tool, which you use to show the “your browser is outdated” banner.

These tools have User-Agent to Can I Use name conversation and it is the best place to add the fix.

**Comment by rj-david** [comment]
We actually do not use any "existing" tool as we are using the actual output from browserlist to our app.

Sorry, if this is not the right place.

**Comment by maltesa** [comment]
Im having the same issue. Maybe it makes sense to separate the new mobile version of the edge browser from their desktop versions (like `edge_mobile`)? 

Otherwise `last 2 Edge versions` should also return `45` as its the latest mobile version for android and ios.

**Comment by nikeee** [comment]
Any news on this? As far as I know, this is still an issue.
