### ISSUE TITLE
Documentation contradiction?

### ISSUE THREAD

**Issue by leaumar** [browserslist/browserslist#503]
`readme.md`:
> `and` query combinations are also supported to perform an intersection of all the previous queries:
> `last 1 version OR chrome > 75 AND > 1%`
> will select `(browser last version OR Chrome since 76) AND more than 1% marketshare`.

also `readme.md`:
> `and` combiner has precedence over `or` combiner.

This reads like a contradiction to a colleague and me. The first example suggests "and" has the unconventional effect of applying to _everything preceding_ it (ending where when using a config file? Start of line?), while the bottom paragraph suggests the more typical math-like behavior.

**Comment by ai** [comment]
The first sentence is more correct. Can you send PR to docs?

**Comment by leaumar** [comment]
I'm not really in any position to correct any docs since I'm not at the point yet of fluently speaking browserslist.

**Comment by ai** [comment]
I mean the simple fix like c3d441d
