### ISSUE TITLE
"supports" Query does not work

### ISSUE THREAD

**Issue by TomWilsonFL** [browserslist/browserslist#504]
According to the documentation it seems that this query should work, but it does not. Thoughts?

```
# npx browserslist --version
browserslist 4.13.0
# npx browserslist 'supports es6-modules'
browserslist: Unknown browser query `es6-modules`. Maybe you are using old Browserslist or made typo in query.
```

> supports es6-module: browsers with support for specific features. es6-module here is the feat parameter at the URL of the Can I Use page. A list of all available features can be found at caniuse-lite/data/features.

**Comment by ai** [comment]
Try to call `npx browserslist@latest "supports es6-modules"` in your project dir.

I am afraid that there is something broken in your `node_modules`. Maybe you need to call `npm update` or `yarn upgrade`.

**Comment by mreinstein** [comment]
@ai  there is a typo in your command. It should be:

```bash
npx browserslist@latest 'supports es6-module'
```

(module is singular)

**Comment by mreinstein** [comment]
When is this expected to land in stable?

**Comment by ai** [comment]
@mreinstein it is already in stable. I  to add `@latest` just to be sure that user is using the latest version of Browserslist.

**Comment by mreinstein** [comment]
I guess I don't understand why `npx  browserslist` doesn't run the latest version. I would have thought it would. 🤔

**Comment by ai** [comment]
> I guess I don't understand why npx browserslist doesn't run the latest version.

If you have an old version of `browserslist` in `node_modules`, `npx` will run it instead of downloading the new version (but I ma not sure).

**Comment by mreinstein** [comment]
> If you have an old version of `browserslist` in `node_modules`, `npx` will run it

You're right! I just confirmed that. Thanks :)

Although that makes me wonder if this could be considered a cacheing bug.

**Comment by nathanredblur** [comment]
I can use this `supports async-function`
but I can not do this `not supports async-function`
how can I make this work?

**Comment by ai** [comment]
@nathanredblur show error or expected/actual results

**Comment by ai** [comment]
@nathanredblur do as you asked in the error message. `not X` query could be only after some another query.

**Comment by nathanredblur** [comment]
I see, but, then I have this problem.
this are my original rules
`> 0.5%, not dead, not ie <= 11, not op_mini all`

then I found that certain legacy code was not working because not recognize async functions and I did this
`> 0.5%, not dead, not ie <= 11, not op_mini all, not supports async-functions`

but this `npx browserslist "> 0.5%, not dead, not ie <= 11, not op_mini all, not supports async-functions"`
not return results

**Comment by ai** [comment]
> but this npx browserslist "> 0.5%, not dead, not ie <= 11, not op_mini all, not supports async-functions"
not return results

It is correct result. But the true that there is no browsers for such query.
