### ISSUE TITLE
Dangerous extend without access to API

### ISSUE THREAD

**Issue by cyberbiont** [browserslist/browserslist#505]
Hi
Let me describe my usecase: I run `webhint` VS Code extension, which uses Browserslist to generate relevant hints.
This means that I don't immediately deal with Browserslist API and I cannot set `dangerousExtend` option, that I need because I have a practice of keeping all of my configs in one package. 

What would you recommend? Maybe I'm missing something?

**Comment by ai** [comment]
Why do you need to use the dangerous Browserslist config? I added `dangerousExtend` for rare hacks, not to the production usage.

We can add `BROWSERSLIST_DANGEROUS_EXTEND` env variable, but I do not want to promote dangerous configs without good use cases for it.

**Comment by timomayer** [comment]
@ai a very common usecase is to have one repo per company with all lint files in (.eslintrc, .stylelintrc, .browserslistrc) maintain it there centralized and extend from this central configs in every project. therefore this repo can not share the default naming schema with browserslist in repo/packagename but just something like "company-lint-configuration-defaults"

**Comment by ai** [comment]
Closed by https://github.com/browserslist/browserslist/pull/517

**Comment by ai** [comment]
Released in 4.14
https://twitter.com/Browserslist/status/1291517437066850305
