### ISSUE TITLE
Compatibility problems

### ISSUE THREAD

**Issue by aiyadingya** [browserslist/browserslist#506]
// .browserslistrc

and_chr > 30

> npx browserslist 

and_chr 81

I want to be compatible with versions starting from android 4.4, so the configuration is and_chr> 30. But the result of executing `npx browserslist` here is only and_chr 81, does it mean only compatible with and_chr 81 version.

What should I write, it will be compatible with 30 to the latest version？

**Comment by ai** [comment]
This is a limit of Can I Use. It provides only the latest release for Android Chrome.

You can try to use `mobileToDesktop` to convert mobile Chrome to desktop Chrome.
