### ISSUE TITLE
how to set dangerousExtend: true when browserlist is used inside of another tool like eslint-plugin-compat

### ISSUE THREAD

**Issue by timomayer** [browserslist/browserslist#516]
how to set dangerousExtend: true when browserlist is used inside of another tool like eslint-plugin-compat is there any way to do that, if not is there any chance to set maybe over .browserslistrc file in "main" project?

**Comment by ai** [comment]
Please send PRv with adding `BROWSERSLIST_DANGEROUS_EXTEND` environment variable support

**Comment by timomayer** [comment]
here we go :)

**Comment by ai** [comment]
Closed in https://github.com/browserslist/browserslist/pull/517

**Comment by ai** [comment]
Released in 4.14
https://twitter.com/Browserslist/status/1291517437066850305
