### ISSUE TITLE
browserl.ist has 503 error and the site isn't available

### ISSUE THREAD

**Issue by kb-coder** [browserslist/browserslist#518]
Looks like https://browsersl.ist/ isn't working. I see a 503: service unavilable.

**Comment by ai** [comment]
We are working on a short-term solution: https://github.com/jonrohan/browserl.ist/pull/279

FOr long-term solution please help us promote our funding campaign for redesign and security fixes:
https://github.com/jonrohan/browserl.ist/pull/279
