### ISSUE TITLE
Update DB requires auth credentials 

### ISSUE THREAD

**Issue by SevenOutman** [browserslist/browserslist#529]
I ran into this issue in my React project in a CI environment. I ran `browserslist --update-db` in my `prebuild` npm script and got this error log:

    + npm run build --if-present

    > xxxx@ prebuild /jenkins/workspace/xxxx
    > browserslist --update-db

    npm ERR! This request requires auth credentials. Run `npm login` and repeat the request.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /jenkins/.npm/_logs/2020-09-08T08_01_03_012Z-debug.log
    child_process.js:640
        throw err;
        ^

    Error: Command failed: npm show caniuse-lite --json
    npm ERR! This request requires auth credentials. Run `npm login` and repeat the request.

I do have some scoped packages installed from my custom npm registry, but the installing phase finished without auth errors. Why does `browserslist --update-db` requires auth credentials?

**Comment by ai** [comment]
Very strange.

Can you try `npx browserslist --update-db`?

**Comment by SevenOutman** [comment]
> Can you try `npx browserslist --update-db`?

No luck. `npx browserslist --update-db` failed with the same reason.

**Comment by ai** [comment]
Do you use proxy for npm?

`--update-db` calls `npm install`

**Comment by SevenOutman** [comment]
> Do you use proxy for npm?

No. 

`npx` and `prebuild` both work fine on my local machine and fail in CI environment.

**Comment by ai** [comment]
Do you have private dependencies in your `package.json` which can be instaleed without npm login?

**Comment by ai** [comment]
I improved UI 927dee2

You need to call `npm install` manually.

**Comment by ai** [comment]
Released in 4.14.2.

**Comment by SevenOutman** [comment]
> Do you have private dependencies in your `package.json` which can not be installed without npm login?

I do have private dependencies but they can be installed by `npm ci` without npm login.

**Comment by ai** [comment]
We can’t use `npm ci` since we need to update the lock file. It could be a reason why npm asks you an npm login.

If you have an idea of how to pass npm login to `--update-db` feel free to send PR.

Sorry, for this month I spend all my time for PostCSS 8.0 release.
