### ISSUE TITLE
Unknown version 59 of op_mob

### ISSUE THREAD

**Issue by mischnic** [browserslist/browserslist#537]
```js
const browserslist = require("browserslist");

console.log(browserslist(["op_mob 59"], {mobileToDesktop: true}));
```

fails with

```
Uncaught Error [BrowserslistError]: Unknown version 59 of op_mob
    at Function.select (.../node_modules/browserslist/index.js:1101:17)
    at .../node_modules/browserslist/index.js:336:33
    at Array.reduce (<anonymous>)
    at resolve (.../node_modules/browserslist/index.js:318:18)
    at browserslist (.../node_modules/browserslist/index.js:443:21)
```

```
console.log(browserslist(browserslist(['op_mob 46']))); // == [ 'op_mob 46' ]
console.log(browserslist(browserslist(['op_mob 47']))); // Error
```

This has come up because Parcel first does `browserslist(["> 0.25%"])` with the query read from some npm package.json, and then passing the result to Babel which calls `browserslist` again (https://github.com/parcel-bundler/parcel/issues/5164#issuecomment-695348725)

**Comment by Natetronn** [comment]
Subscribed...

**Comment by ai** [comment]
Do you have an idea how to solve the problem?

**Comment by mischnic** [comment]
No.

So when running `browserslist` without `mobileToDesktop: true`, `data` in this line just before the error https://github.com/browserslist/browserslist/blob/7986f767c7323d8141cc27e332b499fdf772cac1/index.js#L1085

is:
```js
{
  name: 'op_mob',
  versions: [
    '10',   '11',
    '11.1', '11.5',
    '12',   '12.1',
    '59'
  ],
  released: [
    '10',   '11',
    '11.1', '11.5',
    '12',   '12.1',
    '59'
  ],
  releaseDate: {
    '10': 1287100800,
    '11': 1300752000,
    '12': 1330300800,
    '59': 1593475200,
    '11.1': 1314835200,
    '11.5': 1318291200,
    '12.1': 1349740800
  }
}
```

With `mobileToDesktop: false`, all versions are there except `59`, so

```js
console.log(browserslist(["op_mob 46"], {mobileToDesktop: false})); // throws, expectedly?
console.log(browserslist(["op_mob 59"], {mobileToDesktop: false})); // doesn't throw, expectedly?
console.log(browserslist(["op_mob 59"], {mobileToDesktop: true})); // throws?
```

The description

> mobileToDesktop: Use desktop browsers if Can I Use doesn’t have data about this mobile version

suggests that turning on that option should never produce more errors than before.

---

Maybe here

https://github.com/browserslist/browserslist/blob/7986f767c7323d8141cc27e332b499fdf772cac1/index.js#L253-L258

`browserslist.data[name]` should be somehow merged in as well (to get the `use desktop browsers if not available` effect)? Though I'm surprised that there is no Opera Desktop 59 in the first place....

**Comment by Natetronn** [comment]
> Though I'm surprised that there is no Opera Desktop 59 in the first place....

There was one, unless you mean in the browserlist itself?

https://blogs.opera.com/desktop/2018/11/opera-developer-59-with-built-in-crypto-wallet-access/ - (many posts on it, in fact.)

**Comment by mischnic** [comment]
> unless you mean in the browserlist itself?

Yes, in the browserslist database

**Comment by ai** [comment]
Browserslist uses Can I Use as a database. Can I Use doesn't have a separated data for mobile browser versions.

This option just cover desktop browser versions to mobile, assuming that they have the same features.

It is a hack. But Babel team needed it.

**Comment by Natetronn** [comment]
Not sure if this is helpful or if there is something I can do to help?

https://help.opera.com/en/opera-version-history/
https://help.opera.com/en/operas-archived-history/

**Comment by Natetronn** [comment]
Here's the Opera versions that's on Can I use: https://i.imgur.com/Daenha9.png

https://caniuse.com/ciu/comparison

**Comment by scriptex** [comment]
Here is what I did in order to (temporarily) fix the issue:

1. Deleted the `.cache` folder
2. Added `"not op_mob > 1"` in the `browserslist` setting in my `package.json` file.
3. Rebuilt the project

I am using parcel-bundler v.1.12.4

**Comment by mischnic** [comment]
@ai 

So from what I can tell, `mobileToDesktop` actually always uses the desktop version of the browser, not only `if Can I Use doesn’t have data about this mobile version`.

I think there are solutions:
- change `mobileToDesktop` to somehow merge mobile & desktop (if that's even possible?)
- add Opera Desktop 59 to the Can I Use DB (which I don't know how to do: https://github.com/Fyrd/caniuse/blob/master/CONTRIBUTING.md#unsupported-changes), as it's not listed on https://caniuse.com/ciu/comparison

**Comment by ai** [comment]
> change mobileToDesktop to somehow merge mobile & desktop (if that's even possible?)

Can I Use doesn’t have version data of mobile browsers? There is no database to merge with.

> add Opera Desktop 59 to the Can I Use DB

I think this is the best solution since Can I Use data is not valid right now.

**Comment by mischnic** [comment]
> Can I Use doesn’t have version data of mobile browsers? There is no database to merge with.

At least on https://caniuse.com/ciu/comparison, I can see an "Opera Mobile" browser. The versions on that page are also in the snippet I posted here: https://github.com/browserslist/browserslist/issues/537#issuecomment-695352420 (`op_mob`).

> I think this is the best solution since Can I Use data is not valid right now.

Do you know how to do this/who to ask?

**Comment by ai** [comment]
> At least on https://caniuse.com/ciu/comparison, I can see an "Opera Mobile" browser

I mean that Can I Use has no separated version for ach browser. For Opera Mobile they have only the latest version.

> Do you know how to do this/who to ask?

Send PR to Can I Use and give me a link. I will support you in the PR.

**Comment by ai** [comment]
@mischnic can you also try [this PR](https://github.com/browserslist/browserslist/pull/511) for Browserslist 5.0? Did it fix this problem?

**Comment by mischnic** [comment]
> can you also try this PR for Browserslist 5.0? Did it fix this problem?

`console.log(browserslist(["op_mob 59"], {mobileToDesktop: true}));` still fails.

**Comment by mischnic** [comment]
> Send PR to Can I Use and give me a link. I will support you in the PR.

-> https://github.com/Fyrd/caniuse/pull/5617

**Comment by ai** [comment]
Opera 59 w never released. I will add a fix to `mobileToDesktop`.

**Comment by eranroll** [comment]
Hi! Any updates?
I tried the workaround using “not op_mob 59” and it doesn’t work… so I’m kind off stuck on this one...

**Comment by AddictionRecovery** [comment]
I have nothing new to contribute here just wanted to confirm I am experiencing the same issue and none of the suggestions in this issue or here https://github.com/parcel-bundler/parcel/issues/5164 have worked so far.

**Comment by codyrushing** [comment]
none of the solutions have worked for me either

**Comment by Natetronn** [comment]
You deleted .parcel-cache, npm_modules, and package-lock.json (or yarn.lock), added the suggestions to your package.json?

Then ran `npm install` or `yarn` to reinstalled all the dependencies?

Using Yarn, this one worked for me:

```
"resolutions": {
  "browserslist": "4.14.2",
  "caniuse-lite": "1.0.30001129"
}
```

**Comment by ai** [comment]
Fixed 674b53a

**Comment by ai** [comment]
The fix was released in 4.14.4

**Comment by mischnic** [comment]
Thank you!

**Comment by Natetronn** [comment]
Yes, thank you! 

Really appreciate everyone taking this on and so quickly.

**Comment by skipjack** [comment]
Just ran into this error with another package, @ai's `browserlist` release note combined with bumping the `caniuse-lite` version from `1.0.30001129` to `1.0.30001192` in `resolutions` was the only thing that seemed to work...

``` json
  "resolutions": {
    "browserslist": "4.14.4",
    "caniuse-lite": "1.0.30001192"
  },
```

Confusing because the recommended `npx browserslist@latest --update-db` command kept yielding the error whenever I'd restart my `parcel` server. Anyway hope the above might help others and wondering if this is something specific to `parcel`...

**Comment by skipjack** [comment]
The `package.json` file in combination with `npm-force-resolutions`...

https://www.npmjs.com/package/npm-force-resolutions

**Comment by lunlian** [comment]
https://github.com/dkjfu
https://github.com/xzjss
