### ISSUE TITLE
browserslist reports an error during the Jenkins build process

### ISSUE THREAD

**Issue by ZengTianShengZ** [browserslist/browserslist#539]
When I use Jenkins to build a project, the following error will be reported to prevent Jenkins from building.

![image](https://user-images.githubusercontent.com/15622519/93956870-ab9ea500-fd85-11ea-97af-2a4ac5d07fa2.png)

I upgraded the package locally `npx browserslist@latest --update-db` according to this [issues](https://github.com/browserslist/browserslist/issues/492), and then I directly re-direct Jenkins and there is no problem.

But it is troublesome for me to upgrade the package every time before Jenkins builds.

I tried to upgrade the package during the Jenkins build phase, but it didn’t work.

![image](https://user-images.githubusercontent.com/15622519/93957227-6b8bf200-fd86-11ea-95b9-accc4123230a.png)

Is there a better solution.

**Comment by ai** [comment]
`caniuse-lite is outdated` is not an error. It is just a warning. You have some other reason why your build was killed.

But the only way to preventing a warning is `npx browserslist@latest --update-db`. You need to run it only once per 6 months. Here are the reasons why it is important: https://github.com/browserslist/browserslist#browsers-data-updating
