### ISSUE TITLE
Types For browserslist ? 

### ISSUE THREAD

**Issue by mbostwick** [browserslist/browserslist#541]
would you be amenable to a PR with the types in this project ? (wanted to ask before I routed it) 

These ones are out of date.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/browserslist/index.d.ts

**Comment by ai** [comment]
Sure! Send PR.

**Comment by Semigradsky** [comment]
@ai how about to move typings to this repo? I can send PR

**Comment by ai** [comment]
I would like to avoid namespace, have TypeDoc and use `check-dts`.

Like in PostCSS types.

**Comment by mbostwick** [comment]
@Semigradsky thanks ! (webpack 5 upgrades, and some other things pulled me away from getting this done my self :'( )

**Comment by ai** [comment]
Released in 4.15.
