### ISSUE TITLE
Environment variables with webpack EnvironmentPlugin

### ISSUE THREAD

**Issue by xavierfoucrier** [browserslist/browserslist#542]
Hi Andrey @ai,

I am trying to move my browserslist configuration **inside a dedicated json file** for one of my project.
The main goal of this is to have as less configuration files as possible in the project's root directory.

Here is my implementation with the webpack `EnvironmentPlugin`:

![env](https://user-images.githubusercontent.com/2471223/95601712-22a98e00-0a54-11eb-9478-04fa7ffa6de8.png)

Compilation gives the same result even if I change my browserslist query.
Looks like loaders like `autoprefixer` doesn't seem to take care of webpack `EnvironmentPlugin` variables :thinking: ...

> Note that when directly setting the `BROWSERSLIST` environment variable with `process.env.BROWSERSLIST = 'last 2 year and last 2 major version';` before `module.exports` works. I also tried to run into this with the `DefinePlugin`, but still the same result.

May be I am missing something.
Thanks for your help. :wink:

**Comment by ai** [comment]
Very likely that it could be an `EnvironmentPlugin` issue. Maybe webpack run multiple threads and one of them miss environment variables from `EnvironmentPlugin`.

Another place to look: some other tool may set default Browserslist if there is no config in the root (and override environment variable).

You can try adding `console.log(process.env)` to `node_modules/autoprefixer/lib/autoprefixer.js` to be sure, that `EnvironmentPlugin` works.

**Comment by xavierfoucrier** [comment]
Thanks a lot @ai for the fast reply.
I will give a look at this tomorrow and will let you know 😉

**Comment by xavierfoucrier** [comment]
@ai as you guessed, it looks like putting `console.log(process.env.BROWSERSLIST)` at the top of `node_modules/autoprefixer/lib/autoprefixer.js` gives `undefined`... so definitely not an issue with browserslist.

I will investigate more on the other side!
Thanks for your time and feedback :wink:

**Comment by xavierfoucrier** [comment]
Hi @ai,

Just to let you know (and other developers), it looks like `DefinePlugin` and `EnvironmentPlugin` with `webpack 4` doesn't set environment variables "globally" before running webpack, even if the plugin is set at the top of the configuration: variables are defined at build time and will only be available inside js modules using `process.env.*` prefix, webpack configuration is excluded from that...

So for now, I am setting `BROWSERSLIST` env variable at the top of the webpack configuration using:

```js
const { browser } = require('./src/site.json');

process.env.BROWSERSLIST = browser.target;
```
