### ISSUE TITLE
Waterfox

### ISSUE THREAD

**Issue by a8nJ** [browserslist/browserslist#545]
Please consider adding this browser:

https://github.com/MrAlex94/Waterfox

as lack of support for this, is causing major sites to break (https://crates.io)

**Comment by ai** [comment]
Browserslist uses Can I Use browsers.

If you want to add a browser you need to ask Can I Use for it.

**Comment by a8nJ** [comment]
I dont know what that is

**Comment by ai** [comment]
Can I Use is the website https://caniuse.com/

Here is Can I Use repository https://github.com/fyrd/caniuse
