### ISSUE TITLE
How are unknown browser versions handled?

### ISSUE THREAD

**Issue by wilx** [browserslist/browserslist#556]
I am observing odd behaviour with my compilation. If I use this, everything seems to be OK, normal, no polyfills are used:

```
  "browserslist": {
    "production": [
      "Firefox >= 83",
      "Chrome >= 86"
    ]
  }
```

But if I raise the version of Chrome to 87 like this, I suddenly get a lot of polyfills:

```
  "browserslist": {
    "production": [
      "Firefox >= 83",
      "Chrome >= 87"
    ]
  }
```

Is Chrome 87 really that bad or is it just that it is unknown version and it defensively uses polyfills?

**Comment by ai** [comment]
It could be a bug with Babel.

Chrome 87 was not released yet. Very likely, that Babel does not have polyfills data for unreleased Chrome and add all polyfills.

---

I do not recommend locking explicit versions of browsers. `last 2 Chrome versions` is a little better way (but choosing 2 Western browsers is not the best for international diversity). `last 2 version, not dead` is a better way.

**Comment by wilx** [comment]
What I have here is `Version 87.0.4280.66 (Official Build) (64-bit)`.

**Comment by ai** [comment]
@wilx Can I Use database can be a little slow, [Chrome 87 is still unreleased](https://caniuse.com/av1). Chrome 87 was released just in on this week.

Also, you need to regularly call `npm update` or `npx browserslist --update-db` to be sure that your browser's data is synced with Can I Use website.
