### ISSUE TITLE
Add syntax highlight for Browserslist config to GitHub

### ISSUE THREAD

**Issue by ai** [browserslist/browserslist#564]
Docs: https://github.com/github/linguist/blob/master/CONTRIBUTING.md

**Comment by voskresla** [comment]
https://github.com/github/linguist/pull/5099#

**Comment by Alhadis** [comment]
Approved. 😉

**Comment by ai** [comment]
@Alhadis you have first-class contributors support in `linguist`. Great work!

**Comment by Alhadis** [comment]
I practically live on GitHub.

😀 Thanks, mate.
