### ISSUE TITLE
Avoid loading polyfill when using browserslist

### ISSUE THREAD

**Issue by devquestionz** [browserslist/browserslist#570]
I am using Gatsby and only want to support modern browsers and dont want to use polyfill. In my package.json I used:

```js
  "browserslist": [
    "supports es6-module"
  ],
```
but polyfill is still loaded. What should I set the browserlist to avoid loading polyfill?

**Comment by devquestionz** [comment]
also according to gatsby their default is :

```
  "browserslist": [">0.25%", "not dead"]
```

**Comment by Semigradsky** [comment]
What polyfill are you talking about?

**Comment by devquestionz** [comment]
@Semigradsky thanks for your response. Entire polyfill js when loaded, I dont want to include any polyfills

**Comment by ai** [comment]
@devquestionz you need to write to Gatsby or Babel. Seems like they use Browserslist wrong.

**Comment by devquestionz** [comment]
@ai 
I think it is me who is doing it wrong
can you please just let me know what setting I should set browserlist to just include modern browsers? like last 3 major release of firefox, chrome, and safari. No IE support or other old browser.

**Comment by ai** [comment]
Try to run `npx browserslist` in project dir to see what Browserslist see
