### ISSUE TITLE
Typo in query error

### ISSUE THREAD

**Issue by leepowelldev** [browserslist/browserslist#571]
Please forgive me if I'm doing something wrong, but running this example from the readme:

```
npx browserslist "> 1%, IE 10"
```

Results in: `browserslist: Unknown browser query 10. Maybe you are using old Browserslist or made typo in query.`

I've tried numerous things like installing `browserslist` globally and updating the db ... every time I seem to get the same.

**Comment by ai** [comment]
Maybe you have a newline after `IE` or some another symbol, which looks like space but is not a real space?

**Comment by leepowelldev** [comment]
Sadly not, just tried typing it out again from scratch and same error...

**Comment by ai** [comment]
It is some strange `npx` issue in the latest npm. It removed `"` in query and send `[">", "1%,", "IE", "10"]` to Browserslist in `process.argv` instead of `["> 1%, IE 10"]`.

Can you create an issue in npm?

**Comment by ai** [comment]
Quick solution: call `npx browserslist` in the project where you have local Browserslist in `package.json`

**Comment by leepowelldev** [comment]
Bug report is already open at npm - have referenced.

**Comment by ai** [comment]
Thanks. Hope they will fix it quickly. Very painful big for the community.

**Comment by leepowelldev** [comment]
Sure, hopefully shouldn't impact many and most users are probably still on v6
