### ISSUE TITLE
Not clear how to use dangerousExtend option

### ISSUE THREAD

**Issue by Rolandisimo** [browserslist/browserslist#573]
Please help me understand how to make a shareable browserslist work as currently the error message I get is not helpful and the docs are not clear imho.

### Error message
```
browserslist: Browserslist config needs `browserslist-config-` prefix.  Use `dangerousExtend` option to disable.
```

The documentation says

> If you don’t accept Browserslist queries from users, you can disable the validation by using the or BROWSERSLIST_DANGEROUS_EXTEND environment variable or dangerousExtend option.

Some websites show this
```
browserslist(queries, { path, dangerousExtend: true })
```

However, none of this explains where to actually use it or whether it can be used in the package.json browserslist array  
In my case I have a repository with a `.browserslistrc` file. It needs to be used in another project in either way that is possible
### Using rc file
```
    "browserslist": [
        "extends @myRepo/config/.browserslistrc"
    ]
```
or
### Using index.js
```
    "browserslist": [
        "extends @myRepo/config/browserslist-config-myConfig"
    ]
```

**Comment by ai** [comment]
Why example from the docs (`BROWSERSLIST_DANGEROUS_EXTEND=1 npx webpack`) does not explain how to set an environment variable?

You need to add `BROWSERSLIST_DANGEROUS_EXTEND=1 ` prefix before the script which runs your build tools.

**Comment by Rolandisimo** [comment]
@ai and what about `dangerousExtend`? I don't believe this issue is resolved. I still have no clue how to make it work using `dangerousExtend`. Either the documentation should be updated or parts about `dangerousExtend` removed. Wdyt?

**Comment by ai** [comment]
> I don't believe this issue is resolved.

I closed only a duplicate issue. This issue is still open.

> what about dangerousExtend?

It is an option for users (or tools) who uses Browserslist JS API. Since you just write a config and call Babel/Autoprefixer, you can’t set `dangerousExtend` option.

> Either the documentation should be updated or parts about dangerousExtend removed. Wdyt?

I removed note of this option from this section 1c746d5 I think mentioning this option in JS API options section is enough.

**Comment by Rolandisimo** [comment]
@ai ah, my bad, I actually didn't notice I created a duplicate issue. Thanks.

Got it. So the only option when extending in package.json is to have an env variable then. Thanks for clarifying this and have a nice day 🙂
