### ISSUE TITLE
Not clear how to make a shareable config work

### ISSUE THREAD

**Issue by Rolandisimo** [browserslist/browserslist#574]
Please help me understand how to make a shareable browserslist work as currently the error message I get is not helpful and the docs are not clear imho. Ultimately, it'd be great to improve the documentation on this.

### Error message
```
browserslist: Browserslist config needs `browserslist-config-` prefix.  Use `dangerousExtend` option to disable.
```

The documentation says

> If you don’t accept Browserslist queries from users, you can disable the validation by using the or BROWSERSLIST_DANGEROUS_EXTEND environment variable or dangerousExtend option.

Some websites show this
```
browserslist(queries, { path, dangerousExtend: true })
```

However, none of this explains where to actually use it or whether it can be used in the package.json browserslist array  
In my case I have a repository with a `.browserslistrc` file. It needs to be used in another project in either way that is possible
### Using rc file
```
    "browserslist": [
        "extends @myRepo/config/.browserslistrc"
    ]
```
or
### Using index.js
```
    "browserslist": [
        "extends @myRepo/config/browserslist-config-myConfig"
    ]
```

**Comment by ai** [comment]
Duplicate https://github.com/browserslist/browserslist/issues/573
