### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by sammyjo1307** [browserslist/browserslist#575]
https://github.com/browserslist/browserslist/issues

**Comment by sammyjo1307** [comment]
monolithed":true,"octetstream":true,"shanewholloway":true,"broxmgs":true,"staydan":true,"fabrianibrahim":true,"tdreitz":true,"monkeykode":true,"eshinn":true,"alexxnica":true,"oleg_tsyba":true,"cedx":true,"cbetancourt":true,"freaktechnik":true,"mskjp":true,"dwqs":true,"brofox":true,"tztz":true,"gurunate":true,"ravinggenius":true,"horrorandtropics":true,"jherax":true,"princetoad":true

**Comment by ai** [comment]
I am closing this issue since it has no description
