### ISSUE TITLE
Incorrect incompatibilities flagged when caniuse has a footnote

### ISSUE THREAD

**Issue by SDRACK** [browserslist/browserslist#576]
Hey all,

I'm seeing incompatibilities flagged for features that are supported by the browser(s) in question. Take IntersectionObserver and Chrome 86:

<img width="599" alt="Screen Shot 2021-01-12 at 15 32 35" src="https://user-images.githubusercontent.com/8395303/104335991-d60a9e80-54eb-11eb-9f5c-c5a6543bd1d0.png">

It flags Chrome 86 as not supporting the feature, yet according to [caniuse.com]((https://caniuse.com/intersectionobserver)):

<img width="835" alt="Screen Shot 2021-01-12 at 15 34 33" src="https://user-images.githubusercontent.com/8395303/104336079-eb7fc880-54eb-11eb-9345-032c211719fd.png">

The possible cause / issue I can see is the footnote attached to the compatibility, which results in `caniuse-lite` returning `"y #4"`:

<img width="123" alt="Screen Shot 2021-01-12 at 15 33 02" src="https://user-images.githubusercontent.com/8395303/104336203-11a56880-54ec-11eb-8829-3d363e5d4906.png">

Is this intended behaviour or a bug? Apologies in advance if I've overlooked something or this is intended behaviour :)

This is on version 4.16.1, `caniuse-lite` v 1.0.30001174

**Comment by ai** [comment]
I am not `compact/compact` developer (is it ESLint plugin)? Are you sure that this bug is related to Browserslist and not to this tool?

If yes, please post Browserslist JS API call, real result, and expected result.

**Comment by SDRACK** [comment]
Looks like it's my mistake here - I'd thought we were using browserslist to get this compatibility, missed the `compat/compat` info.

Thanks for the quick reply regardless @ai.
