### ISSUE TITLE
Can I only find desktop browsers only?

### ISSUE THREAD

**Issue by CHANist** [browserslist/browserslist#579]
As the web app I develop have a companion mobile App, so when visit the webpage from mobile, instead of login page, it will redirect to a page to download Android / iOS app instead. 

So I think I do not need the extra flag, and just concern on the desktop one. I know this may not be the expected behavior browserlist was originally designed for. But in this way, when building project, I may skip some of the polyfill needed to generate or some of the css prefix that is needed and so on, so that I can have a smaller bundle file size. 

Is it possible using browserlist?

**Comment by Semigradsky** [comment]
@CHANist  You can manually ignore mobile browsers:
```
> 1%, not and_chr 87, not and_uc 12.12, not samsung 13.0, ...
```
See also #131

**Comment by ai** [comment]
We think it is a bad practice for most of the cases and we do not want to promote it by adding a special query.
