### ISSUE TITLE
Requires CC 4.0 licence due to caniuse-lite dependency

### ISSUE THREAD

**Issue by mfields3** [browserslist/browserslist#582]
Whilst this package is under MIT, it utilises a dependency under CC 4.0.

Out of 2k packages used in our solution, caniuse-lite via browserslist is the only such package under CC 4.0.

Is there any chance of this being reworked to use an alternative?

**Comment by ai** [comment]
Can I ask you for some proofs that only CC-code can use CC dependencies?

**Comment by mfields3** [comment]
I do not mean that only CC code can use CC dependencies - this is incorrect.

The issue is the CC 4.0 licence is more restrictive than MIT (in that it requires attribution). As browserslist uses a dependency under CC 4.0, we would have to attribute the dependency,

As mentioned, out of 2k packages used (dependencies of packages we use of which browserslist is one of them), browserslist is the only such one that has a dependency that requires attribution. 

All licence checks for npm packages (correctly) iterate the entire dependency graph and report licences required for any and all dependencies. Would recommend checking out [legally](https://github.com/franciscop/legally) and [tldrlegal](https://github.com/eladnava/tldrlegal).

Hence wondering if only dependencies using MIT/ISC/BSD/Apache 2.0/DBAD can be utilised.

**Comment by ai** [comment]
> we would have to attribute the dependency

What do you mean?

**Comment by mfields3** [comment]
See https://creativecommons.org/licenses/by/4.0/

> Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

**Comment by ai** [comment]
We have an explicit link to Can I Use in docs https://github.com/browserslist/browserslist/blob/main/README.md

What exactly changes do you suggest?

**Comment by ai** [comment]
Closing because of the lack answer

**Comment by Ginden** [comment]
@mfields3 According to [Creative Commons Page](https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses), licenses without `-SA` aren't viral.
