### ISSUE TITLE
Config query doesn't work

### ISSUE THREAD

**Issue by fobdy** [browserslist/browserslist#587]
```
> npx browserslist@latest 'config'
browserslist: Unknown browser query `config`. Maybe you are using old Browserslist or made typo in query.
```

**Comment by ai** [comment]
There is no `config` query. We have only `browserslist config`.

**Comment by fobdy** [comment]
@ai Sorry, but
```
> browserslist config
browserslist: Unknown browser query `config`. Maybe you are using old Browserslist or made typo in query.
```
Maybe I misunderstand something?

**Comment by fobdy** [comment]
@ai BTW
Statement from the [documentation](https://github.com/browserslist/browserslist#full-list):

<img width="668" alt="изображение" src="https://user-images.githubusercontent.com/1515734/110799676-7b43b800-828c-11eb-923e-1b305f70edb9.png">


<img width="799" alt="изображение" src="https://user-images.githubusercontent.com/1515734/110799645-73841380-828c-11eb-8e1d-ea4c9d4c2fd5.png">

**Comment by ai** [comment]
@fobdy you need to enter:

```sh
npx browserslist "browserslist config"
```
