### ISSUE TITLE
I set Firefox >40 but the Settings are invalid

### ISSUE THREAD

**Issue by zhoudanjun** [browserslist/browserslist#589]
I set Firefox >40 but the Settings are invalid

**Comment by zhoudanjun** [comment]
![Uploading image.png…]()

**Comment by zhoudanjun** [comment]
![image](https://user-images.githubusercontent.com/23226626/113407677-60261d00-93e0-11eb-9879-0060f4d9c1cf.png)

**Comment by Semigradsky** [comment]
@zhoudanjun https://github.com/browserslist/browserslist#queries
It should be `.browserslistrc` config file. Not `.browserslist`.
