### ISSUE TITLE
Browserslist update with rush and pnpm doesn't work

### ISSUE THREAD

**Issue by raldone01** [browserslist/browserslist#590]
I use rush to manage a big monorepo.
It has many subprojects.
Rush stores no individual lock file and instead keeps one big lock file in a central location.

While building with rush my subprojects output the following error:
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
```

When I cd into a subproject and run `pnpx browserslist@latest --update-db` it crashes with the following error:
`No lockfile found. Run "npm install", "yarn install" or "pnpm install"`

**Comment by ai** [comment]
I did not cover this case in [`update-db.js`](https://github.com/browserslist/browserslist/blob/main/update-db.js).

Please send PR if you want to fix this case since I am on open source vacation and the case is relatively rare.

**Comment by raldone01** [comment]
I ran `rush update --full` apparently it is enough to just update the caniuse-lite package.

**Comment by wbern** [comment]
I made a script to bump only caniuse-lite (since `rush update --full` is a rather disruptive operation just for this package to be updated).

Here is a script that I made. Make sure it exists under `scripts/` in your monorepo, since I hard-coded paths to navigate to root from there (or you can just alter the code).

https://gist.github.com/wbern/1f560e2ea3fc7093743c8107a0e105e2

**Comment by Measy** [comment]
You can just write a `.pnpmfile.cjs readPackage hook`, and run `rush update --recheck`; As @wbern mentioned，`rush update --full` is a rather disruptive operation just for this package to be updated
```js
function readPackage(packageJson, context) {

  // // The karma types have a missing dependency on typings from the log4js package.
  // if (packageJson.name === '@types/karma') {
  //  context.log('Fixed up dependencies for @types/karma');
  //  packageJson.dependencies['log4js'] = '0.6.38';
  // }
  if (packageJson.dependencies && packageJson.dependencies['caniuse-lite']) {
    packageJson.dependencies['caniuse-lite'] = '^1.0.30001251';
    context.log(`${packageJson.name} caniuse-lite use ^1.0.30001251`)
  }

  return packageJson;
}
```

**Comment by KVROHITH098** [comment]
Ok then correct it. 


Thank you

**Comment by gianpaj** [comment]
I believe this works for `pnpm` to only update one package :
```
pnpm up caniuse-lite
```
https://pnpm.io/cli/update
