### ISSUE TITLE
--update-db to work with npm-shrinkwrap.json

### ISSUE THREAD

**Issue by johngeoffrey** [browserslist/browserslist#594]
npm-shrinkwrap.json and package-lock.json are functionally the same for `npx browserslist@latest --update-db` to work.

It would be good to update the script to treat npm-shrinkwrap.json the same as a package-lock.json

**Comment by ai** [comment]
Why do we need `npm-shrinkwrap.json` for the modern npm ecosystem?

**Comment by johngeoffrey** [comment]
https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#package-lockjson-vs-npm-shrinkwrapjson

**Comment by ai** [comment]
It is not an answer why do you publish this config.

I do not see a big and important use case to do it on my own, but I will accept PR.

**Comment by ai** [comment]
The fix was released in 4.16.6.
