### ISSUE TITLE
Webpack with Browserslist and Autoprefixer doesn't make any prefixes

### ISSUE THREAD

**Issue by MegaBulkOrg** [browserslist/browserslist#599]
Hello!

With purpose to make prefixes to styles I installed autoprefixer, browserslist and postcss-loader. Then I connected autoprefixer in webpack.config.js:
```
const autoprefixer = require('autoprefixer')
```
After this I added postcss-loader for processing css files
```
const cssLoaders = extra => {
	const loaders = [
		{
			loader: MiniCssExtractPlugin.loader,
			options: {
				publicPath: ''
			}
		},
		'css-loader',
		'postcss-loader'
	]
	if (extra)
	{
		loaders.push(extra)	
	}
	return loaders
}
module: {
	rules: [
		{
			test: /\.css$/,
			use: cssLoaders()
		},
		{
			test: /\.less$/,
			use: cssLoaders('less-loader')
		},
		{
			test: /\.s[ac]ss$/,
			use: cssLoaders('sass-loader')
		}			
	]
}		
```
And I made 2 files at root folder of the project: .browserslist and postcss.config.js. In postcss.config.js I put this code:
```
module.exports = {
  plugins: [
    require('autoprefixer')
  ]
}
```
And in .browserslist I put this code:
```
cover 99.5%
last 20 versions 
not dead
```
As a result, no prefixes are created. Can you tell me what I'm doing wrong and how to fix my code so that it creates prefixes?

**Comment by ai** [comment]
What CSS do you use to test prefixes?

I recommend `a { user-select: none }`

**Comment by MegaBulkOrg** [comment]
Yes, for this CSS property prefixes are created. But for no one property more. What is the reason?

**Comment by ai** [comment]
> But for no one property more. What is the reason?

Seems like, you do not these prefixes anymore.

See https://github.com/postcss/autoprefixer#why-doesnt-autoprefixer-add-prefixes-to-border-radius

**Comment by MegaBulkOrg** [comment]
But why then in Gulp all prefixes are being made?

**Comment by ai** [comment]
You still didn't answer r about CSS that you use to test prefixes. I can answer to you question without it

**Comment by MegaBulkOrg** [comment]
I use
```
	color: #26f0cb;
	padding: 25px;
	border: 7px solid #f30d7b;
	width: 50%;
	font-family: new-tegomin;
	display: inline-block;
	background: blue;
	user-select: all; 
```

**Comment by MegaBulkOrg** [comment]
I added more style and make screenshot.
![Снимок экрана 2021-05-14 в 19 34 51](https://user-images.githubusercontent.com/77190488/118301467-c0ce6c80-b4eb-11eb-8d67-3b8f153bc5c8.png)

**Comment by MegaBulkOrg** [comment]
I added more style and make screenshot.
![Снимок экрана 2021-05-14 в 19 34 51](https://user-images.githubusercontent.com/77190488/118301645-fc693680-b4eb-11eb-96f2-d0fcda9758a9.jpg)

**Comment by ai** [comment]
You do not need prefixes for these styles anymore.

In Gulp you may have old `caniuse-lite` in dependencies with outdated data about browsers.

Don't forget to update it by calling `npx browserslist@latest --update-db`

**Comment by MegaBulkOrg** [comment]
I don't use in Gulp caniuse-lite. Just gulp-autoprefixer

**Comment by ai** [comment]
@MegaBulkOrg `gulp-autoprefixer` has `postcss` and `autoprefixer` in dependencies. `autoprefixer` has `browserslist` and `caniuse-lite` in dependencies.

Every time when you install `gulp-autoprefixer`, you install `postcss` and `caniuse-lite`.

Just check `npm ls | grep caniuse-lite`

**Comment by MegaBulkOrg** [comment]
Well I update caniuse-lite as you told me but Gulp still makes more prefixes then WebPack.

**Comment by ai** [comment]
1. Show what is a difference
2. Show your Browserslist config (config location and content)

**Comment by MegaBulkOrg** [comment]
- Difference is that Gulp makes prefixes for such styles like display, align-items and justify-content.
- For Gulp I didn't make Browserslist config
- In WebPack I have browserslist@4.16.6 and caniuse-lite@1.0.30001228 and in Gulp I also have browserslist@4.14.6 and caniuse-lite@1.0.30001228

**Comment by ai** [comment]
1. Show `npx browserslist` output for webpack and Gulp cases
2. What is Autoprefixer version in Gulp version
3. What Browserslist config do you have for webpack?

**Comment by MegaBulkOrg** [comment]
1. See this picture
![Снимок экрана 2021-05-15 в 17 17 26](https://user-images.githubusercontent.com/77190488/118364590-b79fd700-b5a1-11eb-986a-181bc7674b4b.png)
2. gulp-autoprefixer@7.0.1 and autoprefixer@9.8.6
3. I made file .browserslist with this code:
```
cover 99.5%
last 20 versions 
not dead
```

**Comment by ai** [comment]
Maybe there is old fixed bug in old Autoprefixer.

I do not think we should spend time of finding a reason why old Autoprefixer generated wrong output.

Also we never supported `gulp-autoprefixer`. `gulp-postcss` is only right way to avoid these problems with Autoprefixer updates.

The new version is correct. You do not need prefixes.

**Comment by MegaBulkOrg** [comment]
Ok. Thanks.
