### ISSUE TITLE
Disable font styles in the terminal

### ISSUE THREAD

**Issue by geminic** [browserslist/browserslist#605]
I use the string with the result of the database update, but I get this:
`Latest version:     \u001b[1m\u001b[32m1.0.30001237\u001b[39m\u001b[22m\nInstalled version:  \u001b[1m\u001b[32m1.0.30001237\u001b[39m\u001b[22m\n\u001b[1m\u001b[32mcaniuse-lite is up to date\u001b[39m\u001b[22m\n`
It looks cool in the terminal, but there are many invisible symbols and tags, that make it difficult to work with the string in javascript.
As I understand, the **colorette** package is being used to add the font styles. Is there any way to disable it and output the raw text?

**Comment by ai** [comment]
`colorette` had a special code to detect color support from terminal.

You can disable colour by setting `NO_COLOR=1` environment variable.

Or maybe we can fix `colorette` color support detection. How do you run Browserslist?

**Comment by geminic** [comment]
It works for me, thank you!

I run Browserslist from javascript with exec:

`exec('npx browserslist@latest --update-db', { env: { 'NO_COLOR': 1 } }, (error, stdout) => {
    . . .
})`

> Or maybe we can fix colorette color support detection.
This solution works well in my case, but it would be great to have an option to disable it once and for all.
