### ISSUE TITLE
Getting BrowserslistError in WebdriverIO

### ISSUE THREAD

**Issue by vinodtestautomation** [browserslist/browserslist#609]
@wdio/runner: BrowserslistError: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's`. Maybe you are using old Browserslist or made typo in query

![Screenshot_1](https://user-images.githubusercontent.com/62179164/124567052-3e19bc00-de61-11eb-91aa-8aca0101d533.png)

**Comment by ai** [comment]
It is a problem above the Browserslist.

Some tool (could be `gensync` or Babel) calling Browserslist with wrong options.
