### ISSUE TITLE
[ Question ] : Will autoprefixer prefix my css properties ONLY for the listed browsers in .browserslistsrc?

### ISSUE THREAD

**Issue by Mr-M1M3** [browserslist/browserslist#610]
Hello there, I want to use PostCSS autoprefixer with browserlist. But, will autoprefixer prefix my css properties **ONLY** for the browsers listed in .browserslistsrc? It's not an issue, but I couldn't find the answer anywhere. So, i had to do this. Plz, help me.

**Comment by ai** [comment]
> will autoprefixer prefix my css properties ONLY for the browsers listed in .browserslistsrc?

Yes

**Comment by Mr-M1M3** [comment]
> > will autoprefixer prefix my css properties ONLY for the browsers listed in .browserslistsrc?
> 
> Yes

you mean, **ONLY** the selected browsers, nothing else. Right?

**Comment by ai** [comment]
Yes
