### ISSUE TITLE
 Browserslist: caniuse-lite is outdated

### ISSUE THREAD

**Issue by KishaniKandasamy** [browserslist/browserslist#611]
OS -
**Windows 10**

Hi,
After running this command  also  **npx browserslist@latest --update-db** , I'm getting the same error!
Can anyone Please help me to fix it?

**Comment by ai** [comment]
What error?

**Comment by KishaniKandasamy** [comment]
When I run my React app this error always pops up

**Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db**

So then I run npx browserslist@latest --update-db in the shell:
**caniuse-lite has been successfully updated
No target browser changes**

when I run my Next program, again the same error occurs
**Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db**

**Comment by ai** [comment]
Seems like Next.js put Browserslist inside it without a way to update it by npm.

Try to ask Next.js community.
