### ISSUE TITLE
`browserslist.coverage` broken for 'my stats'

### ISSUE THREAD

**Issue by DanielHeath** [browserslist/browserslist#613]
At https://github.com/browserslist/browserslist/blob/main/index.js#L580 , the call to `env.getStat(opts)` doesn't pass the second (mandatory) output parameter, which causes it to crash in all cases.

Changing that line to `env.getStat(opts, data = {})` fixes it.

**Comment by ai** [comment]
Can you send PR?

**Comment by ai** [comment]
Like this 333f1fc ?

**Comment by ai** [comment]
(What exact error did you have to mention in `CHANGELOG.md`?)

**Comment by DanielHeath** [comment]
That commit changes `normalizeStats`, not `getStats`. I can see that the latter calls the former, but you can't set `data` in getStats by assigning it in `normalizeStats` (you can set properties but, not assign a new object). 

As a result, the fix doesn't actually fix it.

Definitely running the latest version. Can also reproduce it on a git checkout of `eb11543`.

Error message is:
```
      if (versions.length === 1 && data[i] && data[i].versions.length === 1) {
                                       ^

TypeError: Cannot read property 'op_mini' of undefined

```

`i` is `'op_mini'` and `data` is `undefined`.

**Comment by DanielHeath** [comment]
Thanks for your help and for having already fixed it!
