### ISSUE TITLE
Add support for Naver Whale

### ISSUE THREAD

**Issue by carlosjeurissen** [browserslist/browserslist#618]
As Naver Whale is a browser with a separate WebExtension store and it's own webExtension adaptions and additions, it is very valuable to have it supported in browserslist.

See: https://whale.naver.com/en/

**Comment by ai** [comment]
Sorry. You need to ask Can I Use team to add it. We just using their data.

**Comment by carlosjeurissen** [comment]
See: https://github.com/Fyrd/caniuse/issues/6004
