### ISSUE TITLE
nanocolors failing on Node v.15

### ISSUE THREAD

**Issue by svennergr** [browserslist/browserslist#624]
Hey,

I noticed the change of colorette to nanocolors. 
Since we are currently using Node v15.12.0 and nanocolors only supports "^8.0.0 || ^10.0.0 || ^12.0.0 || ^14.0.0 || >=16.0.0" this change of dependency is breaking our project.

This might be attended and I know, that we probably should upgrade our Node version, but just wanted to let you know about this.

**Comment by ai** [comment]
Node.js 15 out of support.

You can keep using Node.js 15 by `--ignore-engines`.

If it is not acceptable, I can think about another solution.

**Comment by svennergr** [comment]
Fine for me. But honestly I did not expect such change in a minor version update ;)

**Comment by ai** [comment]
I released 0.1.6 with odd versions support.

**Comment by svennergr** [comment]
Perfect, thanks for this fast response :)
