### ISSUE TITLE
Bad form to console.warn about outdated packages

### ISSUE THREAD

**Issue by Sembiance** [browserslist/browserslist#628]
Started getting spam in my console logs when running `eslint` : `Browserslist: caniuse-lite is outdated. Please run: npx browserslist@latest --update-db`

Uhm, it's pretty bad form to console.warn() all random end users that a package might be out of date. That's not something you should be concerned about or warning about.

Especially since your 'fix' for the problem, this `update-db` code, feels like a major hack, detecting package managers and updating various lock files.

Just, NO.

Please remove this console.warn

**Comment by ai** [comment]
Can you explain your use case?

---

This warning is important (for me) because it affects `last 2 version` and similar browser’s query. Without DB updates you will have unexpected results which will lead to slow websites for everyone (old DB leads to many unnecessary polyfills which slow down JS bundle).

**Comment by Sembiance** [comment]
It's just not accepted behavior for 3rd party modules such as this to output random console messages about dependencies being out of date. If every module out there decided to due this the way browserlist does, every time you run anything in node we'd be flooded with messages on the console.

It really doesn't need much more explaining than that. This is fairly obviously improper.

Checking for updated dependencies on every code execution simply isn't something you should be doing, it's not your job and is not proper behavior. The onus for updated dependencies is on packages that use them, using the standard package.json syntax.

Based on the fact that you feel this is appropriate, I don't think anything I can say will convince you otherwise.

At the **VERY LEAST** you should do one of the following:
1. Check a ENV variable so I can SILENCE the messages
2. Suggest to folks that they use something like package.json `resolutions` feature to update the caniuse-lite package

**Comment by ai** [comment]
Feel free to send PR with a message about `resolutions` in case that current package manager support it.

If you will find a use case where ENV silencer will be useful for developer and end-users, feel free to send PR as well.
