### ISSUE TITLE
Should I run 'npx browserslist@latest --update-db' in my production server

### ISSUE THREAD

**Issue by moshfiqrony** [browserslist/browserslist#632]
Hi, I use AWS EC2 to run my React app. I use GitLab, Jenkins, AWS Code Deploy stack for CI/CD. In this CI/CD stack we have some scripts file that runs every time we give new deploy. I have three questions.

Question 1: Does not running the command affect my app that is build using `yarn build` and running though nginx? If yes What can be the problem?
Question 2: Do I need to run `npx browserslist@latest --update-db` in my production build?
Question 3: If the answer to the first question is "Yes I have to run it". How the process should go with CI/CD because if I give it in the script it will run every time I will give a new build. 

Please let me know If you have more information from my side.
Thanks in advance.

**Comment by ai** [comment]
What is your Browserslist config?

What tools use Browserslist (you can check it in `npm ls`).

**Comment by moshfiqrony** [comment]
This is what the config I have in my package.json

```
"browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

**Comment by ai** [comment]
> Question 1: Does not running the command affect my app that is build using yarn build and running though nginx? If yes What can be the problem?

Yes. You `>0.2%` query is time sensitive. With old `caniuse-lite` it will return very old browsers. It will lead to more JS/CSS polyfills in your webapp bundle and slower work.

> Question 2: Do I need to run npx browserslist@latest --update-db in my production build?

You need to run it on your development machine just to update `yarn.lock` or `package-lock.json`.

You need to call it every 3-5 months.

> Question 3: If the answer to the first question is "Yes I have to run it". How the process should go with CI/CD because if I give it in the script it will run every time I will give a new build.

It is up to you. I do not know your CI and help here.

**Comment by yairEO** [comment]
What is `Discussions`? Why can't a person post an issue as a question? (it's the norm in 99% Github projects), just configure your Github issues templates accordingly to allow a variety of issues' types.

Anyway, I don't understand you @ai, you said `You need to call it every 3-5 months.`, which makes no sense, as deployment machines gets a complete clean install on each deployment, so the command will run anyway, so I don't see how would devops time it to "3-5 months" using a clean machine each time.
