### ISSUE TITLE
npx browserslist@latest --update-db fails

### ISSUE THREAD

**Issue by mangelozzi** [browserslist/browserslist#639]
```
postcss /file/in.css -u autoprefixer -o /file/out.css
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
michael@dev:~$ npx browserslist@latest --update-db
npx: installed 6 in 2.408s
Cannot find package.json. Is this the right directory to run `npx browserslist --update-db` in?
michael@dev:~$ sudo npx browserslist@latest --update-db
npx: installed 6 in 1.142s
Cannot find package.json. Is this the right directory to run `npx browserslist --update-db` in?
```
What dir should I  be executing these commands in?

Note: I have installed my NPM pacakges with `-g` global switch (I dev in python, and only use NPM for building).

**Comment by ai** [comment]
> `michael@dev:~$`

Do you install `autoprefixer` and `postcss-cli` global?

**Comment by mangelozzi** [comment]
> > `michael@dev:~$`
> 
> Do you install `autoprefixer` and `postcss-cli` global?

Yes I do. I updated the to the lastest nodejs and now it is working.

**Comment by ZWChenn** [comment]
Could you share what directory you run the code. I got the same warning in the console.
