### ISSUE TITLE
Allow to pass path to lock file

### ISSUE THREAD

**Issue by alber70g** [browserslist/browserslist#640]
Currently I'm facing the issue that I have no lock file in the root of the project.

So I need to be able to pass the path to the lockfile. We're using https://rushjs.io/ monorepo tool.

The command `npx browserslist@latest --update-db` fails with

```log
No lockfile found. Run "npm install", "yarn install" or "pnpm install"
```

**Comment by eimerreis** [comment]
@alber70g - I'm also using rush monorepo manager and faced the same issue. I found a small helper script within issue #590, which updates the pnpm-lock file. I added it to my `common/scripts` folder and then ran: 

![image](https://user-images.githubusercontent.com/14016944/145839053-b7d8bdd6-e354-4d03-bef5-fb85cb912360.png)

```shell
node common/scripts/update-caniuse.js
rush update
```
