### ISSUE TITLE
standardize syntax

### ISSUE THREAD

**Issue by alexander-akait** [browserslist/browserslist#641]
The syntax is not currently standardized, there are plans on rust based implementation, but will be good to avoid problems between different implements and avoid incompatibility problems. In theory, we could just rewrite the code, but this does not provide any guarantees for future changes and additions.

@ai thoughts?

**Comment by ai** [comment]
Sure. I like this idea.

But I am bad with syntax definition language. Can somebody help me with it?

**Comment by alexander-akait** [comment]
I think simple grammar will be enough here, like (pseudo code):
```
root               = browsers-list
browsers-list = browser [newline browser]*
browser         = [not]? [ defaults | ie | firefox ]!
```

and describe `[]`/`?`/`!` means, I don't think we need an academic level for this, just so others can read it and implement

**Comment by ai** [comment]
Yeap, I need somebody who will write this rules

**Comment by alexander-akait** [comment]
@ai Maybe you describe all possible variants and I will do it, just as a creator, it will be easier for you to do it

**Comment by ai** [comment]
All queries are described here https://github.com/browserslist/browserslist#full-list

Syntax for combining queries here https://github.com/browserslist/browserslist#query-composition

RegExps to parse queries: https://github.com/browserslist/browserslist/blob/main/index.js#L677

Interesting cases from tests:

```
last 1 Baidu version and not <2% in AT
Last 01 MaJoR Version
node 7.5.0
supports arrow-functions
> .2% in US
> 10.2% in US
> 1% in alt-AS
Last 01 Explorer Version
```

**Comment by g-plane** [comment]
Here is what I'm working recently: https://github.com/g-plane/browserslist-rs .

**Comment by g-plane** [comment]
There is a similar issue: #421 . I think we can close this to avoid duplication.
