### ISSUE TITLE
unknown support for edge mobile

### ISSUE THREAD

**Issue by cdaringe** [browserslist/browserslist#642]
# Problem

By studying https://github.com/browserslist/browserslist#browsers, it is unknown if browserslist supports edge mobile.

With proper coaching, I can send a patch to the README to help clarify.

[edge mobile installation URL](https://play.google.com/store/apps/details?id=com.microsoft.emmx&hl=en_US&gl=US). example user agent

<details>
<summary>Example user agent + parse output</summary>

<pre>
uap('Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1; Microsoft; Lumia 950) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Mobile Safari/537.36 Edge/15.14977')
{
  ua: 'Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1; Microsoft; Lumia 950) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Mobile Safari/537.36 Edge/15.14977',
  browser: { name: 'Edge', version: '15.14977', major: '15' },
  engine: { name: 'EdgeHTML', version: '15.14977' },
  os: { name: 'Windows Phone', version: '10.0' },
  device: { vendor: 'Microsoft', model: 'Lumia 950', type: 'mobile' },
  cpu: { architecture: undefined }
}
</pre>
</details>

**Comment by ai** [comment]
We do not support Edge Mobile.

To add browser support we need to add it to Can I Use, we just use their DB.

Why it is unknown if there is no Edge Mobile in the list?

**Comment by cdaringe** [comment]
> Why it is unknown if there is no Edge Mobile in the list?

Because "Edge for Microsoft Edge" is in the browsers list, leaving ambiguity if Edge Mobile could be categorized under the "Edge" label.

Currently https://github.com/browserslist/browserslist#browsers is a list. Perhaps a markdown table could remove some of that ambiguity?

| Browser Name | Desktop | Mobile/Android | Mobile/iOS | Mobile/Other |
| -- | -- | -- | -- | -- |
| Chrome | `Chrome` | `ChromeAndroid`,`and_chr` | unavailable | n/a |
| BlackBerry | n/a | n/a | n/a | `BlackBerry`, `bb` |
| Edge | `Edge` | unavailable | unavailable | n/a |

...etc. 

What do you think? I'd be happy to send a patch.

I think this is quite nice because it disambiguates by providing an extra dimension of discriminating information

**Comment by ai** [comment]
Hm, interesting idea. Let’s see how it will look like on big scale.

**Comment by cdaringe** [comment]
Cool. what do you mean “at a bigger scale?” Would you like me to complete the table, for demonstration?

**Comment by ai** [comment]
Yeap, At big scale = full table

**Comment by cdaringe** [comment]
closing this issue, moving discussion to #649
