### ISSUE TITLE
Safari 15.1 still not listed?

### ISSUE THREAD

**Issue by sylvaindubus** [browserslist/browserslist#644]
Hello there,

I work on a project where we heavily rely on browserslist for particular features. Currently, using the latest version (4.17.6), Safari 15.1, which has been released two weeks ago (just before the last browerslist release) is not listed yet.

Here is my browerslist's string:
`Safari >= 11.1 or unreleased Safari versions`

And here is what I get:
`safari 15
safari 14.1
safari 14
safari 13.1
safari 13
safari 12.1
safari 12
safari 11.1
safari TP`

I wonder how new versions are added to the list, and what is the average delay between a release and the support in browserslist.

Thanks!

**Comment by ai** [comment]
We are using browsers list from Can I Use and can’t change it.

You should ask Can I Use to add new version.

**Comment by ai** [comment]
https://github.com/Fyrd/caniuse

**Comment by sylvaindubus** [comment]
Thanks for the info! 👍
