### ISSUE TITLE
Unreleased versions will be included when querying `since 1970`

### ISSUE THREAD

**Issue by g-plane** [browserslist/browserslist#646]
When querying `since 1970`, it will be parsed into the UNIX timestamp `0`. On the other hand, in `caniuse-lite` data, release date of unreleased versions are `null`.

Now, when processing `since` query, there is a comparison logic: https://github.com/browserslist/browserslist/blob/29cecf978e78d4e3daab99809e8816488fcf8fb7/index.js#L212 .

In JavaScript, `null >= 0` will be evaluated to `true`, which causes unreleased versions will be included in the result when querying `since 1970`.

I'm not sure whether it's a bug or not. I found this problem when I was implementing `since` query in [browserslist-rs](https://github.com/g-plane/browserslist-rs), and currently I implemented this feature/bug as-is: https://github.com/g-plane/browserslist-rs/blob/35ed72f516ab1230d0c102169a9bbe25f493fedb/src/queries/since.rs#L53-L62 .

**Comment by ai** [comment]
Wow, crazy bug. Thanks.

I will add special logic for `null`. We should not use `data.releaseDate[v] === null` in any `since X` query.
