### ISSUE TITLE
Possibility to turn this annoying warning off

### ISSUE THREAD

**Issue by bmaehr** [browserslist/browserslist#651]
Please add an option to turn these annoying and useless warnings off.

```
✖ 2 problems (0 errors, 2 warnings)
  0 errors and 1 warning potentially fixable with the `--fix` option.

- building... [broccoli-persistent-filter:EslintValidationFilter > applyPatches]Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
/ building... [Babel: ember-concurrency-decorators > applyPatches]Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
| building... [Babel: ember-pikaday > applyPatches]Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
\ building... [Babel: mvb-ember-components > applyPatches]Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
| building... [Babel: mvb-ember-components > applyPatches]Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
```

1.) The output is done every build and many times
2.) The npx command is not working because I don't have a npx command (only npm or yarn)
3.) I didn't find any documentation WHAT the command is really supposed to do and I prefer not to execute commands doing "something"
4.) I don't care how many percent which browser is used at the moment. The project should be built the same way today and in two years.

**Comment by ai** [comment]
What Browserslist config do you have?

**Comment by ai** [comment]
> The npx command is not working because I don't have a npx command (only npm or yarn)

Seems like you need to update `npm`. You are using very old version, which is not safe.

> I didn't find any documentation WHAT the command is really supposed to do and I prefer not to execute commands doing "something"
> I don't care how many percent which browser is used at the moment. The project should be built the same way today and in two years.

I improved docs 3d3df97

Now they are explicitly saying about the reasons

> The output is done every build and many times

It is OK since it tells you about bad practices. Following good practices (like keeping your browsers actual and avoid unnecessary polyfills) will improve webapp performance for everyone.

I am closing this issue since we improved docs, and you didn’t show why this warning was irrelevant for your case. It is OK to be mad, but note that this warning is telling about important thing.
