### ISSUE TITLE
update: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by Beraliv** [browserslist/browserslist#657]
Hey 👋

Thank you for the great project!

I'm currently trying to update my `yarn.lock` and faced the issue that `integrity` is missing in my yarn.lock. Short example of what I have now:

```yaml

caniuse-lite@^1.0.30001202:
  version "1.0.30001242"
  resolved "https://registry.yarnpkg.com/caniuse-lite/-/caniuse-lite-1.0.30001242.tgz#04201627abcd60dc89211f22cbe2347306cda46b"

caniuse-lite@^1.0.30001219:
  version "1.0.30001223"
  resolved "https://registry.yarnpkg.com/caniuse-lite/-/caniuse-lite-1.0.30001223.tgz#39b49ff0bfb3ee3587000d2f66c47addc6e14443"

caniuse-lite@^1.0.30001228:
  version "1.0.30001228"
  resolved "https://registry.yarnpkg.com/caniuse-lite/-/caniuse-lite-1.0.30001228.tgz#bfdc5942cd3326fa51ee0b42fbef4da9d492a7fa"
```

That's why it tries to access the third line and cannot find it

Do you think we can add `if` here?

https://github.com/browserslist/browserslist/blob/2c292532b068606202567ddefc17415ab92e472d/update-db.js#L154-L159

Let me know if I can fix it

More details:

1. Versions
```bash
➜ npx --version
8.0.0
➜ yarn --version
1.22.17
➜ node -v
v16.11.0
```
2. `yarn lockfile v1`
3. Project where I run it – https://github.com/Beraliv/beraliv.dev

**Comment by ai** [comment]
Yeap, can you send PR with `if` to save your name in the project’s history?

It seems like it is just an edge case and `if` is the best solution.

**Comment by Beraliv** [comment]
@ai i will send it today in the evening!

**Comment by Beraliv** [comment]
@ai sent it yesterday, please feel free to check it when you have time 🙏

**Comment by ai** [comment]
@Beraliv sorry, I am in computer game (Black book). Hope to finish it before the weekend.

**Comment by Beraliv** [comment]
> @Beraliv sorry, I am in computer game (Black book). Hope to finish it before the weekend.

All good 🙏, just wanted to let you know if you didn't see it

**Comment by Ponjimon** [comment]
I'm not sure if I'm doing something wrong, but I still get exactly the same error when running `npx browserslist@latest --update-db`.

```
$ npx browserslist@latest --update-db
Latest version:     1.0.30001292
[redacted]/node_modules/@babel/core/node_modules/browserslist/update-db.js:145
        lines[3] = latest.dist.integrity ? lines[3].replace(
                                                    ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at [redacted]/node_modules/@babel/core/node_modules/browserslist/update-db.js:145:53
    at Array.forEach (<anonymous>)
    at updateYarnLockfile ([redacted]/node_modules/@babel/core/node_modules/browserslist/update-db.js:134:10)
    at updateLockfile ([redacted]/node_modules/@babel/core/node_modules/browserslist/update-db.js:199:12)
    at updatePackageManually ([redacted]/node_modules/@babel/core/node_modules/browserslist/update-db.js:205:22)
    at updateDB ([redacted]/node_modules/@babel/core/node_modules/browserslist/update-db.js:291:5)
    at Object.<anonymous> ([redacted]/node_modules/@babel/core/node_modules/browserslist/cli.js:40:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

Do I need to explicitly add browserlist as a dependency or add the latest version to the `resolutions` field in `package.json`?
