### ISSUE TITLE
Unable to upgrade + Incorrect delegation of responsibility - "Browserslist: caniuse-lite is outdated. Please run: npx browserslist@latest --update-db"

### ISSUE THREAD

**Issue by Domiii** [browserslist/browserslist#663]
Browserslist is not my own dependency. In fact:

```
> yarn why browserslist
yarn why v1.22.4
[1/4] Why do we have the module "browserslist"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "browserslist@4.16.6"
info Reasons this module exists
   - "_project_#webpack" depends on it
   - Hoisted from "_project_#webpack#browserslist"
   - Hoisted from "_project_#@babel#core#@babel#helper-compilation-targets#browserslist"
   - Hoisted from "_project_#@babel#preset-env#core-js-compat#browserslist"
```

When trying to update, as expected, I am told that I don't have it:

```
> npx browserslist@latest --update-db
Need to install the following packages:
  browserslist@latest
Ok to proceed? (y)
```

If I confirm, it still does nothing (probably because I don't have a direct dependency on `caniuse-lite` either):

```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
Latest version:     1.0.30001286
Installed version:  none
Removing old caniuse-lite from lock file
Installing new caniuse-lite version
$ yarn add -W caniuse-lite
(other dependency's warnings omitted here)
Cleaning package.json dependencies from caniuse-lite
$ yarn remove -W caniuse-lite
(other dependency's warnings omitted here)
caniuse-lite has been successfully updated
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

No target browser changes
```

Not sure if you can fix this?

(It does not seem ideal to have unfixable warnings and no-op recommendations thrown around by third-party dependencies)

**Comment by ai** [comment]
> probably because I don't have a direct dependency on caniuse-lite either

You do not need `caniuse-lite` in direct dependencies. We are using our own script to update all nested copies of `canisel-lite` in your dependencies tree.

> Not sure if you can fix this?

You can use any other way to update `node_modules` dependencies. For instance, you can run `npm update`.

`npx browserslist@latest --update-db` is just a script for 95% use cases. You do not need to use it. You need to keep `caniuse-lite` fresh.

**Comment by Domiii** [comment]
@ai The problem is that the `--update-db` command does not do anything. That's a bug, no?

It says:

```
Latest version:     1.0.30001286
Installed version:  none
```

And once it finishes, it did not change anything, and the warnings remain.

Not sure what to make of that.

**Comment by ai** [comment]
Could be a big or a rare environment edge case.

Just call `npm update` instead.

**Comment by Domiii** [comment]
@ai I'm using `yarn`, not `npm`

**Comment by ai** [comment]
`yarn upgrade` in this case.

You do not need to have direct updates. `yarn upgrade` should update indirect versions too.

**Comment by Domiii** [comment]
@ai It is not possible to `upgrade` indirect dependencies, as explained [here](https://github.com/yarnpkg/yarn/issues/4986).

The only way here seems to manually modify `yarn.lock`, but as pointed out [here](https://github.com/yarnpkg/yarn/issues/4986#issuecomment-916377528), that is a terrible idea.

Can you PLEASE add a way to just update the database file without causing potential [diamond dependency conflicts](https://jlbp.dev/what-is-a-diamond-dependency-conflict) by installing it directly?

Why? Having to sift through literally dozens of these pointless warning messages when working in certain CLI environments is really quite troublesome. It is causing quite the headache.

**Comment by ai** [comment]
> It is not possible to upgrade indirect dependencies, as explained here.

This issue is about updating the single indirect dependency.

`yarn upgrade` works. It is just update all dependencies.

If you do not want to update all dependencies, you need to change `yarn.lock` file. You do not need to do it manually. There are many tools to do it.

> literally dozens of these pointless warning messages

They are not pointless. Having old `caniue-lite` slow down your JS bundle a lot by adding unnecessary polyfills.

**Comment by Domiii** [comment]
I still disagree with this heavy-handed approach, but I also do understand why you feel so strongly about it.

On the plus side, I finally found out why this warning is so egregious to me:
I found that I got the warning even when using node (no browser involved), which was the most frustrating aspect of this.

When targeting `node`, the warning still appears, unless `targets: ...node...` is explicitely added to babel options (not just `@babel/preset-env`).

`babel.config.js`:


```js
const targets = {
  node: 16
};

module.exports = {
  targets,   // <- this prevents `browserslist` warnings
  presets: [
    [
      '@babel/preset-env',
      {
        targets,
        // ...
      }
    ]
  ]
  // ...
};
```

**Comment by mmkal** [comment]
@ai I think this message is too aggressive. I am seeing this it in a node project, when running `eslint`, with no babel config at all. I don't have caniuse-lite, browserslist, or even babel as a dependency. Am I really supposed to add babel and a config specifying that this a `node` target just get this warning, which is totally irrelevant to my project, to go away??

**Comment by ai** [comment]
> I don't have caniuse-lite, browserslist, or even babel as a dependency.

Call `npm ls` to see who use `browserslist`.

The problem is not a warning, but too big complexity of some tools, which wasn’t configured correctly because of many reasons.

**Comment by ai** [comment]
Hiding this warning will not solve the core of the problem that your build tool could be slowed down by many unnecessary polyfills.

You need to fix the source of the problem, not blaming a people who tell you about the problem.

**Comment by mmkal** [comment]
@ai I'm sorry if I gave the impression I was blaming any particular people. The problem, to me, is that `browserslist` - the tool, not the people behind it - is incorrectly assuming that a node project is cares about browsers. It's possible that it's being confused by a default babel configuration in eslint, maybe? But the warning message is devoid of context so it's hard to say. I don't think it's right for a library that is typically so deep in dependency trees to confidently say "there's a problem in your setup". The only real problem, as far as some users are concerned, is that an irrelevant message is being printed out to stderr. Performance is fine, functionality is fine.

Note: in my case, this is in a rush project, and `npm ls` doesn't work. I'm not sure When you say "your build tool", do you mean eslint? babel? babel's default config? Seems really strange to require users who aren't explicitly using babel to have to debug this. I agree that overly-complex dev dependencies are a general issue. I disagree that browserslist should be talking about it by saying "caniuse-lite is outdated".

I don't want to be unconstructive though: what if `browserslist` did something like:

```js
const packageJson = require(process.cwd() + '/package.json')
const projectCaresAboutBrowserslist = !!packageJson.browserslist

if (!projectCaresAboutBrowserslist) return
```

before printing the message?

**Comment by Domiii** [comment]
> > I don't have caniuse-lite, browserslist, or even babel as a dependency.
> The problem is not a warning, but too big complexity of some tools, which wasn’t configured correctly because of many reasons.


# The Problem

Well, JavaScript tools and toolchains in 2022 are complex.

If the problem is that a `node` project has non-node `targets` (or, similar to my case, not configured `target` at all or otherwise incorrectly), the warning should reflect that the `target` is wrong, and not just assume that an outdated `browserslist` version causes trouble.

This means that the warning (as it is right now) is incorrect. The problem is not that `browserslist` is out of date, but that the `target` was configured incorrectly.


# Possible Solutions?

I would suggest that there should be a complete website dedicated to the different problems covered by your (may I say: very crude?) detection mechanism, that goes way more in depth on this issue.

Specifically, I would suggest that if you take it upon yourself to aggressively warn about problems that are often times introduced by third-party providers, you might want to provide a proper way to deal with it, not just make a single one-shoe-fits-all suggestion that does not work half of the time.

If you don't want to (or don't have the resources to) improve upon your warning mechanism, maybe it should not warn so aggressively, or at least allow for a silencing option...?

**Comment by ai** [comment]
@mmkal the problem is that with wrong setup we can’t detect that project care about browsers or now.

`!!packageJson.browserslist` will not work. Many web apps (which care about browsers) are using default Browserslist and do not have `packageJson.browserslist`.

> When you say "your build tool", do you mean eslint? babel? babel's default config?

I am not sure. To detect who called Browserslist in Node’s project, I need to spend a time for investigation.

It will be better if you will do this research because it will not put all work on me.

@Domiii 

> I would suggest that the warning could at least link to a complete website dedicated to all the different problems covered by your (may I say: very crude?) detection mechanism, that goes way more in depth on this issue.

It is an excellent idea. But it requires too much time, which I do not have. It is a problem with Browserslist funding.

> least allow for a silencing option

This option will be used by user with real problem of unnecessary polyfills. I'm afraid that adding this option will slow down the Internet because more webapps will have bigger JS bundles.

> maybe it should not warn so aggressively

What do you suggest here? Note that we still should be visible for webapps developers since outdated `caniuse-lite` is a big problem of webapps performance.

**Comment by BillyWM** [comment]
The developer's attitude here is very disappointing; it's patronizingly paternalistic to tell people that they can't be trusted to build software in a certain manner and you need to save them from themselves and in the process heroically save the web itself. 

.....and weirder still he himself added a silence option back in 2019. I tracked it down manually and I'm just sharing it here. You can set property in your environment variables (`process.env`) which will silence the warning:

`process.env['BROWSERSLIST_IGNORE_OLD_DATA'] = true;`

**Comment by quteharry19** [comment]
`yarn upgrade` resolved for me

**Comment by kentr** [comment]
For those wanting a [more targeted upgrade](https://stackoverflow.com/a/65168325/205878) with npm:

```
npm --depth 20 update --save caniuse-lite browserslist 
```

`--depth` is deprecated and will throw a warning, however the command worked for me and only updated a few packages instead of a full `npm update`.

**Comment by LucasRobs** [comment]
> `yarn upgrade` resolved for me

work for me

**Comment by jerimiah797** [comment]
> Therefore you can set a property in your environment variables (`process.env`) which will silence the warning:
> 
> `process.env['BROWSERSLIST_IGNORE_OLD_DATA'] = true;`
> 
> (or whichever method is relevant to your project, e.g. the dotenv pattern etc)

This worked for me. The ci system that my headless jest API tests run on is unable to run `npx` commands to update the db. This ENV variable silences the (unneeded in my use case) warnings. Thank you, @BillyWM

**Comment by aprilandjan** [comment]
> Therefore you can set a property in your environment variables (`process.env`) which will silence the warning:
> 
> `process.env['BROWSERSLIST_IGNORE_OLD_DATA'] = true;`
> 
> (or whichever method is relevant to your project, e.g. the dotenv pattern etc)
> 
> At the very least this warning should provide some guidance on how to perform the upgrade when this is a nested dependency, as it will be probably most of the time, since it's used by Babel (and thereby most React devs)

Just want to remind that this ENV is supported in browserslist@4.5.5 or greater

**Comment by ai** [comment]
@Vrq don’t delete unknown warning. Very likely that you are using Browserslist for Babel. Without updating database, your JS bundle will be slower (which effect on the business).

**Comment by Vrq** [comment]
I am using Create React App and would be glad to get rid of the underlying problem.
Do you have a suggestion how to solve it?

**Comment by ai** [comment]
@Vrq Create React App uses Babel inside and `caniuse-db` update is important for every application on top of Create React App.

Without `caniuse-db` update your web app will be slower, and your business will lose money.

**Comment by Vrq** [comment]
Why does it slow down the app? 
Is there a way to opt-out of this feature altogether?

**Comment by ai** [comment]
@Vrq with old `caniuse-lite` database, Browserslist will tell to Babel very old browsers versions as that actual browsers. So Babel will insert unnecessary polyfills. These polyfills will bloat JS bundle and will slow down JS code (polyfill often slower than actual method).

**Comment by Vrq** [comment]
Is it possible to disable the polyfills?

**Comment by ai** [comment]
@Vrq without polyfills your modern JS code will not work in modern browsers. Even actual browsers don’t support all standards.

Also, it is CRA, there is no many things you can configure there and Babel enabled in CRA.

**Comment by Vrq** [comment]
Thanks for the explanation!
When I use the npx update-browserslist-db@latest command, it installs a caniuse-lite package to prod dependencies - is this supposed to be like that?

**Comment by ai** [comment]
> When I use the npx update-browserslist-db@latest command, it installs a caniuse-lite package to prod dependencies

Yes. Unfortunately, there is no easy way to update nested dependency in npm.

You can try to use any other package for nested dependency update. Or move to pnpm which have simple `pnpm update -r caniuse-lite` command.

**Comment by logan-xyz** [comment]
pnpm update -r don't work for me, i'm using pnpm

**Comment by Henery002** [comment]
> 

but didn't worked for me.

**Comment by Henery002** [comment]
> `yarn upgrade` resolved for me

but didn't worked for me🥺.

**Comment by RahulGuptaIIITA** [comment]
I did Yarn upgrade but after that I started getting error for yarn build


info  - Loaded env from /Users/poojagupta/Desktop/pp/collab-easy-fe/.env.local
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
It looks like you're trying to use TypeScript but do not have the required package(s) installed.

Please install @types/react by running:

	yarn add --dev @types/react

If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files in your pages directory).

error Command failed with exit code 1.

**Comment by Hema-chakri** [comment]
Hi,
I am also struggling with warnings due to
Browserslist:caniuse-lite is outdated. Please run:npx browserslist@latest --update-db

**Comment by vjohansen** [comment]
> . You do not need to do it manually. There are many tools to do it.

What are these tools?

**Comment by Hema-chakri** [comment]
oh, okay then i am facing an issue with authentication while trying to push my code to repository. My old peronal access token is expired. Now shall i continue with same git repository by creating a new personal access token?

**Comment by Kailash121212** [comment]
npx update-browserslist-db@latest

use this instead of recommended

**Comment by luisAzcuaga** [comment]
> npx update-browserslist-db@latest
> 
> use this instead of recommended

This worked for me without making a mess on the `lock` file!

**Comment by shellscape** [comment]
> npx update-browserslist-db@latest

This is not compatible with a project using pnpm FYI

**Comment by ai** [comment]
@shellscape use `pnpm dlx`
