### ISSUE TITLE
New website ideas

### ISSUE THREAD

**Issue by ai** [browserslist/browserslist#667]
Here are a ideas for new Browserslist website:

- [ ] Light/dark theme
- [ ] A short description of what is Browserslist and why it was created
- [ ] List with Browserslist’s queries
- [ ] The version of Browserslist and `caniuse-db` on the page (maybe a note that we should keep `caniuse-db` up to date).
- [ ] Field/textarea for queries (string, `package.json`, config file content). It will show selected browsers below.
- [ ] Each browser should have a link to Wikipedia
- [ ] Show release date and popularity for each browser version
- [ ] Warn about popular mistakes in queries:
  - [ ] Lack of `not dead` on `last X versions` query
  - [ ] Lack of diversity on queries for Western browsers only
- [ ] File upload for `in my stats` query
- [ ] Sponsors section (at least with Evil Martians logo)
- [ ] Link to a list with verified good configs and description of queries and reasons

Implementations:

- [ ] No React, Vue, or any other JS framework for better performance.
- [ ] Avoid vendor lock-in services for deployment. Cheap Docker image for Google Cloud Run is better than “free” Vercel.

**Comment by ai** [comment]
@usmanyunusov I am planning to start design after ideas collecting

**Comment by igorlukanin** [comment]
Great ideas, @ai! Here's what @dangreen and I would like to see here as well:

>  Each browser should have a link to Wikipedia

We can also show release dates for the most recent version and current usage stats for each browser.

We can also add charts that show historic usage stats for browsers — might help to promote browser diversity, e.g., by showing that the usage of certain browsers is not declining, etc. We can spin up an API with [Cube](https://github.com/cube-js/cube.js) for that and just fetch the data from the front-end.

> Field/textarea for queries

We can support uploading stats from analytics and support the "in my stats" query as well.

**Comment by zulhilmyyjimmy** [comment]
P
