### ISSUE TITLE
`--update-db` fails with yarn, "No package matched your request"

### ISSUE THREAD

**Issue by IanVS** [browserslist/browserslist#675]
Hi, I'm attempting to run `npx browserslist@latest --update-db` in my yarn monorepo project.  When I do, I get this:

```
node:child_process:903
    throw err;
    ^

Error: Command failed: yarn info caniuse-lite --json
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at getLatestInfo (/Users/ianvs/code/storybook/storybook-builder-vite/node_modules/browserslist/update-db.js:48:20)
    at updateDB (/Users/ianvs/code/storybook/storybook-builder-vite/node_modules/browserslist/update-db.js:202:16)
    at Object.<anonymous> (/Users/ianvs/code/storybook/storybook-builder-vite/node_modules/browserslist/cli.js:40:3)
```

And, when I try to run `yarn info caniuse-lite --json` directly, I get:

```
Usage Error: No package matched your request
```

This is with yarn `3.1.1`.

**Comment by IanVS** [comment]
It looks like the correct way to do this with yarn 2+ is `yarn npm info` (https://yarnpkg.com/cli/npm/info)

**Comment by IanVS** [comment]
I cloned this repo, and ran it manually via `node path/to/browserslist/cli.js --update-db`, and it worked fine.  I was hoping to be able to help troubleshoot what was happening, but I guess it seems related to npx.  `yarn dlx browserslist --update-db` also works fine, so that's what I'll use going forward, I suppose.  Feel free to close if you'd like.

**Comment by ai** [comment]
Can you send PR with correct command?

**Comment by IanVS** [comment]
Unfortunately no, the code is already doing the right thing, it seems, and it's failing only when run via `npx`.  I'm not sure exactly how to debug it in that case.  Perhaps it's just something odd in my own environment.

**Comment by Danon** [comment]
And when you run it directly from `.bin`:
```
 .\node_modules\.bin\browserslist --update-db
```
it says
```
PS C:\Users\Daniel\WebstormProjects\4play> .\node_modules\.bin\browserslist --update-db
'npx' is not recognized as an internal or external command,
operable program or batch file.                            
Latest version:     1.0.30001399                                                                           
Installed version:  1.0.30001399                                                                           
caniuse-lite is up to date                                                                                 
caniuse-lite has been successfully updated                                                                 
                                                                                                           
Error: Command failed: npx browserslist                                                                    
'npx' is not recognized as an internal or external command,                                                
operable program or batch file.                  
```

I don't have `npm` and `npx` installed, I only use `yarn`.

**Comment by elderapo** [comment]
@Danon

> I don't have `npm` and `npx` installed, I only use `yarn`.

`yarn dlx` is an equivalent of `npx` in yarn so you should just be able to do:

```bash
yarn dlx browserslist --update-db
```

**Comment by Danon** [comment]
> @Danon
> 
> > I don't have `npm` and `npx` installed, I only use `yarn`.
> 
> `yarn dlx` is an equivalent of `npx` in yarn so you should just be able to do:
> 
> ```shell
> yarn dlx browserslist --update-db
> ```

Don't have it either.

```
C:\Users\Daniel\WebstormProjects\4play> yarn dlx
yarn run v1.22.19
error Command "dlx" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Shouldn't there be a way to pass shell argument to `--update-db` that allows standard execution without additional tools?
