### ISSUE TITLE
navigator.serviceWorker() is not supported in Android Browser 4.4.3-4.4.4

### ISSUE THREAD

**Issue by DVGY** [browserslist/browserslist#677]
navigator.serviceWorker() is not supported in Android Browser 4.4.3-4.4.4
I have a react project with webpack config
How can I exclude some the unwanted browsers ?
I tried `"not android all"` but it does not work. 

```
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all",
    "electron 1.6"
  ],
```

**Comment by ai** [comment]
`not android > 0`

**Comment by DVGY** [comment]
@ai is there any list these commands ?
I also want to exclude Biadu and few other browser

**Comment by ai** [comment]
https://github.com/browserslist/browserslist#queries
