### ISSUE TITLE
Only knows about and_chr 100?

### ISSUE THREAD

**Issue by bhollis** [browserslist/browserslist#682]
```
$ npx browserslist 'ChromeAndroid >= 91'
and_chr 100
```

I would have expected to see `and_chr 91` through `and_chr 100`? Similar queries like `last 2 ChromeAndroid versions` yield the same result, only `and_chr 100`.

caniuse-lite@1.0.30001324
browserslist@4.20.2

**Comment by sbusch** [comment]
See <https://github.com/Fyrd/caniuse/issues/6188#issuecomment-1052714906>
