### ISSUE TITLE
Should I update caniuse-lite eventhough I'm using my own stats

### ISSUE THREAD

**Issue by miqdadfwz** [browserslist/browserslist#683]
Hi this is not an issue report, I just have a simple question.

I have my own browserslist-stats.json in my repo but I keep getting a warning telling that caniuse-lite is oudated. Is it safe to completely ignore this warning since I'm using my own stats?

Thanks!

**Comment by ai** [comment]
> Hi this is not an issue report, I just have a simple question.

It is better to use Discussions for questions

> I have my own browserslist-stats.json in my repo but I keep getting a warning telling that caniuse-lite is oudated. Is it safe to completely ignore this warning since I'm using my own stats?

Not. You need fresh `caniuse-lite` not only for market share, but also for queries like `last 2 versions` and overall browser versions.

Browsers release a new version every month. Without data of these versions, Autoprefixer or Babel will not be able to remove unnecessary prefixes/polyfills.
