### ISSUE TITLE
Error message for missing features

### ISSUE THREAD

**Issue by Dreamsorcerer** [browserslist/browserslist#684]
From: https://github.com/PSPDFKit-labs/browserslist.dev/issues/39
They think something should be fixed here.

If the 'supports' feature fails to recognise a name, there is no useful error message to explain what failed.

For example, I wanted to search for this intersection of features:
supports custom-elementsv1 and supports es6-module-dynamic-import and supports es6-class and supports replace-all and supports shadowdomv1

It seems that one of the values is not recognised, but it's rather difficult to figure out which one.

**Comment by ai** [comment]
Wendy error do el hace right now?

**Comment by Dreamsorcerer** [comment]
I think a cat just walked on your keyboard. :P

But, if you look at the linked issue, the developer says "right now browserslist isn't throwing a stable error for missing features."

My problem is that browserslist.dev just doesn't update anything if there is a missing feature, so I can't even tell there's an error at all.

**Comment by ai** [comment]
Can you help me: run Browserslist with broken query and copy the error?

**Comment by ai** [comment]
You can try any online IDE.

It is not cool to demand something from open-source maintainer who is working for free and avoid giving any help.

**Comment by Dreamsorcerer** [comment]
Didn't know online npm IDEs even existed. But, I just tried at npm.runkit.com/npm with:
```
require('browserslist')()
browserslist.coverage(browserslist('supports custom-elementsv1 and supports es6-module-dynamic-import and supports es6-class and supports replace-all and supports shadowdomv1', { stats }), stats)
```

And just get a reference error, I've no idea how to actually import it.

I'm just relaying the information from the other issue, as that author seems to think it's a problem here, but has neglected to open an issue. I maintain plenty of projects myself, so don't have the time to figure out how to run this. If it was one of my projects, I'd have no problem running 1 command from my own project, or looking directly at the source code for the errors being returned (and adding documentation for those errors).

**Comment by ai** [comment]
Here is what error I have in CLI:

```
$ npx browserslist 'supports custom-elementsv1 and supports es6-module-dynamic-import and supports es6-class and supports replace-all and supports shadowdomv1'
/home/ai/Dev/browserslist/cli.js:97
      throw e
      ^

Error: Cannot find module 'caniuse-lite/data/features/replace-all.js'
```

The error message is not very cryptic for my taste.

Do we really need to improve it?

Looks like the cryptic message was from browserslist.dev way to build JS bundle.

**Comment by ai** [comment]
Fixed by https://github.com/browserslist/browserslist/pull/714
