### ISSUE TITLE
`defaults` query returns unreleased browsers if `mobileToDesktop` enabled

### ISSUE THREAD

**Issue by g-plane** [browserslist/browserslist#695]
Running the query below:

```
pnpm browserslist 'defaults' --mobile-to-desktop
```

`op_mob` in the result above will contain `87` and `86`, but `87` isn't released, which the `release_date` is `null`. Is this intended?

**Comment by g-plane** [comment]
However, `opera` in the result is `86` and `85`.

For convenience, here is the result of `last 2 versions`:

```
and_chr 101
and_chr 100
and_ff 101
and_ff 100
and_qq 10.4
and_uc 12.12
android 101
android 100
baidu 7.12
bb 10
bb 7
chrome 101
chrome 100
edge 101
edge 100
firefox 101
firefox 100
ie 11
ie 10
ie_mob 11
ie_mob 10
ios_saf 15.4
ios_saf 15.2-15.3
kaios 2.5
op_mini all
op_mob 87
op_mob 86
opera 86
opera 85
safari 15.5
safari 15.4
samsung 16.0
samsung 15.0
```

**Comment by ai** [comment]
There is no Opera 87 version on Can I Use (Can I Use data is very inconsistency).

**Comment by g-plane** [comment]
Yes, that's why I'm confused. When `mobileToDesktop` enabled, mobile versions list comes from desktop. However, `opera` doesn't contain `87` while `op_mob` does.
