### ISSUE TITLE
Unknown version 16 of safari

### ISSUE THREAD

**Issue by Techn1x** [browserslist/browserslist#698]
I've just updated to `caniuse-lite 1.0.30001349` (currently latest) and I target this query `'supports es6-module and supports fetch'` but when building for it, this error occurs
`Unknown version 16 of safari`

Likely due to Apple releasing it very recently.

I'm using `browserslist 4.20.4` (currently latest)

I suspect that browserslist needs an update to recognise this version, is that correct? Or should I post elsewhere. Also, is there anything I can do to avoid this error occurring in future on every release of a new browser?

A gif of the browserslist website also not recognising safari 16
![Peek 2022-06-08 13-32](https://user-images.githubusercontent.com/1049837/172526127-e3c1b0e2-458a-4162-8b1b-1ed9fa1c1f9c.gif)

**Comment by ai** [comment]
> I suspect that browserslist needs an update to recognise this version, is that correct?

No, we need Can I Use update.

Browserslist use it for the browsers data.

There is nothing (expect bloody hacks) which we can do on Browserslist side.

**Comment by Techn1x** [comment]
Ok, so it's an issue with caniuse-lite then... :/ sorry it can be difficult to figure out which part of the system is responsible when things break

**Comment by mickeyjoes** [comment]
Get same issue since yesterday with target `supports cryptography` and our build breaks with 
`BrowserslistError: Unknown version 16.0 of safari
    at Array.reduce (<anonymous>)`

**Comment by al4str** [comment]
@Techn1x, @mickeyjoes you can `npm i caniuse-lite@1.0.30001346` as temporary fix

**Comment by mickeyjoes** [comment]
Thanks @al4str for that! 
It finally worked in my case, though I had to force dependency `"caniuse-lite": "1.0.30001346"` in package.json instead of `"caniuse-lite": "^1.0.30001346"`.

Note: I tried earlier the new update `caniuse-lite 1.0.30001350` from today, but it didn't work either.

**Comment by NKeil** [comment]
Thanks for the temp-fix, been looking for what was causing this issue all day. I also had to add an override to package.json for browserslist:
```
"overrides": {
    "browserslist": {
      "caniuse-lite": "1.0.30001346"
    }
  }
```

**Comment by ai** [comment]
The new versions of Can I Use was released. Did they fix the problem?

**Comment by NKeil** [comment]
Yep, can confirm new Can I Use version is working.
