### ISSUE TITLE
Remove Internet Explorer by default

### ISSUE THREAD

**Issue by nickmccurdy** [browserslist/browserslist#699]
Now that Microsoft is already redirecting Internet Explorer to Edge automatically, I'd argue it's already dying, and will be dead once support ends on June 15th.

**Comment by ai** [comment]
Agree. Let's wait a week-two for everyone to update and then will add it to `dead`.

**Comment by ntwb** [comment]
Hey,

Thinking of the corporate and enterprise markets, does anyone know more details on this auto-redirection policy, I’m wondering if this market might be using MSFT Group Policy to prevent those redirects.

I’ve got clients in Asia & Africa that still have IE requirements unfortunately and am thinking about how to continue supporting this in some way until they are in a position to remove that IE support

**Comment by ai** [comment]
@ntwb why custom Browserslist is not a solution for these clients?

You can add Browserslist config without `not dead` query. Or use `not dead, ie 11`.

**Comment by ntwb** [comment]
Thanks @ai, yes, this should work, I will test it now

**Comment by zloirock** [comment]
I hope that it will be a major bump of `browserslist` version.

**Comment by ai** [comment]
@zloirock why it should be major bump?

We didn’t change the meaning of `dead` query. We change browsers in all queries (like `last 2 version` or `> 1%`) without major bump.

**Comment by zloirock** [comment]
Removing IE from defaults will be unexpected for many users. Even if it's no longer maintained by MS, too many companies are forced to maintain it for many different reasons, the most of them who use `browserslist` directly do not specify IE and use `defaults`. If it will be updated without a major bump, it will break their products.

**Comment by ai** [comment]
> Even if it's no longer maintained by MS, too many companies are forced to maintain it for many different reasons, the most of them do not specify IE directly and use defaults.

If they need to support IE 11, they should explicitly explain it in Browserslist config by adding `ie 11`.

If we do not add IE 11 to `dead` query it will be breaking changes, since our contract with users was that `dead` will be actual.

(Also if we will add IE 11 to `dead` in major bump it will lead to big problems in ecosystem since different tools will have different target browsers for the same Browserslist config)

**Comment by zloirock** [comment]
It's your choice. I just said that without it you will break too many products. And this breakage can be a more significant problem than updating the ecosystem.

**Comment by RiZKiT** [comment]
Alright, now I know why our transpilation did not worked anymore as expected, we had "> 0.5%, ie 11, not dead", which worked before, instead of "> 0.5%, not dead, ie 11" which works now. 🙄
