### ISSUE TITLE
v4.21.0 Packaging error

### ISSUE THREAD

**Issue by MR-QXJ** [browserslist/browserslist#707]
*v4.21.0* Packaging error, limited to version *4.20.x* is no problem
nodejs **v14.17.6**
![image](https://user-images.githubusercontent.com/45258968/175476211-83f2167e-b3d3-42e7-98ee-be2ad7be8fd7.png)

**Comment by ai** [comment]
I do not see Browserslist in the stack.

Maybe you have a problem because you lost IE 11 from browsers? Try to create `.browserslistrc` file with `defaults, ie 11` content.

**Comment by MR-QXJ** [comment]
After adding `ie 11` to the `.browserslistrc`, no error is reported; But we can compile normally without adding `ie 11` before the 4.21 update.  This is the content of the previous `.browserslistrc`:
![image](https://user-images.githubusercontent.com/45258968/175509255-0641ecf3-d511-41ac-b838-10f5416fb3ec.png)

**Comment by ai** [comment]
> This is the content of the previous .browserslistrc

Before 4.21 `not dead` does not include `ie 11`. You had IE 11 in your previous `.browserslistrc` and after update to 4.21 you stopped to have IE 11.

IE 11 was added to `dead` only in Browserslist 4.21.

> Packaging error

You have a problem with `?.` syntax. Before you had IE 11 and babel-preset-env polyfills it. With Browserslist 4.21 you do not need to polyfill `?.` anymore, but your bundler do not support `?.` and start to throw an error.

Update your bundler (for instance, webpack) to support the latest JS syntax,

**Comment by MR-QXJ** [comment]
thanks
