### ISSUE TITLE
Outdated version for latest Firefox ESR

### ISSUE THREAD

**Issue by binyamin** [browserslist/browserslist#711]
The data hard-codes `Firefox 91` as the latest extended-support release (ESR) for Firefox. Regardless of whether this is a good idea, [Firefox released a new ESR today](https://www.mozilla.org/en-US/firefox/102.0.1esr/releasenotes/) (102).

https://github.com/browserslist/browserslist/blob/066c0fa75f18d6b1e9a072d57d60fe3bfdf9bc37/index.js#L995

It might be a good idea to rig up some reminder or automation, because [they release a new one every 42 weeks](https://support.mozilla.org/en-US/kb/choosing-firefox-update-channel). It's even possible that you can hard-code a single ESR release, and advance 42 weeks until you find the latest ESR version. I don't know if that's how it works, though it shouldn't be too difficult to cross-check.

**Comment by ai** [comment]
I had this reminder but then ESR schedule page or was closed.

Where I can find the release schedule?

**Comment by ai** [comment]
https://wiki.mozilla.org/Release_Management/Calendar

Will use it to make an alarm

**Comment by ai** [comment]
Fixed 8cd0597

**Comment by ai** [comment]
The fix was released in 4.21.2.
