### ISSUE TITLE
Case sensitive?

### ISSUE THREAD

**Issue by CTimmerman** [browserslist/browserslist#727]
[I noticed](https://github.com/microsoft/vscode-edge-devtools/issues/1168#issuecomment-1239647306) my `package.json` browserlist only worked with `firefox` instead of `Firefox`.

**Comment by ai** [comment]
Browser names and queries are case insensitive:

https://browsersl.ist/#q=firefox+%3E+100
https://browsersl.ist/#q=Firefox+%3E+100

You have a very different error name:

```
Unknown browser query `{`
```

**Comment by CTimmerman** [comment]
I'll quote the relevant part of my comment here:

`package.json` does work with JSON config, except not the one above: `'input[type=datetime-local]' is not supported by Firefox < 93.` Turns out the browser name must be lowercase, as this `package.json` works:
```
{
	"browserslist": "defaults, firefox > 100"
}
```

**Comment by ai** [comment]
`defaults` contains Firefox 91 (`firefox esr`) https://browsersl.ist/#q=defaults

`,` is `OR` operator.
