### ISSUE TITLE
`npx browserslist@latest --update-db` ignores version overrides

### ISSUE THREAD

**Issue by RaazKH** [browserslist/browserslist#730]
It seems that the command `npx browserslist@latest --update-db`  does not respect "overrides" in the package.json file when updating the browser list.

**Comment by ai** [comment]
Can you show example?

**Comment by RaazKH** [comment]
Apologies, while preparing the example I noticed that I was running an older version of npm. Only versions 8.3 and above respect the overrides in the package.json file. This is not an issue for browserslist, apologies once again.

In case you are interested:
[Override dependencies for `npm install`](https://stackoverflow.com/a/70396201/13231224)
[package.json overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides)
