### ISSUE TITLE
iOS Safari 10 minor version queries not recognised

### ISSUE THREAD

**Issue by camslice** [browserslist/browserslist#732]
### Background

We display a page to users who have an outdated browser according to our `browserslist` configuration. For this we use `browserslist-useragent` to match the user agent string against our list of supported browsers, then redirect to an "Outdated browser" page.

### Description of the issue

Queries targeting minor versions of iOS Safari 10 are not recognised. All minor version of Safari 10 are treated as v10.0.0.

If I visiting our web page using Safari 10.1.x, 10.2.x or 10.3.x, I will be redirected to the "Outdated browser" page.

The following queries are not recognised:
```
ios_saf => 10.3
ios_saf => 10.2
ios_saf => 10.1
```

If I change the query to `ios_saf => 10` it work as expected, however I am unable to target minor versions as described above.

### How to reproduce

You can use either [`browserslist-useragent`](https://github.com/browserslist/browserslist-useragent) or [`detect-browser`](https://github.com/DamonOehlman/detect-browser) to reproduce, along with an iOS Device or Simulator running iOS => 10.1

**Comment by ai** [comment]
Browserslist CLI works correctly:

```
bpx browserslist "ios_saf >= 10.3"
ios_saf 16.0
ios_saf 15.6
ios_saf 15.5
ios_saf 15.4
ios_saf 15.2-15.3
ios_saf 15.0-15.1
ios_saf 14.5-14.8
ios_saf 14.0-14.4
ios_saf 13.4-13.7
ios_saf 13.3
ios_saf 13.2
ios_saf 13.0-13.1
ios_saf 12.2-12.5
ios_saf 12.0-12.1
ios_saf 11.3-11.4
ios_saf 11.0-11.2
ios_saf 10.3
```

Should we open this issue in `browserslist-useragent`?

**Comment by camslice** [comment]
Hmm, so it does. I'll open another issue `browserslists-useragent`.  I guess it could be related to the way they are matching the UA string. Do you mind if I leave this open for a little while though?

**Comment by ai** [comment]
I think it is better to close it and open again if we will find an issue in Browserslist core.

**Comment by camslice** [comment]
Thanks @ai
