### ISSUE TITLE
Feature Request: add nginx njs support

### ISSUE THREAD

**Issue by xiaoxiangmoe** [browserslist/browserslist#733]
njs compatibility list:
https://nginx.org/en/docs/njs/compatibility.html

babel preset:
https://github.com/jirutka/babel-preset-njs

**Comment by ai** [comment]
Do you want to add Browserslist config to `njs`? You need to open an issue there in this case. I am not a maintainer of njs.

Or they already support Browserslista and you want to add them to examples?

**Comment by xiaoxiangmoe** [comment]
Some other build tools, like swc, need to use `.browserslistrc` file as js runtime target.

**Comment by ai** [comment]
I agree. But you need to ask them to add `.browserslistrc` support.

You can open an issue and mention me, I will add extra details.

**Comment by xiaoxiangmoe** [comment]
@ai Hi, I create a issue there.
