### ISSUE TITLE
Can't query for Chrome Android under version `105`

### ISSUE THREAD

**Issue by NicolasBonduel** [browserslist/browserslist#734]
I am trying to match all `and_chr` versions.

I have tried to be creative and to use:
- `npx browserslist "and_chr > 0"`
- `npx browserslist "last 9999 and_chr versions"`

It always return `and_chr 105` for me, why won't it return all versions of Chrome for Android? Am I doing something wrong?

**Comment by ai** [comment]
Yes, this is limit of Can I Use
