### ISSUE TITLE
QQ browser query doesn't work 

### ISSUE THREAD

**Issue by chenzezhang** [browserslist/browserslist#736]
">= 0.1% in CN",
      "defaults",
      "Chrome>=45",
      "ie >= 10"

**Comment by ai** [comment]
I see `QQ Browser | 13.1` on this query: https://browsersl.ist/#q=%3E%3D+0.1%25+in+CN%2Cdefaults%2CChrome%3E%3D45%2Cie+%3E%3D+10

1. Try to update `caniuse-lite` and `browserslist`
2. Show output of `npx browserslist` command inside your project

**Comment by chenzezhang** [comment]
QQ Browser  | 10  query doesn't work

browserslist: 4.21.4

>= 0.1% in CN,defaults,Chrome>=45,ie >= 10, QQ Browser >= 10

browserslist: Unknown browser query `QQ Browser >= 10`. Maybe you are using old Browserslist or made typo in query.

https://browsersl.ist/#q=%3E%3D+0.1%25+in+CN%2Cdefaults%2CChrome%3E%3D45%2Cie+%3E%3D+10%2C+QQ+Browser+%3E%3D+10

**Comment by ai** [comment]
The name of QQ Browser is `and_qq`.

You need:

```
>0.1% in CN, defaults, Chrome>=45, ie >= 10, and_qq >= 10
```

Here is result: https://browsersl.ist/#q=%3E0.1%25+in+CN%2C+defaults%2C+Chrome%3E%3D45%2C+ie+%3E%3D+10%2C+and_qq+%3E%3D+10

Here is all browser’s names: https://github.com/browserslist/browserslist#browsers
