### ISSUE TITLE
Not intuitive `dead`/`not dead` query behaviour

### ISSUE THREAD

**Issue by Semigradsky** [browserslist/browserslist#741]
`not dead` looks the same as the other requests, and seems like it should return all 'not dead' browsers. Actually it is not.
`not dead` filters *previous* queries and remain only 'not dead' browsers.
As a result, two similar queries give different results:
```
'> 1%, not dead, ie 11' // has 'ie 11' in result
'> 1%, ie 11, not dead' // hasn't 'ie 11' in result
```

See also this comment: https://github.com/browserslist/browserslist/issues/699#issuecomment-1340291827

**Comment by ai** [comment]
What changes do you suggest?

**Comment by Semigradsky** [comment]
Ideally, I think that the syntax for `dead` should be changed, as it is really a filter. For example:
`'> 1%, not dead, ie 11'` -> `'not dead(> 1%), ie 11'`
`'> 1%, ie 11, not dead'` -> `'not dead(> 1%, ie 11)'`
And deprecate `, not dead, `/`, dead, `.

**Comment by Semigradsky** [comment]
At least this behavior can be described in README. Some developers still read the documentation. 😄

**Comment by Semigradsky** [comment]
> We already mention not behavior in docs.

> Some developers still read the documentation. 😄

Looks like I'm the kind of developer who doesn't read the full documentation. I used `browserslist` for years and don't know how 
 query with `not` actually works.

Feel free to close this 'issue'.

**Comment by ai** [comment]
Yes, seems like it is just a problem which we should ignore
