### ISSUE TITLE
Check if `process` is defined.

### ISSUE THREAD

**Issue by romainmenke** [browserslist/browserslist#745]
https://github.com/browserslist/browserslist/blob/74dbf959874e3c05adec93adab98832db35cb66b/index.js#L420

I am working on a new playground for `postcss-preset-env` and I am bundling everything so that I can apply transforms instantly in a browser.

- `postcss`
- `postcss-preset-env` and all included plugins
- `browserslist`
- ...

The only thing that didn't work immediately was `browserslist` because of the line with `process.env....`

Would it be possible to first check if `process` is defined?
Something like `if ('process' in self && ...`

I am now working around this by doing :
```js
self.process = { env: {} };
```

This is not blocking for me and totally fine to leave this as is.

**Comment by ai** [comment]
Sure. We did the `process`-less env support, just miss it after some PR.

Will do it on this week.

**Comment by romainmenke** [comment]
The new playground :)
https://preset-env.cssdb.org/playground/

**Comment by ai** [comment]
Fixed 643f025
