### ISSUE TITLE
In Typescript config

### ISSUE THREAD

**Issue by danny007in** [browserslist/browserslist#751]
how config shared value in target
```json
{
  "compilerOptions": {
    "target": "es2018",
   }
}
```

**Comment by Underewarrr** [comment]
@danny007in 
Add ES2018 to lib in tsconfig.json:

"lib": [
  "ES2018"
]

lib is different to target. target roughly means the JavaScript version of the generated output files. lib means the features you will use in TypeScript. For example, you can use new features in ES2018 ("lib": ["ES2018"]), but still target at ES6 ("target": "ES6"). Those new features will be translated to ES6 during compilation (this may be done via third party tools like babel, and some new features may not be translatable, but these are just implementation details).

**Comment by ai** [comment]
It will be nice to have Browserslist feature in TS, but we should move this issue to TS
