### ISSUE TITLE
browserslist: Unknown version 103 of android

### ISSUE THREAD

**Issue by massimocode** [browserslist/browserslist#753]
When running `npx browserslist@latest --update-db`, we get the following output: `browserslist: Unknown version 103 of android`.

browserslist never used to complain about the `android 103` in my browserslist file. Is `android 103` not a valid value? If so, why has this only recently started happening? It used to work fine before.

For some additional context, the `android 103` entry exists in our browserslist file due parsing the past 8 months of analytics data from our production website using the tool `browserslist-ga-export`.

**Comment by ai** [comment]
Unfortunately, Can I Use data is very fragile and we don't control it.

Some browsers (like `android`) has only the latest version in the database. Use different query.

If you will show me the config, I can suggest better strategy.

**Comment by massimocode** [comment]
We do the following to generate our browserslist file:
1) Log into Google Analytics and export data on browsers in the past 6 months, as per instructions here: https://github.com/browserslist/browserslist-ga-export#usage
2) Run the command `npx browserslist "> 0.1% in my stats" --stats=browserslist-stats.json` (pointing to the stats file generated in the previous step)
3) Update the caniuse-lite database `npx browserslist@latest --update-db`
4) Rebuild the project

**Comment by ai** [comment]
BTW, try also to update Browserslist (and be sure that you are using only single version across the lock file). We fixed a few bugs, maybe it could help.

You need to ask `browserslist-ga-export` about the solution for the browsers which have only latest version in Can I Use.

**Comment by massimocode** [comment]
@ai If you're able to suggest any better ways of us doing this, or have any other ideas (maybe specifically around the android thing), that would be great.

By the way, the generated browserslist looks like this:
```
and_chr 111
and_uc 13.4
android 103
chrome 106
chrome 105
ios_saf 16.0
ios_saf 15.5
ios_saf 15.4
ios_saf 15.2-15.3
ios_saf 15.0-15.1
ios_saf 14.5-14.8
ios_saf 14.0-14.4
ios_saf 13.4-13.7
ios_saf 12.2-12.5
safari 15.5
```

**Comment by ai** [comment]
I recommend removing `android` from the list because from polyfill side it is very close to `and_chr`

**Comment by massimocode** [comment]
> BTW, try also to update Browserslist (and be sure that you are using only single version across the lock file). We fixed a few bugs, maybe it could help.
> 
> You need to ask `browserslist-ga-export` about the solution for the browsers which have only latest version in Can I Use.

Regarding updating Browserlist (and making sure we're only using a single version), what's the best way of doing that? We don't have Browserlist in our package.json (it's in the lock file though). I think it's being used by autoprefixer.

**Comment by massimocode** [comment]
> I recommend removing `android` from the list because from polyfill side it is very close to `and_chr`

Thanks, we can try that too

**Comment by ai** [comment]
> Regarding updating Browserlist (and making sure we're only using a single version), what's the best way of doing that?

The best way is to update to `pnpm` (it only has a right tools). But since you will not be able to do it, you need to Google some hacky tools related to your package manager.
