### ISSUE TITLE
caniuse-lite is outdated

### ISSUE THREAD

**Issue by diegoolavarria** [browserslist/browserslist#755]
When compiling my React project, I get the following warning, and gets stuck:

![image](https://user-images.githubusercontent.com/15364801/233172344-c30383a5-61a5-426f-963e-e837bebd4251.png)

And, when updating caniuse-lite in my package.json, the compilation gets broken.

**Comment by ai** [comment]
> when updating caniuse-lite in my package.json, the compilation gets broken

What exactly is the problem?

Note that `caniuse-lite` update will update polyfills, which could lead to changes in the app.

**Comment by marvinthepa** [comment]
When I update caniuse-lite to the latest version (a mere 17 hours old) I still get the warning.

Could it be that the logic is wrong:

```
function latestReleaseTime(agents) {                                  
  var latest = 0                                                                               
  for (var name in agents) {
    var dates = agents[name].releaseDate || {}                                                 
    for (var key in dates) {                                                                   
      if (latest < dates[key]) {                      
        latest = dates[key]                                                                    
      }                                                                     
    }                                                   
  }                                                                                            
  return latest * 1000                       
}
```

if you use `latest < dates[key]` in the if statement, you do not get the latestReleaseTime, but the oldest release time.
IMVHO it should be `latest > dates[key]`. Or the method name should be renamed do oldestRelaeseTime, if it is was you intend, that you want to warn if the oldest supported browser is older than 6 months (which IMHO, is not a valid warning for some applications, namely enterprise applications that are not exposed to the Internet).

**Comment by marvinthepa** [comment]
Yeah sorry, of course I was wrong *facepalm*.

> @marvinthepa very likely some tool bundled caniuse-lite inside and update script doesn’t update this bundled version.

No, I checked yarn.lock, this is the only entry:

```
caniuse-lite@^1.0.0, caniuse-lite@^1.0.30000981, caniuse-lite@^1.0.30001109, caniuse-lite@^1.0.30001400:                                                                                                                                                                                                                                                                                    
  version "1.0.30001495"                                                                                                                                                                                                                                                                                                                                                                    
  resolved "https://zpackage-proxy.genua.de:4873/caniuse-lite/-/caniuse-lite-1.0.30001495.tgz#64a0ccef1911a9dcff647115b4430f8eff1ef2d9"                                                                                                                                                                                                                                                     
  integrity sha512-F6x5IEuigtUfU5ZMQK2jsy5JqUUlEFRVZq8bO2a+ysq5K7jD6PPc9YXZj78xDNS3uNchesp1Jw47YXEqr+Viyg==
```

https://www.npmjs.com/package/caniuse-lite/v/1.0.30001495 was published 18 hours ago..

**Comment by marvinthepa** [comment]
@ai thanks for the (very quick!) clarification, and sorry for the noise.

Actually running update-browserslist-db did remove the warning, which did not go away when I updated caniuse-lite manually (which I only did because running npx update-browserslist-db is a pain because we use a npm proxy and the machine cannot reach npmjs.com directly)
