### ISSUE TITLE
Support Node 20

### ISSUE THREAD

**Issue by dburles** [browserslist/browserslist#756]
Node 20 isn't currently recognised, see: https://browsersl.ist/#q=node+20

**Comment by ai** [comment]
I will check for `node-releases` update

**Comment by ai** [comment]
Asked `node-releases` for a release https://github.com/chicoxyzzy/node-releases/issues/35

**Comment by pavog** [comment]
They released [v2.0.11](https://github.com/chicoxyzzy/node-releases/releases/tag/v2.0.11) and [v2.0.12](https://github.com/chicoxyzzy/node-releases/releases/tag/v2.0.12)

**Comment by ai** [comment]
Nice, now you will get a new Node.js versions on dependency update since Browserslist use `^` https://github.com/browserslist/browserslist/blob/main/package.json#L34
