### ISSUE TITLE
Electron versions missing

### ISSUE THREAD

**Issue by troppoli** [browserslist/browserslist#758]
Given a package.json config of
```
    "browserslist": [
        "Electron 19.0.6"
    ],

```
or
```
    "browserslist": [
        "Electron 19.1.9"
    ],

```

npx browserslist
chrome 102

However for 
```
    "browserslist": [
        "Electron 22.3.7"
    ],

```
npx browserslist
browserslist: Unknown version 22.3.7 of electron

```
    "browserslist": [
        "Electron 22.3"
    ],

```
npx browserslist
browserslist: Unknown version 22.3 of electron

But for 

```
    "browserslist": [
        "Electron 22.0"
    ],

```
npx browserslist
chrome 108

I expected v22 to behave the same as 19.

Thanks for what you do!

**Comment by ai** [comment]
The version exists in `electron-to-chromium` https://github.com/Kilian/electron-to-chromium/blob/master/full-chromium-versions.js#L2291

Try to update `electron-to-chromium` dependency (google nested dependency update for your package manager).

**Comment by troppoli** [comment]
Doing an
`npm update --depth 5
`
worked for me, your depth requirement may vary, but a regular update wasn't finding this.
-s
