### ISSUE TITLE
mobile-to-desktop option is negated by feature support

### ISSUE THREAD

**Issue by steverep** [browserslist/browserslist#761]
The `mobile-to-desktop` flag appears to be completely negated by adding an intersection with a feature query.  For example:

```
$ npx browserslist --mobile-to-desktop "defaults"
and_chr 113
and_chr 112
and_ff 113
and_ff 112
and_qq 13.1
and_uc 13.4
android 113
android 112
...
```

But adding any `supports` feature query produces different results:

```
$ npx browserslist --mobile-to-desktop "defaults and supports es5"
and_chr 113
and_ff 113
and_qq 13.1
and_uc 13.4
android 113
...
```

I get why this is happening since `caniuse` doesn't keep data on older mobile versions, but it seems to me that the entire point of the `mobileToDesktop` option is to assume that mobile version numbers act like their desktop counterparts, so this is definitely unexpected and should be fixed IMO.

**Comment by ai** [comment]
I will need a help with PR here since I am busy on another project right now
