### ISSUE TITLE
Time queries with mobileToDesktop do not work for Android

### ISSUE THREAD

**Issue by steverep** [browserslist/browserslist#762]
I would expect the following queries all to produce the same results:

- `last 1000 versions`
- `last 100 years`
- `since 1969`

Instead the latter 2 are different with `mobileToDesktop = true` because Android versions are not back-filled to the first evergreen version as with the first query.

**Comment by ai** [comment]
Please send PR. I am busy on another project and this issue is not looks critical.

**Comment by steverep** [comment]
We'll have to disagree on what is critical or not I guess.  Between this and #761, my experience has been that the `mobileToDesktop` option simply does not work as expected.

**Comment by ai** [comment]
I will accept and release PR very fast, don’t worry.

I just don’t want to spend my time, because I don’t use this feature. If you need it, you can help the project and fix it. Open source is a community work.
