### ISSUE TITLE
Android "last" queries incorrectly include Android 36

### ISSUE THREAD

**Issue by steverep** [browserslist/browserslist#764]
Found another issue while fixing #762.  The code correctly tries to limit Android to a minimum of 37, but the computations are flawed.  It incorrectly assumes that the version history is always just incremented by 1, but this was broken when Chrome/Android 82 was abandoned during the pandemic.  The result is that a minimum of 36 is being used instead.

Fix pending...

**Comment by ai** [comment]
Interesting user case. Wait for PR.
