### ISSUE TITLE
Converting to Typescript

### ISSUE THREAD

**Issue by naorpeled** [browserslist/browserslist#784]
Hey,
I'd like to work on converting this project to TypeScript.
Any objections? 🙏

**Comment by ai** [comment]
We will need an extra build step which will reduce project maintainability. Right now `npm` has the same sources as we have in GitHub. The paths in stacktrace are 100% equal, very easy to debug `browserslist` inside `node_modules`.

**Comment by ai** [comment]
I am using TypeScript only for applications. All my open source libraries are JS + `.d.ts`.

**Comment by naorpeled** [comment]
@ai for sure 🙏 

I had a misunderstanding,
that's why I marked this as completed.
Sorry for bothering you and thanks for replying ❤️
