### ISSUE TITLE
Mobile to desktop broken for Chrome/Android feature queries

### ISSUE THREAD

**Issue by steverep** [browserslist/browserslist#785]
As of 4.21.10, #767 seems to have regressed but only for and_chr and android:

```
$ ./cli.js  --mobile-to-desktop "Android > 0 or ChromeAndroid > 0 and supports es6-module"
and_chr 114
android 114
```

It's now only reporting the latest version.  Any idea what  happened here?

**Comment by steverep** [comment]
I suspect the problem is that the list of versions in the feature cache does not match the list of versions in the browser cache.

**Comment by ai** [comment]
PR will be needed. I am too busy on another open source project.

**Comment by steverep** [comment]
I should be able to fix it.  I'll try to get to it later this week.
