### ISSUE TITLE
usage query does not respect preceeding queries in a union

### ISSUE THREAD

**Issue by kirkwaiblinger** [browserslist/browserslist#788]
For some reason this browserlistrc ([playground link](https://browsersl.ist/#q=chrome+95%0Alast+1+chrome+major+versions+and+%3E+0.05%25))
```
chrome 95
last 1 chrome major versions and > 0.05%
```
gives only chrome 116 as a target.
whereas this one ([playground link](https://browsersl.ist/#q=last+1+chrome+major+versions+and+%3E+0.05%25%0Achrome+95))
```
last 1 chrome major versions and > 0.05%
chrome 95
```
gives chrome 116 and chrome 95.

I observe the same behavior if I use commas, or if I use a single line with or combinator.  I would expect that each line is treated as a union and therefore both variants would output chrome 116 and chrome 95.

**Comment by ai** [comment]
Sorry, it is how it works, and we can’t change it without major release (which is painful for the ecosystem).

`and` applies to a previous selector and reduce it.

**Comment by ai** [comment]
> Oh, so this is intentional?

I would say that the PR with `and` has no good research before and this is a result

> # And this isn't valid??

Yes, query can’t be started from `and`

**Comment by kirkwaiblinger** [comment]
Huh. More you learn
