### ISSUE TITLE
Change log message

### ISSUE THREAD

**Issue by MehdiDgrs** [browserslist/browserslist#789]
Hi i'm new to open source I would like to contribute to browserList because I had a little trouble with the log message.
When installing browserList 4.21.10 on windows I had this message : 

![browserlist](https://github.com/browserslist/browserslist/assets/94008225/691ed3ef-4dc0-4091-ae3e-cb1b6c395bab)

I would like to modify the line " $ yarn add -W caniuse-lite" by adding ' ... ' to specify that the package is downloading. 
I cant find the file that handles displaying the logs

**Comment by ai** [comment]
I don’t want to add `...` to bash command, since the commend stop be be valid. We can add `...` somewhere else, but I think it is better to add some custom loader there.

This code is here https://github.com/browserslist/update-db
