### ISSUE TITLE
Version mismatch between npmjs.com and private Azure DevOps registries

### ISSUE THREAD

**Issue by mirzakrzic** [browserslist/browserslist#796]
I have a private npm registry set up, and the version updated is done automatically...

I have noticed my CI/CD pipeline failing because it could not find the newest 4.22.1 version.
Upon further investigation I found out that info on npm.js is valid, latest is 4.22.1 built 19h ago
![image](https://github.com/browserslist/browserslist/assets/31995726/b250ebaf-3b9b-4587-b231-0f2985e3a4f3)

When I go into my private one, I see that latest version was built yesterday (which is correct) but the tag is wrong, it says 4.22.0 is the latest.
![image](https://github.com/browserslist/browserslist/assets/31995726/88900f5c-ba11-4a91-bbbc-d0b7ab31257f)

Any clue about the point of failure?

**Comment by ai** [comment]
Sorry, have no idea. 4.22.1 release process was exactly the same.

Very likely that problem is with private registry (you know software always have problems with cache).

**Comment by mirzakrzic** [comment]
You're right! I am sure now that the issue is on my side.

Sorry for the false alarm :D
