### ISSUE TITLE
caniuse-lite doesn't updated below 1.0.30001431 when run `npx update-browserslist-db@latest ` or `pnpm up caniuse-lite`

### ISSUE THREAD

**Issue by roadloser** [browserslist/browserslist#801]
Why is it necessary to install a version of "caniuse-lite" greater than 1.0.30001431 in the root directory's "package.json" when running commands, rather than updating the built-in "caniuse-lite" within "browserslist"?

now is [1.0.30001553](https://github.com/browserslist/caniuse-lite/blob/main/package.json)
[caniuse-lite below 1.0.30001431 or not in root path]
```
npx update-browserslist-db@latest 
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Latest version:     1.0.30001431
Updating caniuse-lite version
$ pnpm up caniuse-lite
caniuse-lite has been successfully updated
```

**Comment by ai** [comment]
Seems like you have an issue with npm registry. Maybe some cache issue.

It works on other cases without a problem.
