### ISSUE TITLE
Bug: cannot exclude kaios anymore

### ISSUE THREAD

**Issue by kkmuffme** [browserslist/browserslist#812]
https://github.com/browserslist/browserslist?tab=readme-ov-file#browsers specifies `kaios`

but:
https://browsersl.ist/#q=%3E0.1%25%0Anot+kaios
>Unknown browser query not kaios

Afair this was working fine before

**Comment by ai** [comment]
There is no query like `not [browser]` (for the reason because it is not a good way).

If you _really_ need it, you can try [`not kaios > 0`](https://browsersl.ist/#q=%3E0.1%25%0Anot+kaios+%3E+0), but first google why Kai OS phones is a big deal in Afrika.

**Comment by ai** [comment]
In this case you still need to use different query. For instance, `> 1% in US`.
