### ISSUE TITLE
Should I be able to use "extends @company/reponame/browserslist-config" 

### ISSUE THREAD

**Issue by boucodes** [browserslist/browserslist#814]
Hello! I ran into an issue after publishing our Browserslist configs and referencing them as such: 

@company/reponame/browserslist-config

I found these issues:
[]( https://github.com/browserslist/browserslist/issues/284) and [](https://github.com/browserslist/browserslist/pull/285 )

And they fall within the the same issue as I am having.  I'm wondering if it would be possible to update SCOPED_CONFIG__PATTERN to 

`var SCOPED_CONFIG__PATTERN = @[^/]+(?:\/[^/]+)?\/browserslist-config(?:-|$|\/)`

I can create the pr if it helps! 

Thank you!

**Comment by ai** [comment]
Why don't you want to create a separated package for that?

Using the big all-in package, I think, is not in the spirit of npm and prevent other to use your config.

**Comment by boucodes** [comment]
Valid question! I work for a public service that has a dozen of repos. The repos we are placing the configs in manages the standardized configs for every other repos. We've had that pattern for much longer than I have been working here, I can't imagine things changing. As we are a public service, this isn't for profit, but it's not a public repo.

**Comment by ai** [comment]
Yes, send PR

**Comment by ai** [comment]
Fixed by https://github.com/browserslist/browserslist/pull/816

**Comment by ai** [comment]
Released in 4.22.3.

**Comment by boucodes** [comment]
Thank you!
