### ISSUE TITLE
React error browserslist

### ISSUE THREAD

**Issue by Shinu87** [browserslist/browserslist#820]
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Invalid options object. Dev Server has been

**Comment by ai** [comment]
I am closing the issue because of the lack of details.

Open new issue with more details.

**Comment by Shinu87** [comment]
client@0.1.0 start
> react-scripts start

Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options.allowedHosts[0] should be a non-empty string.
 - after  Updating also it is giving same error
