### ISSUE TITLE
Firefox ESR Information outdated

### ISSUE THREAD

**Issue by sateffen** [browserslist/browserslist#827]
Hey,

using the following commands in my project creates completely outdated information about Firefox ESR:

```sh
$ npx update-browserslist-db
# -> just some install output, most important message:
# Latest version:     1.0.30001608

$ npx browserslist "Firefox ESR"
firefox 60
firefox 52
```

Firefox 60 and 52 are not the current ESR versions, the current ESR version is 115, with 128 becoming the next ESR version. See [here](https://whattrainisitnow.com/calendar/) for more information about current and upcoming releases.

Other versions, like current Chrome, Firefox or similar look all fine in the dataset, only Firefox ESR is outdated.

I assume the bug lies within [caniuse-lite](https://github.com/browserslist/caniuse-lite), but I think in this repository it's simpler to find for anyone else having the same issue.

**Comment by ai** [comment]
You need to regularly update `caniuse-lite` and `browserslist` to have the latest browsers data.

With the latest data, Browserslist will return correct FF 115
https://browsersl.ist/#q=FF+esr

**Comment by sateffen** [comment]
I double checked the dependency tree whether I have some old version installed, and you're right: Some transitive dependency depends on and old version of autoprefixer, depending on browserslist v3. `@babel/preset-env` depends on v4 and installs v4, but yarn resolves to v3 as the main version, and npx using v3 in CLI...

Enforcing browserslist v4 results in Firefox ESR being resolved as v115, just as expected.

Sorry for my blindness, thank you for your answer! Now I know the culprit and can fix my issue :smiley:
