### ISSUE TITLE
Add support for email clients

### ISSUE THREAD

**Issue by kkmuffme** [browserslist/browserslist#828]
It would be great if email clients could be added too from https://www.caniemail.com/ (https://www.caniemail.com/api/data.json)
It's only relevant for css, but would be a great addition

**Comment by ai** [comment]
We are limited to Can I Use data. You should convince them.

**Comment by ai** [comment]
> Is the limitation to caniuse a technical reason or just preference?

Historical reason.

Right now moving from Can I Use will break everything (and it is better to start another project with MDN data behind, etc).
