### ISSUE TITLE
Gaps in results for iOS vs. Safari desktop

### ISSUE THREAD

**Issue by steverep** [browserslist/browserslist#838]
When usage queries are involved, there's often a significant difference between the minimum iOS version and the minimum Safari desktop version.  For example, a result for "defaults" today yields iOS 15.6 vs. Safari 17.4.

As of iOS 15, the included Safari version is feature equivalent to the desktop version.  So in terms of transpiling code or adding polyfills, only the lower number of the two matters.  In other words, an option for adding Safari versions equal to iOS would be desirable.

A use case where this really makes a difference is when using `browserslist-useragent-regexp` to discern modern vs. legacy builds.  Taking the "defaults" example again, the current results end up serving the legacy build for desktop Safari 15 and 16, even though they would be very likely capable of running the modern build.

I think a case could be made for including this as part of the current `mobileToDesktop` option, perhaps by allowing it to accept a string keyword in addition to a boolean for backward compatibility.

**Comment by ai** [comment]
Can you suggest API changes? It is too abstract right now to think about it.

**Comment by steverep** [comment]
I think the API change would be either a new `--sync-safari` option, or something like `--mobile-to-desktop="include-safari"`.  I'd have to re-read the code to determine which is better.

**Comment by ai** [comment]
Can use show before and after results as example?

**Comment by steverep** [comment]
Current:

```
$ browserslist defaults | grep saf
ios_saf 17.5
ios_saf 17.4
ios_saf 16.6-16.7
ios_saf 15.6-15.8
safari 17.5
safari 17.4
```

New option:

```
$ browserslist --sync-safari defaults | grep saf
ios_saf 17.5
ios_saf 17.4
ios_saf 16.6-16.7
ios_saf 15.6-15.8
safari 17.5
safari 17.4
safari 16.6-16.7
safari 15.6-15.8
```

**Comment by ai** [comment]
The default Browserslist output contain `1%`. Of course `ios_saf` versions should be different from `safari` since iOS is much more popular.

**Comment by steverep** [comment]
Right, I understand that.  Per the OP though, that gap is really not meaningful at all to tools like Babel, and can be detrimental when turning the results into a regexp.  If your list includes iOS 15.6, I cannot think of any good reason not to also include Safari 15.6.

**Comment by ai** [comment]
> I cannot think of any good reason not to also include Safari 15.6.

Code complexity and unexpected behavior.

Adding too many features with tiny use base is a popular mistake to kill open source project by increasing code maintainability cost.

For your use case it is better just to explicitly specify:

```browserslist
ios_saf >= 15.6
safari >= 15.6
```
