### ISSUE TITLE
Add support for QtWebEngine

### ISSUE THREAD

**Issue by septatrix** [browserslist/browserslist#840]
QT is a framework to create native desktop GUIs and provides a web component based on chromium. This toolkit is used for several browsers in the Linux world ([qutebrowser](https://qutebrowser.org/), [Falkon](https://www.falkon.org/), [Angelfish](https://apps.kde.org/angelfish/), [Konqueror](https://apps.kde.org/konqueror/)) and by extension also for kiosk systems which display websites. Furthermore, many desktop applications embed it to show HTML content (think email clients, or embedded help pages in applications).

It would be great to support queries like `last 2 QtWebEngine versions` or maybe even `QtWebEngine LTS` and automatically translate that into the [corresponding chromium versions](https://wiki.qt.io/QtWebEngine/ChromiumVersions).

**Comment by ai** [comment]
We just using https://caniuse.com data and you should ask them to add new engine

**Comment by septatrix** [comment]
The usage data itself is already present. One would only need to convert the version to the chromium version. This is similar to #508 though for that the mapping between browser and chromium version is one-to-one whereas for QtWebEngine the version number is not equal to the chromium version (see the table linked above)

**Comment by ai** [comment]
It is very hard to support version mapping
