### ISSUE TITLE
Chrome for Android version always returns 131

### ISSUE THREAD

**Issue by ArthurClemens** [browserslist/browserslist#863]
Any setting, even pinning a version to `ChromeAndroid 103` will return 
```
and_chr 131
```
This can be observed in the playground: https://browsersl.ist/#q=ChromeAndroid+103

**Comment by ai** [comment]
Unfortunately it is limitation of Can I Use. It has only the latest version of each mobile browser.

There is a hacky way by using `mobileToDesktop` but it is pretty limited.

The proper solution requires rewriting Browserslist to MDN data, and I am waiting of some company to sponsor this.

**Comment by ArthurClemens** [comment]
That's unfortunate, because we are locking out users that should be able to use the site.
I understand the effort is beyond a simple FOSS project.

**Comment by ai** [comment]
Could you just use `Chrome 103` and then fix User Agent regexp a little for mobile?

**Comment by ArthurClemens** [comment]
Yes, I've made workaround.
